### ISSUE TITLE
list = list.slice(),I can't understand.

### ISSUE THREAD

**Issue by narutolby** [seajs/seajs#1058]
@lifesinger 
 Javascript is single-thread.So the multi-modification for the lists could't happen.
It means there's no chance to change dynamically.

**Comment by gdut-zdc** [comment]
@lifesinger 
例子当中的，在callback函数使用seajs.on()，删除 list.slice()其实并不会有 a,b,c这样的输出结果，因为此时 len 已经确定下来了，如果是 seajs.off() 便是会有出错了。但是我用的seajs版本是 3.0.0 的，估计以前的版本跟我的不一样，所以才会得出那样的结论，现在提出主要是为了方便其它人更好 的理解~
