### ISSUE TITLE
Sea.js 3.0 想法探讨

### ISSUE THREAD

**Issue by lifesinger** [seajs/seajs#1060]
Sea.js 拟推出 3.0 版本，新增原则：

> Mobile First

具体调整：
1. 开发时只支持 Chrome / Firefox 等现代浏览器，不支持 IE6-8. 需要在 Old IE 下运行的话，需要先构建，生成 id 和 deps 后才能在 IE 下正常运行。
2. 去掉 preload 功能？需要 preload 的组件，建议直接用 script 同步引入。preload 的初衷，是希望通过异步并行下载提高性能，但在非 IE 下，这种异步带来的性能优化已不明显。在移动端更意义不大。
3. 细节调整：去掉根据 sea.js 路径自动猜测 base 路径的功能。交给用户自己配置。

期待你的建议。

**Comment by kongjiea** [comment]
去掉根据 sea.js 路径自动猜测 base 路径的功能。交给用户自己配置？？
到底怎么配置 来个详细讲解啊，

**Comment by zuggs** [comment]
seajs.use是根据什么判断函数加载完的？为什么用seajs在ios8加载js有一定几率执行不下去？

**Comment by xiongsongsong** [comment]
@zuggs 现在不要用seajs，已经停更了，可以采用最新的方案。

seajs.use 是通过script标签的一些事件如```onload```来判断脚本加载是否完成的。
