### ISSUE TITLE
在htc某些机型下seajs加载css未触发onload回调

### ISSUE THREAD

**Issue by lynsun** [seajs/seajs#1073]
hi，玉伯，我在开发一个webapp时遇到一个问题，初步找到重现的方法是在js模块里require一个css，而css加载完成的回调未执行，导致依赖这个css的js的onload也未执行，我的测试机型是HTC-T328d，浏览器为手机自带的，userAgent为：
Mozilla/5.0(Linux;U;Android4.0.3;zh-cn;HTC-T328d/1.67.1401.3) AndroidWebKit/534.30(KHTML,Like Gecko) Version/4.0 Mobile Safari/534.30

深入到seajs源码中继续定位，发现这种机型有两个问题：
1  supportOnload = ‘onload’ in node返回true，但是通过创建link标签加载css却无法触发onload
2  ua中没有AppleWebkit，而是AndroidWebkit，导致seajs判断是否为老版本的webkit时错误
var isOldWebKit = +navigator.userAgent
    .replace(/._AppleWebKit\/(\d+).._/, "$1") < 536

之后导致seajs在addOnload方法中错误的进入了supportonload的分支
if (isCSS && (isOldWebKit || !supportOnload)) {
    setTimeout(function() {
      pollCss(node, callback)
    }, 1) // Begin after node insertion
    return
}

而在这款手机上安装的UC浏览器里其ua为AppleWebkit/530+ ,这个也导致seajs判断isOldWebKit时错误

修改判断isOldWebKit的正则为/._(?:AppleWebKit|AndroidWebKit)\/(\d+)._/后正常（其实是把AndroidWebkit低于536的也视为旧版本的webkit，同时去掉了版本号后一定带小数点的限制），但是不知道这样改会不会造成其他问题

**Comment by lincheng0803** [comment]
请问下，为什么判断版本号低于536的为旧版的webkit呢？有啥资料吗？ 现在问题是这样的，我的魅族，userAgent为 "Mozilla/5.0 (Linux; U; Android 4.4.2; zh-cn; MX4 Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Mobile Safari/537.36" ，它被判断为新版webkit，且 supportOnload = ‘onload’ in node返回true，但是通过创建link标签加载css却无法触发onload，所以导致后续的代码无法被回调执行。把版本改为低于538，可以正常运行，就是不知道会不会引起其他问题？谢谢
