### ISSUE TITLE
2.3规划想法

### ISSUE THREAD

**Issue by army8735** [seajs/seajs#1129]
重开一个。
1. 去掉css支持，原有的css功能做出插件形式。css平常用的场景较少，所以可以提取出来有选择的使用。（提取为一个插件，可以选择默认没有css功能或者添加插件有css功能）
2. preload移除，如果有需要也可以考虑做成插件形式。（直接移除）
3. 去掉根据 sea.js 路径自动猜测 base 路径的功能。交给用户自己配置。（移除）
4. 去掉对老旧版本 Safari 和 Firefox 中，加载 css 的支持。（和1放置到插件中）
   如果做插件的话，这条就放到插件里面去。国产手机还是需要考虑的。
5. 开发时只支持 Chrome / Firefox 等现代浏览器，不支持 IE6-8. 需要在 Old IE 下运行的话，需要先构建，生成 id 和 deps 后才能在 IE 下正常运行。
   感觉无论是老浏览器还是依赖onload还是不要去掉为好。第三方环境无法预测，一旦去掉后引发问题估计一大堆，门槛太高。要做的话尽量放后，考虑周全。（保留此功能）
6. CommonJS规范书写，和NodeJS保持一致，构建后或调试时分析包裹define。
   这个是非常好的新特性，如论新人老人对外层包裹的define都会产生厌倦。不写的好处很多，坏处是需要首先理解模块机制。对构建工具有要求。另外运行时得加一层处理，要么是本地切host启服务器进行预处理，要么是一个代理服务器预处理，要么是fiddle代理预处理，要么是watch源码修改时构建。这样的话又会增加一道门槛。如果这层做得不够智能化傻瓜化，估计又会一堆issue来袭。（spm中支持，老的define兼容）

**Comment by dotnil** [comment]
6 没办法在浏览器端支持吧？除非把模块代码加载方式换成 xhr，或者同时维护 require、exports、以及 module 全局变量，怎么看改动都很大。

define 自动包装这种事情交给 spm 就够了，不喜欢 spm 还可以考虑我的 oceanify 哈哈哈哈
