### ISSUE TITLE
只说两点

### ISSUE THREAD

**Issue by hotoo** [seajs/seajs#1200]
1. docs/ 下的什么时候放真正的文档？
2. 现在 index.html 和 docs/ 都是 seajs.org 站点相关内容，这个建议放在独立的仓库。
3. me.alipay.com 下线了，捐赠地址修改下。

**Comment by kongjiea** [comment]
把里面的 base配置，paths配置，还有关于config配置里都有哪些参数，随着版本的更新貌似都有些变化，来个最新的教程吧，api就写了7个api ，什么config里的配置都没讲

**Comment by afc163** [comment]
.... https://github.com/seajs/seajs/issues/262 缘木求鱼么，下面不是有配置的文档。
