### ISSUE TITLE
GitHub 发布提问编辑器（Markdown ） 学习笔记

### ISSUE THREAD

**Issue by yanyinxi** [seajs/seajs#1214]
## GitHub 发布提问编辑器（Markdown ） 学习笔记

代码块  

```html

<html>

</html>
```

```
http://www.baidu.com/
```
===========
<br>
>
>`自动连接`
>><http://www.baidu.com/>
>
========
<br>

黑体
**中国**
<br>
 
#   这是h1
##  这是h2
*******************
<br>

<p>
>这里使用了p.

*****************
<br>

列表 
`无序`
*   列表1
*   列表2
*   列表3

`有序`
1.   列表1
2.   列表2
3.   列表3

======
<br>

分隔符

* * *

***

*****

- - -

---------------------------------------

各种图案：

```
:+1:
:-1:
:airplane:
:art:
:bear:
:beer:
:bike:
:bomb:
:book:
:bulb:
:bus:
:cake:
:calling:
:clap:
:computer:
:cool:
:cop:
:email:
:feet:
:fire:
:fish:
:fist:
:gift:
:hammer:
:heart:
:iphone:
:key:
:leaves:
:lipstick:
:lock:
:mag:
:mega:
:memo:
:moneybag:
:new:
:octocat:
:ok:
:pencil:
:punch:
:runner:
:scissors:
:ski:
:smoking:
:sparkles:
:star:
:sunny:
:taxi:
:thumbsdown:
:thumbsup:
:tm:
:tophat:
:train:
:v:
:v2:
:vs:
:warning:
:wheelchair:
:zap:
:zzz:

```
对应效果
:+1:
:-1:
:airplane:
:art:
:bear:
:beer:
:bike:
:bomb:
:book:
:bulb:
:bus:
:cake:
:calling:
:clap:
:computer:
:cool:
:cop:
:email:
:feet:
:fire:
:fish:
:fist:
:gift:
:hammer:
:heart:
:iphone:
:key:
:leaves:
:lipstick:
:lock:
:mag:
:mega:
:memo:
:moneybag:
:new:
:octocat:
:ok:
:pencil:
:punch:
:runner:
:scissors:
:ski:
:smoking:
:sparkles:
:star:
:sunny:
:taxi:
:thumbsdown:
:thumbsup:
:tm:
:tophat:
:train:
:v:
:v2:
:vs:
:warning:
:wheelchair:
:zap:
:zzz:

#271

**Comment by kinneylee** [comment]
:1st_place_medal:
