### ISSUE TITLE
发布 Sea.js 2.3.0

### ISSUE THREAD

**Issue by army8735** [seajs/seajs#1228]
对当前页面的模块和模块关系感到混乱？模块依赖图插件轻松一点让你一目了然！

![preview](http://raw.github.com/seajs/seamap/master/preview.png)

只需在chrome上安装一个插件，就可以绘制出有向图，模块根路径、列表、名称、依赖关系尽收眼底。

相对于上个版本，Sea.js的体积又有进一步缩减，这一切归功于将css功能部分提取出作为一个插件存在。
- Sea.js 2.2
  
  > sea-debug.js  20,671 bytes
  > sea.js             6,769 bytes
  > gzip                3.0 KB
  > LOC               947
- Sea.js 2.3
  
  > sea-debug.js  18,177 bytes
  > sea.js             6,064 bytes
  > gzip                2.8 KB
  > LOC               846

测试用例增加到了`505`个！这一切都保障了Sea.js拥有十分强大的健壮性。
### 下载更新

推荐使用 [spm](http://spmjs.io)

```
spm install seajs
npm install seajs
```
### BUG 修复
- IE9下本地url document.URL与之前版本使用的location.href输出不一致导致模块id不能正确resolve #1154 
- Android中的webview当location.href为空时报错 #1225 
- realpath method in util-path.js：https://github.com/seajs/seajs/pull/1193
### 移除特性
- 去掉css支持，推荐link标签同步引入。如果实在要用，可以用seajs-css插件来完成。
- preload移除，推荐script标签同步引入。如果实在要用，可以用seajs-preload插件来完成。
- 去掉根据 sea.js 路径自动猜测 base 路径的功能。交给用户自己配置。
- CommonJS规范书写，这其实是spm3的功能：https://github.com/spmjs/spm/issues/819

> http://spmjs.io
### 改进增强
- seajs-css插件：https://github.com/seajs/seajs-css
- seajs-preload插件：https://github.com/seajs/seajs-preload
- seajs-circular插件，支持循环依赖：https://github.com/seajs/seajs-circular
- seamap插件，模块依赖图，绘制出当前页面上的模块和依赖关系图：https://github.com/seajs/seamap

> 插件目前分为2种：1是seajs插件，以seajs-xxx形式命名；2是开发者工具，以seaxxx命名。
### 其它调整
- 模块保存时增加了save事件
- 细微的性能改进
- CommonJS/AMD/CMD/Other脚本之间的互相转换：https://github.com/army8735/ranma
- pass-entry分支中尝试启用新算法，在体积不变的情况原生支持循环依赖。由于取消了回溯，初始化性能也提升了一倍
- 构建工具seatools更新部分bug：https://github.com/seajs/seatools
- 增加了英文文档：http://seajs.org/docs/en.html
- 同步发布spm3：https://github.com/spmjs/spm/issues/819

有任何问题，欢迎反馈。

**Comment by jxbb** [comment]
一直用1.3.1版本，升级到2.3.0后 grunt压缩合并的js文件突然不能用了

**Comment by huixisheng** [comment]
怎么后面release的版本还是  2.2.* 的？

**Comment by xgqfrms** [comment]
Sea.js 3.0.0  稳定吗？

**Comment by destinycalm** [comment]
怎么下载
