### ISSUE TITLE
seajs data vars的用法

### ISSUE THREAD

**Issue by fwon** [seajs/seajs#1277]
我们知道vars是用在require('xxx/{vars}');中的。用于动态配置url。
但是是否有场景可以为seajs注入全局变量，而不想直接暴露给外部。由于use中的模块是预加载后再执行回调的，所以app.js中想要用到变量globalName, 则需要在它的前面定义该变量。如：

```
seajs.config({
 vars: {
  globalName: 'hehe'
 }
});
seajs.use([app], function(App){
  //do something
});
```

在app.js中使用全局变量:

```
define(function (require, exports, module) {
 console.log(seajs.data.vars.globalName);
});
```

这种做法虽然可行，但是不是合理的？或者有其他解决方案？

**Comment by andyforever** [comment]
Sea.js推荐如何使用全局变量？

**Comment by afc163** [comment]
Sea.js 推荐尽可能不使用全局变量。

如果一定要使用，推荐同步加载全局变量的定义脚本。

**Comment by andyforever** [comment]
@afc163 了解，谢谢！
