### ISSUE TITLE
建议在官方首页放置sea.js 每个版本变更说明

### ISSUE THREAD

**Issue by beautyOfProgram** [seajs/seajs#1285]
#建议
1.因为 sea.js  每次版本变大很大，经常导致前一个版本能用的功能，下一个不能用了，或者不是这样使用的，所以 建议在 首页  放置每个版本更新说明，  来避免 个人搜索到网页上代码 ，下个最新版本 却不能运行的问题，提现使用人注意版本变更点

2.请  标识 有任何问题 请到  issue 里搜索  重要提醒

**Comment by dotnil** [comment]
还是应该维护一份 History.md 的 :monkey:
