### ISSUE TITLE
需要修改 script 标签的属性

### ISSUE THREAD

**Issue by hotoo** [seajs/seajs#1312]
JavaScript 异常监控时，默认对于跨站脚本不暴露有效的异常信息（即著名的 `Script error.`），为了解决这个问题，需要从客户端和服务端相互配合完成。
- 服务端：设置 `Access-Control-Allow-Origin` HTTP 头
- 客户端：设置 `script[crossorigin="anonymous"]` 属性。

现在服务端已经设置好，静态内联脚本也可以逐渐修改完成。
但是通过 seajs 动态加载的模块，目前无法设置。
## 建议
- 考虑提供事件机制，让用户可以扩展。（目前 request 事件已经被 module.js 占用，util-request.js 应该使用什么事件？）
- 动态配置，类似 charset 属性。
- 写死，类似 async 属性。

**Comment by VaJoy** [comment]
为何3.0.0版本又去掉了该项支持呢？

**Comment by army8735** [comment]
https://github.com/seajs/seajs/blob/master/src/util-request.js#L33-L35

你没看错吧，哪里去掉了？

**Comment by VaJoy** [comment]
3.0.0版本是去掉了，3.0.1+又加上了，虚惊一场哈。。。。现在项目用的3.0.0的

**Comment by army8735** [comment]
不是去掉了，3.0的时候还没加，然后出2.2.3和3.0.1的时候加上去的
