### ISSUE TITLE
最近在看新的spm3 如何打包seajs,感觉还是不会弄 高手能帮我看看package.json 要怎么写吗

### ISSUE THREAD

**Issue by w19871029** [seajs/seajs#1328]
项目结构是：
![项目结构](http://ww2.sinaimg.cn/mw690/8833c257gw1eknjs1d6s5j20cg0b9wf0.jpg)

**Comment by QzhouZ** [comment]
@w19871029 请问线下只有加define才能调试的问题，有找到解决方法吗？

**Comment by afc163** [comment]
@QzhouZ https://github.com/spmjs/spm/wiki/%E8%B0%83%E8%AF%95-CommonJS-%E6%BA%90%E7%A0%81
