### ISSUE TITLE
构建和直接use的疑问

### ISSUE THREAD

**Issue by anna-js** [seajs/seajs#1349]
![2014-10-29 11 02 12](https://cloud.githubusercontent.com/assets/9441404/4820579/edf3f5d4-5f18-11e4-9c66-25f905f21125.png)

直接use会在页面产生很多请求，而构建会将JS合并减少请求。

但是直接use后浏览器会缓存这些模块，而构建是将模块都复制一份合并成一个文件。
那么在加载速度方面考虑是否直接use比构建更好。

**Comment by zuibunan** [comment]
有了combo，为何还要构建呢，是为了进一步优化请求？
