### ISSUE TITLE
path中出现 // 问题

### ISSUE THREAD

**Issue by lichenhao** [seajs/seajs#1394]
RT
在"2.3.0"版本中为何会出现 http://g.tbcdn.cn/xxx/xxx//xxx/xx.js 这明显是在合并 paths和alias的时候出现问题。但是却并没处理干净。

**Comment by ClassJS** [comment]
@lichenhao 
建议在配置paths的时候使用%%，提高可识别度；@army8735 可以考虑把这种方式加入官方手册

    var ROOT_PATH = '/wuhao/',
        LIB_PATH = ROOT_PATH + 'lib/';
    seajs.config({
        base: ROOT_PATH,
        debug: true,
        alias: {
            'seajs-css' : LIB_PATH +'seajs-css-master/dist/seajs-css-debug.js',
            "jquery": LIB_PATH + "jquery/jquery-1.7.1.js",
            "qunit": LIB_PATH + "qunit/qunit-1.18.0.js",
            "jquery.mobile": LIB_PATH + "jquery.mobile-1.4.5/jquery.mobile-1.4.5.js",
            "handlebars": LIB_PATH + "handlebars/handlebars-v3.0.3.js",
            "jquery.slides": LIB_PATH + "Slides-SlidesJS-3/source/jquery.slides.js"
        },
        paths: {
            '%root%': ROOT_PATH,
            '%lib%': LIB_PATH,
            '%jquery.mobile%': LIB_PATH + 'jquery.mobile-1.4.5',
            '%.%': '.'
        }
    });

**Comment by ClassJS** [comment]
@lichenhao 
建议在配置paths的时候使用%%，提高可识别度；@army8735 可以考虑把这种方式加入官方手册

var ROOT_PATH = '/wuhao/',
    LIB_PATH = ROOT_PATH + 'lib/';
seajs.config({
    base: ROOT_PATH,
    debug: true,
    alias: {
        'seajs-css' : LIB_PATH +'seajs-css-master/dist/seajs-css-debug.js',
        "jquery": LIB_PATH + "jquery/jquery-1.7.1.js",
        "handlebars": LIB_PATH + "handlebars/handlebars-v3.0.3.js"
    },
    paths: {
        '%root%': ROOT_PATH,
        '%lib%': LIB_PATH,
        '%.%': '.'
    }
});

**Comment by ClassJS** [comment]
@lichenhao 
建议在配置paths的时候使用%%，提高可识别度；@army8735 可以考虑把这种方式加入官方手册


    var ROOT_PATH = '/wuhao/',
        LIB_PATH = ROOT_PATH + 'lib/';
    seajs.config({
        base: ROOT_PATH,
        debug: true,
        alias: {
            'seajs-css': LIB_PATH + 'seajs-css-master/dist/seajs-css-debug.js',
            'jquery': LIB_PATH + 'jquery/jquery-1.7.1.js',
            'handlebars': LIB_PATH + 'handlebars/handlebars-v3.0.3.js'
        },
        paths: {
            '%root%': ROOT_PATH,
            '%lib%': LIB_PATH,
            '%.%': '.'
        }
    });

**Comment by iulo** [comment]
估计是楼主path配置了类似 `test: mytest/dec/`   require的时候用 `test/whatever`
