### ISSUE TITLE
seajs里面不能直接用underscore吗

### ISSUE THREAD

**Issue by younth** [seajs/seajs#1408]
var data = {
        name : 'test',
        age: 23
    };
    var tpl="<div><%=data.name %></div>";
    var html = _.template(tpl, data);
    $("body").html(html);
 
页面中引入了jquery,underscore ，但是上面这段代码在main.js里面执行报错：data is not defined..

把这段代码放在页面的script标签里面执行就可以，为什么啊？是要怎么设置吗

**Comment by lichunqiang** [comment]
什么原因
