### ISSUE TITLE
如何让 kissy 和 seajs 共存

### ISSUE THREAD

**Issue by nimojs** [seajs/seajs#1410]
需要用kissy editor 但两者都同时占用了 `define`

**seajs:**
```javascript
define
function (a,c,d){var e=arguments.length;1===e?(d=a,a=b):2===e&&(d=c,x(a)?(c=a,a=b):c=b),!x(c)&&y(d)&&(c=r(""+d));var f={id:a,uri:s.resolve(a),deps:c,factory:d};if(!f.uri&&K.attachEvent){var g=q();g&&(f.uri=g.src)}B("define",f),f.uri?s.save(f.uri,f):W=f}
```
**kissy:**
```javascript
define
function (e,t,r){l.add(e,t,r,arguments.length)}
```

**Comment by afc163** [comment]
kissy 自有 loader ，不建议一起使用。

**Comment by nimojs** [comment]
抱歉之前没仔细看kissy的文档，找到方法了。
`modulex.noConflict`  
引入 modulex 后（或引入KISSY种子文件seed.js），默认define/require 关键词是modulex使用，若需要让出它们的控制权给例如 requirejs , seajs 等类库使用，可调用 modulex.noConflict() 方法。

主要是要用到kissy editor 所以就两个一起混用了。

**Comment by nimojs** [comment]
补充联动issuse：[seajs与其他loader类库并存方法](https://github.com/seajs/seajs/issues/1379#issuecomment-68820817)
