### ISSUE TITLE
为什么我node运行文件会用Dw打开文件呢

### ISSUE THREAD

**Issue by Mebiiu** [seajs/seajs#1411]
为什么我node运行文件会用Dw打开文件呢,我该怎么解决呢

**Comment by army8735** [comment]
这个问题请自行解决吧，您提的我也帮不了您……

**Comment by popomore** [comment]
请自行 google

**Comment by followgiant** [comment]
你是怎么运行的
关注农民，由心开始
在 wuzhiping <notifications@github.com>，2015年1月7日 下午9:29写道：为什么我node运行文件会用Dw打开文件呢,我该怎么解决呢
