### ISSUE TITLE
在spm doc watch 模式下，通过ajax加载json返回数据中都自动拼上了define(....)导致无法正常解析json数据的问题

### ISSUE THREAD

**Issue by GENGSHUANGs** [seajs/seajs#1413]
如题，如何破？，我使用的是spm3.x
目前我的解决方法是在把xxx.json 修改成xxx.jsonx处理，但是应该还有正经的解决途径才对
建议：是否可以对examples/目录下的内容不进行wrap处理

**Comment by afc163** [comment]
为啥提到 seajs 这里来了。。。

**Comment by afc163** [comment]
建议到 https://github.com/spmjs/serve-spm 去提，目测是一个问题，需要加上 XHR 的判断。

**Comment by GENGSHUANGs** [comment]
谢谢
