### ISSUE TITLE
seajs-combo comboExcludes 被覆盖的问题

### ISSUE THREAD

**Issue by popomore** [seajs/seajs#1414]
当重复定义 comboExcludes 的时候，后一次会覆盖前一次

```
seajs.config({
  comboExcludes: /.*/
});
seajs.config({
  comboExcludes: /jquery\.js/
});
```

当是正则的时候能否做个合并？感觉这是一个或的关系

**Comment by army8735** [comment]
之前存在合并的是类似alias这样的map配置：
```js
seajs.config({
  alias: { ...prev }
});
```
这个东西可以出现任意次，后续的仍然是键值形式，不存在添加，存在覆盖。
使用此config的方式，是从map中取键值，不同键之间无干扰。

combo插件的话，这里是个排除选项，哪些不应combo。
看源码实现，只有唯一的设置，不像map配置，可以function还可以array。

如果要支持的话，也应该是兼容支持了，即目前seajs.config的逻辑，object覆盖，array则concat。

**Comment by popomore** [comment]
现在这个参数好像是 function 或正则吧，seajs 能否把原始设置的值都存在数组里，插件自己去控制。

按理说应该插件控制的，但是 config 的 api 是 seajs 的。

```
seajs.data.config.comboExcludes = [/.*/, 'jquery\.js']
```

这样最起码可以保证 seajs 的逻辑是一致的

**Comment by army8735** [comment]
https://github.com/seajs/seajs-combo/blob/master/src/seajs-combo.js#L30

https://github.com/seajs/seajs-combo/blob/master/src/seajs-combo.js#L303-L306

插件写死了一个正则，来源是seajs.data

**Comment by popomore** [comment]
是啊，因为插件无法获取多次设置，因为 config 已经是覆盖的了，所以能不能在设置的时候通过一个字段存所有设置的值，则有插件可以使用处理好的也可以用用户真实设置的。

**Comment by army8735** [comment]
你是说每次设置的都保存下来，存为一个数组？

seajs.config的api支持的啊，直接设置数组的话，就合并了。插件那边缺少对数组的处理。

https://github.com/seajs/seajs/blob/master/src/config.js#L45-L46

**Comment by popomore** [comment]
数组的话就是报错多个数组不是合并，比如 `[arr1, arr2]`

我的想法是把所有用户设置的数据都给存下来，现在问题是插件无法取到用户之前设置的值。

**Comment by army8735** [comment]
这样做的话得改seajs的api了，config接口添加保留历史设置。总感觉别扭，小题大做的感觉。

想取之前设置的话，不光插件，业务代码都能做到：只要判断seajs.data.xxx是否存在即可。
```js
if(seajs.data.comboExcludes){
var history = seajs.data.comboExcludes;
}
```
引用保存下来。然后这个comboExcludes设置还支持function()类型回调，后面逻辑就随便了。

这个保存历史设置的逻辑放在最底层？插件？还是业务逻辑？考虑在这。

**Comment by popomore** [comment]
不改啊，只是多存一份数据，代码也没几行，缺点就是稍微吃点内存。

都是通过 config 来设置，插件要怎么处理？给个实现代码看看？

**Comment by army8735** [comment]
插件不能处理，我想错了。

内存那点也没啥。只是对于用途有点犹豫。

加在seajs.data.history上，名做key，每次配置形成一个list做value？

**Comment by army8735** [comment]
没异议了吗？么有就加了？

**Comment by popomore** [comment]
我没异议，记得发 PR

**Comment by army8735** [comment]
保存历史记录里得clone object，否则还是一样的引用

**Comment by popomore** [comment]
就保留原始引用吧，seajs.data 里应该不是引用吧

**Comment by lifesinger** [comment]
用在什么场景下呀？

理想情况下，一个页面里，只有一处 config，多处 config 的用法得尽量避免掉。

**Comment by lifesinger** [comment]
我建议还是别加，除非使用场景很常见，很难避免。

**Comment by popomore** [comment]
现在就有场景多处使用 config，而且是两处全局的。所以既然有 API 就很难猜测如何使用
