### ISSUE TITLE
不用spmjs也能用seajs吗？

### ISSUE THREAD

**Issue by haoniukun** [seajs/seajs#1415]
我的require jquery总是返回null，看了很多标识的文档，我也没太明白标识到底指的是什么。我在alias里面指定的jquery路径是/assets/libs/jquery/jquery/1.11.2/jquery.js，在require的时候是require("jquery")，我看到jquery.js文件被浏览器正常下载了，但是require的返回值总是null。有什么办法不用spmjs也能用seajs吗？我也试了require("/assets/libs/jquery/jquery/1.11.2/jquery.js")，也还是不行。

**Comment by afc163** [comment]
#930

**Comment by popomore** [comment]
@afc163 你太快了

**Comment by haoniukun** [comment]
就是看了930，还是没太懂，一定要用相对路径，不能用/assets之类的绝对路径吗？

**Comment by popomore** [comment]
可以，就是路径和 id 一致就可以

**Comment by haoniukun** [comment]
这个id到底是什么？alias后面的路径吗？还是require的第一个参数？我用的2.3.0，把alias的路径和require的第一个参数对应了，还是返回null。

**Comment by popomore** [comment]
多看看 seajs 的文档吧，文档里面还有很多链接的，除了 #930 可以看看 #426 #242

**Comment by haoniukun** [comment]
那类似jquery这类不是我自己写的library，我怎么用define设定id呢？需要自己手动改jquery的代码嘛？我试着在require里面用alias里对应的jquery，resolve的uri结果是对的，但返回值一直是null。

On Tue, Jan 13, 2015 at 3:11 AM, Haoliang Gao <notifications@github.com>
wrote:

> 多看看 seajs 的文档吧，文档里面还有很多链接的，除了 #930
> <https://github.com/seajs/seajs/issues/930> 可以看看 #426
> <https://github.com/seajs/seajs/issues/426> #242
> <https://github.com/seajs/seajs/issues/242>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/seajs/seajs/issues/1415#issuecomment-69729202>.
>



-- 
         牛坤
MSN:haoniukun@hotmail.com

**Comment by haoniukun** [comment]
我还试过在define的时候把jquery加入到dependency列表中，也不管用，不知道是不是这个路径和id不一致引起的。文档我看了好多遍，但都是自己define module，jquery这类不是我自己写的代码，我看大部分sample都是直接用的，但到我这里直接用就不行了。我的代码比hello.js都简单。

**Comment by popomore** [comment]
http://spmjs.io/package/jquery

**Comment by popomore** [comment]
凡是自己写的都比较直接用麻烦，写代码都是先用再理解，你先把 hello world 什么跑通再慢慢改成你自己想要的就好了。这里还是不多说了，实在要研究就多翻翻帖子，也有很多人总结出自己使用的经验。

推荐先用 spm 跑，需要自己定制才去写工具，事半功倍。

**Comment by haoniukun** [comment]
就是说如果我想用jquery的话，一定要先用spmjs打包？

On Tue, Jan 13, 2015 at 8:41 AM, Haoliang Gao <notifications@github.com>
wrote:

> http://spmjs.io/package/jquery
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/seajs/seajs/issues/1415#issuecomment-69774872>.
>



-- 
         牛坤
MSN:haoniukun@hotmail.com

**Comment by popomore** [comment]
你用了 spm 就可以先不知道为什么了，不然你得研究完原理才开始用。

**Comment by haoniukun** [comment]
谢谢你的耐心，赶项目，我还是先直接用再回来研究怎么用spm和seajs吧。

On Tue, Jan 13, 2015 at 9:16 AM, Haoliang Gao <notifications@github.com>
wrote:

> 你用了 spm 就可以先不知道为什么了，不然你得研究完原理才开始用。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/seajs/seajs/issues/1415#issuecomment-69781286>.
>



-- 
         牛坤
MSN:haoniukun@hotmail.com
