### ISSUE TITLE
seajs require  tpl  跨域问题 

### ISSUE THREAD

**Issue by cxh80301983** [seajs/seajs#1419]
如题，求高手解决方式

**Comment by popomore** [comment]
编译成 js

**Comment by chengqinghuanyu** [comment]
全路径

**Comment by chenmnkken** [comment]
首先保证开发环境的配置的顶级域名是相同的，然后使用document.domain来设置相同的顶级域名，在静态资源的域中放置一个proxy.html（用于设置静态资源域的document.domain），使用iframe的形式将proxy.html加载到页面中，然后改写seajs-text，其xhr对象一律使用iframe.contentWindow来创建，比较烦碎，但还算是解决了跨域问题。
