### ISSUE TITLE
seajs能不能兼容AMD模块

### ISSUE THREAD

**Issue by valaxy** [seajs/seajs#1420]
jquery/underscore这些模块的封装法都不判断`require.cmd`属性的，
能不能多开发一个配置项使得seajs的模块也有`require.amd`属性，然后就可以直接加载amd模块了？

**Comment by army8735** [comment]
是define.amd

可以书写时采用commonjs规范，build时自己按不同合并。还可以使用ranma

**Comment by valaxy** [comment]
确实是 `define.amd`，我搞错了
我是希望 seajs 可以直接加载别人的amd模块，不用去改别人的代码，也不用通过build来保证模块兼容
开发环境下build总是略麻烦

**Comment by lifesinger** [comment]
忘记 CMD 和 AMD 吧，都不长久

大家拥抱 CommonJS 的写法，让各种 XMD 逐步淡去。
