### ISSUE TITLE
大家都用什么构建工具

### ISSUE THREAD

**Issue by riskers** [seajs/seajs#1421]
使用seajs有一段时间了，一开始用的Grunt，但是项目稍微大一点以后，写配置文件也是一件很麻烦的事情。就转到了Gulp，感觉[gulp-seajs](https://github.com/teamrun/gulp-seajs)这个插件还是不错的。
拿一个实际的例子来说：
```
//gulpfile.js :
gulp.task('sea',function(){
	gulp.src('script/main.js')
		.pipe( seajs('main.min') )
		.pipe( rename('main.min.js') )
                .pipe( uglify() )
		.pipe( gulp.dest('dist') )
});
```
目录结构是这样的：
```
|-index.html
|-script
    |-a.js
    |-b.js
    |-main.js
    |-feature
        |-c.js
```
```
//a.js:
define(function(require,exports){	
	exports.aaa = function(){
		console.log('a.js')
	}
})
//b.js:
define(function(require,exports){
	var a = 'aaaa' ;
	var b = 'bbb' ;
	exports.bbb = function(){
		console.log(a)
		console.log(b)
	}
})
//main.js
define(function(require,exports){
	require('a').aaa() ;
	require('b').bbb() ;
	require('./feature/c').ccc() ;
})

//c.js:
define(function(require,exports){
	exports.ccc = function(){
		alert('cccc')
	}
})

//index.html:
seajs.config({
	base : './' ,
	alias : {
		a : 'script/a' ,
		b : 'script/b' ,
		c : 'script/feature/c'
	}
}) ;
seajs.use('./dist/main') ;
```

这样就行了，但是这个插件不支持alias，这个最基本的config竟然没有支持，也就是`main.js`只要写成这样：
```
define(function(require,exports){
	require('a').aaa() ;
	require('b').bbb() ;
	require('c').ccc() ;
})
```
这个插件就报错，很纠结的事情，不知道大家还有什么好用的工具呢？都来说说吧~~~

**Comment by lichunqiang** [comment]
spm

**Comment by sorrycc** [comment]
spm

**Comment by riskers** [comment]
感觉spm有点麻烦啊~~

**Comment by popomore** [comment]
麻烦说下哪里麻烦，我们可以改进

—
通过 Mailbox 发送

**Comment by riskers** [comment]
又是father，又是gulp-spm，而且还没有demo

**Comment by popomore** [comment]
http://spmjs.io/documentation

http://sorrycc.gitbooks.io/spm-handbook/

**Comment by sorrycc** [comment]
https://github.com/spmjs/examples

**Comment by riskers** [comment]
我是感觉gulp-spm这个插件很好，但是不明白为什么不支持alias。。。

**Comment by riskers** [comment]
好吧，我搞了一下Gulp，说说心得：
seajs的构建工具构建过程以后不能用的原因就是moduleID和URL不匹配！
比如：
```
seajs.use('script/main')
```
而main.js经过transport工具构建以后变成：
```
define('main',[],function(){
    ...
})
```
就算是这样，都是不能使用的，因为seajs.use的URL（script/main）和main模块的moduleID（main）不匹配！只能像本文一样使用map来映射：本来加载 script/main.js 而现在加载 script/dist/main.min.js
```
 ['script/main.js','script/dist/main.min.js']
```
这样就能保证URL和moduleID的一致了~
其他的就都不重要了，Grunt和Gulp都大同小异，不过用Gulp还是比Grunt爽的~~

**Comment by alvin2ye** [comment]
spm +1

**Comment by nuintun** [comment]
@riskers 自己写了个 [gulp-cmd](https://github.com/nuintun/grunt-cmd) ， 示例 [gulp-sample](https://github.com/nuintun/gulp-sample)
