### ISSUE TITLE
在原来的页面上追微信新接口jweixin-1.0.0.js提示jWeixin is not defined

### ISSUE THREAD

**Issue by chengqinghuanyu** [seajs/seajs#1422]
感觉是命名空间冲突了，使用sea.js后加载微信最新sdk接口实例化接口后报错：

!seajs.use(["dist/js/jweixin"],function(){
	/* * 注意：
   * 1. 所有的JS接口只能在公众号绑定的域名下调用，公众号开发者需要先登录微信公众平台进入“公众号设置”的“功能设置”里填写“JS接口安全域名”。
   * 2. 如果发现在 Android 不能分享自定义内容，请到官网下载最新的包覆盖安装，Android 自定义分享接口需升级至 6.0.2.58 版本及以上。
   * 3. 完整 JS-SDK 文档地址：http://mp.weixin.qq.com/wiki/7/aaa137b55fb2e0456bf8dd9148dd613f.html
   *
   * 如有问题请通过以下渠道反馈：
   * 邮箱地址：weixin-open@qq.com
   * 邮件主题：【微信JS-SDK反馈】具体问题
   * 邮件内容说明：用简明的语言描述问题所在，并交代清楚遇到该问题的场景，可附上截屏图片，微信团队会尽快处理你的反馈。*/
	jWeixin.config({
        debug: true,
		appId: '{$signPackage['appId']}',
		timestamp: '{$signPackage['timestamp']}', 
		nonceStr: '{$signPackage['nonceStr']}',
		signature: '{$signPackage['signature']}',
        jsApiList: [
        'checkJsApi',
        'onMenuShareTimeline',
        'onMenuShareAppMessage',
        'onMenuShareQQ',
        'onMenuShareWeibo',
        'hideMenuItems',
        'showMenuItems',
        'hideAllNonBaseMenuItem',
        'showAllNonBaseMenuItem',
        'translateVoice',
        'startRecord',
        'stopRecord',
        'onRecordEnd',
        'playVoice',
        'pauseVoice',
        'stopVoice',
        'uploadVoice',
        'downloadVoice',
        'chooseImage',
        'previewImage',
        'uploadImage',
        'downloadImage',
        'getNetworkType',
        'openLocation',
        'getLocation',
        'hideOptionMenu',
        'showOptionMenu',
        'closeWindow',
        'scanQRCode',
        'chooseWXPay',
        'openProductSpecificView',
        'addCard',
        'chooseCard',
        'openCard'
      ]
  });//console.log(app.init_modle()._scrollStop());
});
!seajs.use(["dist/js/demo"],function(){
	
})

报错：
Uncaught ReferenceError: jWeixin is not defined
demo.js?v=31:12 Uncaught ReferenceError: jWeixin is not defined
但是微信的接口是可以使用wx.config和wx.ready的或者 jWeixin.config或者 jWeixin.ready();路径都能访问到，可是就是报错如果把sea.js拿掉就不会报错：
文件加载的顺序也是sea.js在微信sdk的js的前面。微信sdk的接口在微信实例化前面。
怎样才能不报错呢。。。。

**Comment by yuhonlang** [comment]
我也碰到这样的问题，楼主解决了吗？求助

**Comment by xuhuan** [comment]
目前可以通过把微信接口sdk移到sea.js上面来解决。

**Comment by ddtramp** [comment]
你们去看看 jweixin-1.0.0.js 的源码， 即使是压过的 只看第一行就可以了； 如果 global variable 有 define && define.amd | define.cmd  只能通过 require 获取 wx； 如果没有， 则在window 上添加 wx 和 jWeixin 两个 属性名

**Comment by chomyeong** [comment]
@xuhuan Hi friend! May I ask you how to solve the question?
