### ISSUE TITLE
paths配置问题

### ISSUE THREAD

**Issue by jieyou** [seajs/seajs#1423]
各位作者大大好，我想给我的 [lazyload组件](https://github.com/jieyou/lazyload) 加入cmd的模块加载支持，但是按如下方式配置了seajs，出现了一些问题，先上代码
`````
<script src="http://cdn.bootcss.com/seajs/2.3.0/sea.js"></script>
<script>
  seajs.config({
    base:'./',
    paths: {
      jquery: 'http://webmap2.map.bdimg.com/yyfm/jQuery_1.x/1.10.2/js/jQuery_1.x.min'
    }
  })
</script>
<script>
  seajs.use(['jquery','../lazyload'],function($){
    $(".lazy").lazyload()
  })
</script>
`````

文件放置位置：
* 我的jquery位于 `http://webmap2.map.bdimg.com/yyfm/jQuery_1.x/1.10.2/js/jQuery_1.x.min.js`
* 我的layzload.js位于相对html的上一级目录，即`../lazyload.js`

但是seajs却往`../jquery.js`的位置去加载jquery了，而不是我想要的paths里的位置`http://webmap2.map.bdimg.com/yyfm/jQuery_1.x/1.10.2/js/jQuery_1.x.min.js`。也就是说配不配置paths没有生效，请问应该如何配置才能正确？

**Comment by afc163** [comment]
paths 和 alias 是不一样的。

**Comment by jieyou** [comment]
@afc163 谢谢偏右。用paths是因为以前用的都是requirejs。凭直觉就直接用了，以为这一条也是相同的。
