### ISSUE TITLE
Grunt、Gulp构建的心得

### ISSUE THREAD

**Issue by riskers** [seajs/seajs#1424]
这两天一直纠结在工具构建seajs上。
seajs的构建工具transport抽取模块id和依赖以后不能用的原因就是moduleID和URL不匹配！
比如：
```
seajs.use('script/main')
```
而main.js经过transport工具构建以后变成：
```
define('main',[],function(){
    ...
})
```
就算是这样，都是不能使用的，因为seajs.use的URL（script/main）和main模块的moduleID（main）不匹配！这一切都是因为transport抽取的moduleID只是自己本身的文件名，这和我们use的URL不一致就不能正常加载。
只能像本文一样使用map来映射：本来加载 script/main.js 而现在加载 script/dist/main.min.js
```
 ['script/main.js','script/dist/main.min.js']
```
这样就能保证URL和moduleID的一致了~感觉有点坑~
其他的就都不重要了，Grunt和Gulp都大同小异，不过用Gulp还是比Grunt爽的~~
------------
这是我的解决方法，不知道大家是怎么解决的？

**Comment by popomore** [comment]
spm 有一个 idleading 的配置

**Comment by chenmnkken** [comment]
同样碰到这种问题，也是一样的解决方式，用map

**Comment by riskers** [comment]
@chenmnkken 我纠结了好久好久才想到这样。
以前都是不用transport，自己写moduleID和依赖数组，然后concat。
后来项目大了，这样实在麻烦

**Comment by afc163** [comment]
同 idleading

**Comment by lynzz** [comment]
采用 grunt 打包机制，因文件非常多，每一次打包至少要30分钟，忍不了啊

**Comment by popomore** [comment]
30分钟 :anger:

**Comment by lynzz** [comment]
gruntfile 已写满非常可怕的配置了，求大伙大项目的打包机制经验

**Comment by chenmnkken** [comment]
30分钟，你还能忍，换gulp吧。

**Comment by riskers** [comment]
gulp，[非常简单](http://www.tuicool.com/articles/uMBZ7fB)
这是我的gulp.file:
```
var gulp = require('gulp') 
var concat = require('gulp-concat')
var uglify = require('gulp-uglify')
var transport = require('gulp-seajs-transport') 
var rename = require('gulp-rename')
 
//使用gulp-seajs-transport
gulp.task('sea',function(){
    return gulp.src(['./script/main.js','./script/a.js','./script/b.js','./script/func/c.js'])
        .pipe( transport() )
        .pipe( concat('main.min.js') )
        .pipe( uglify() )
        .pipe( gulp.dest('./script/dist') )
})
```

**Comment by XIAOGUIGUI** [comment]
var transport = require('gulp-seajs-transport') ;怎么给构建文件添加id前缀，grunt可以设置idleading ，gulp呢？

**Comment by popomore** [comment]
@XIAOGUIGUI 这个是非官方的，请移步 https://github.com/guilipan/gulp-seajs-transport

**Comment by elover** [comment]
官方的是那个，有没有一个可以运行起来的demo？

**Comment by differui** [comment]
@lynzz 是啊，超级慢。我还以为是我代码的原因呢。

我后来就只能是局部文件打包，改了那几个文件就重新 transport 哪几个。要不然每次修改都整体 transport 到了世界末日都完不成了。

**Comment by chenmnkken** [comment]
可以试试我的 gulp 插件，自动解析模块的所有依赖然后进行合并，同时也会解析 seajs.config 。
https://github.com/chenmnkken/gulp-seajs-combo
grunt 无论是配置还是性能都没办法和 gulp 拼。

**Comment by elover** [comment]
@chenmnkken 刀哥出品，必属精品，相对于其他的，这个最好了，代码也很简单，学习使用两不误

**Comment by nimojs** [comment]
我的做法是使用服务器 combo，开发人员不去管构建的事了。

https://github.com/nimojs/seajs-cmd
http://cmd.nimojs.com/examples/arale-dialog-combo.html

对打包要求很细致的时候，就直接抛弃seajs 用 spm3 开发。

**Comment by enng0227** [comment]
学习了
