### ISSUE TITLE
seajs和kissy的一个配置问题

### ISSUE THREAD

**Issue by Jnanke** [seajs/seajs#1425]
例如一个bForm插件，我在use的时候需要写mycmd/bForm/1.0.0/bForm，能不能像kissy一样只需要写成
mycmd/bForm/1.0.0/

seajs.use(['mycmd/bForm/1.0.0/bForm'], function() {})

改变之后：

seajs.use(['mycmd/bForm/1.0.0/'], function() {})

请问下有没有这样的一个配置项

**Comment by army8735** [comment]
据我所知没有。
