### ISSUE TITLE
用preload优先加载感觉有时会失效?

### ISSUE THREAD

**Issue by darkbluegood** [seajs/seajs#1426]
<script type="text/javascript" src="js/sea.js"></script>
	<script type="text/javascript">
		seajs.config({
			alias : {},
			preload : ['jquery','easing']
		});
		seajs.use('main');
	</script>
我是这样写的 ..优先加载jquery和easing
有时候打开页面会提示js/easing.js:1 Uncaught ReferenceError: jQuery is not defined
有时候又是正常的...什么问题啊?

**Comment by w567675** [comment]
config 在preload 之后么？

**Comment by darkbluegood** [comment]
@w567675 代码都贴出来了啊 ...你看看啊

**Comment by army8735** [comment]
jquery和easing是并行的……
