### ISSUE TITLE
如果两个页面用了一些不同的js效果.seajs是如何工作的?

### ISSUE THREAD

**Issue by darkbluegood** [seajs/seajs#1427]
假如一个首页(index),一个内页(page);
这两个页面都用了seajs.use('main');就是都引用了main.js
我在index页面里写了一个幻灯片效果.这个的代码都写在main.js
例子:
define("main",function(require,exports,module){
	require("focus");//幻灯片
});
define("focus",function(require,exports,module){
	//do things
});
但是page页面没有这个幻灯片效果.当打开page内的时候main.js被加载.
加载到require("focus")这里的时候 有什么影响的吗??或者说这样写符合seajs的逻辑标准吗?
因为打开page页的时候 ,既不会报错又没发生页面有什么问题.所以想问问.

**Comment by popomore** [comment]
这和 seajs 没关系，不论用不用 seajs 这都是你要解决的问题。

—
通过 Mailbox 发送

**Comment by darkbluegood** [comment]
@popomore 但是打开page页的时候 执行到require("focus");//幻灯片 这一句的时候 为什么不报错?

**Comment by army8735** [comment]
这要看你的幻灯片逻辑。可能幻灯片判断了是否要展示dom的id存在，不存在就不执行。像jquery取id，不存在的id也不会报错。
