### ISSUE TITLE
seajs2.3配置alias不生效

### ISSUE THREAD

**Issue by liuzdcq** [seajs/seajs#1428]
<script type="text/javascript">
    	seajs.config({
    		plugins: ['shim'],
    		base: '${js_home}',
			alias: {
				'jquery': {
					src: 'lib/jquery-1.9.1.min'
				},
			    'jquery.lazyload.min': {
			      	src: 'lib/jquery.lazyload.min',
			      	deps: ['jquery']
			    },
			    'underscore' : {
			    	src: 'lib/underscore'
			    }
			}
		});
		seajs.use('modules/main');
    </script>
main.js里引用jquery
define(function(require, exports, module) {
  	var $ = require('jquery');
});
报错找不到${js_home}/jquery.js
同样的配置用2.0.1版本加上plugin-shim是OK的，请问是升级版本后有什么改动吗？

**Comment by army8735** [comment]
https://github.com/seajs/seajs/issues/744

**Comment by liuzdcq** [comment]
原来如此！这些改动为毛不放在官方文档上，官方文档还是以前的用法
那如果不想用CMD去包装插件的话，就正常的用script引入也是OK的吧？

**Comment by army8735** [comment]
对的

**Comment by afc163** [comment]
很好奇哪个官方文档还是以前的用法。

**Comment by liuzdcq** [comment]
seajs.org上那个5分钟上手，确实没有用shim插件哈，不过貌似也没提到要用CMD包装jquery，只在后面的其他文档里有讲
