### ISSUE TITLE
当seajs与第三方的UI库（bootstrap、easyui等）结合时，应该怎么控制文件的加载顺序而不引起页面重绘？

### ISSUE THREAD

**Issue by andyforever** [seajs/seajs#1430]
举个例子：

项目中用到easyui，easyui需要依赖jquery，而jquery是等待seajs加载完才进行加载，导致的后果是DOM元素在UI库的js文件加载完成后改变。

这样的问题在使用seajs的时候有没有更好的解决方案？

**Comment by ccwq** [comment]
关注

**Comment by afc163** [comment]
看不懂。

**Comment by lichunqiang** [comment]
直接引用jquery和easyui

**Comment by andyforever** [comment]
目前可能只有楼上的解决方案了，第三方库直接js引用，业务逻辑代码再按照CMD规范用seajs加载吧
