### ISSUE TITLE
用grunt压缩代码之后，出现object is not a function

### ISSUE THREAD

**Issue by woshiwenzhijie** [seajs/seajs#1431]
![image](https://cloud.githubusercontent.com/assets/6478844/5871591/e6427c70-a31a-11e4-8729-a9e0764aba6c.png)
![image](https://cloud.githubusercontent.com/assets/6478844/5871601/0d730300-a31b-11e4-9a02-6a6d590f49c7.png)
控制台打出null

**Comment by afc163** [comment]
#930

**Comment by woshiwenzhijie** [comment]
看了930的问题 还是没有解决。。我的jquery不是具名模块，按理是可以正常加载吧

**Comment by afc163** [comment]
如果不是具名模块，的确不会碰到 #930 的问题。我觉得可能有两个原因：

1. 其实是具名模块楼主没注意到，看下 jquery.min.js 的文件长什么样。
2. 或者加载 jquery 时出现了 404 。

**Comment by afc163** [comment]
好吧，问题应该出在这里，对于匿名模块 require 参数不能压缩。

![](https://cloud.githubusercontent.com/assets/6478844/5871601/0d730300-a31b-11e4-9a02-6a6d590f49c7.png)

https://github.com/seajs/seajs/issues/259

**Comment by woshiwenzhijie** [comment]
1：可以确认不是具名模块
2：network中没有加载jquery的请求

ps：没有压缩的话是可以正常跑通的，压缩之后就出现这个问题了

**Comment by woshiwenzhijie** [comment]
thanks

**Comment by woshiwenzhijie** [comment]
再请教一下
我是用grunt的grunt-contrib-uglify进行压缩的，好像没有指定过滤某个字符串的方法，要人肉去改回来？

**Comment by woshiwenzhijie** [comment]
再请教一下
我是用grunt的grunt-contrib-uglify进行压缩的，好像没有指定过滤某个字符串的方法，要人肉去改回来？

**Comment by afc163** [comment]
https://github.com/gruntjs/grunt-contrib-uglify#reserved-identifiers
