### ISSUE TITLE
map 配置的一些问题，不确认是否是BUG。

### ISSUE THREAD

**Issue by feng-ming** [seajs/seajs#1432]
- 目前项目模块如下：
```shell
.
|-- a
|   `-- main.js
|-- b_a
|   `-- main.js
`-- main.js

```
map 配置如下：
```shell
map:{
    [a/main.js,     a/main_bv3342.js]
   [b_a/main.js,  b_a/main_5634.js]
   [main.js,        main_67894d.js]
}
```
 当`require('a/main.js')` 时，seajs会自动加载`a/main_67894d.js` (即main.js 的别名)，实际上希望加载`a/main_bv3342.js`。看了下源码，seajs 的 parseMap 是基于后缀匹配的方式，会出现这样的情况。

项目想基于内容的md5值自动加版本号，请问各位是否遇到这样的问题，是怎么处理的。

**Comment by army8735** [comment]
基于后缀匹配？
https://github.com/seajs/seajs/blob/master/src/util-path.js#L97-L99

不过我却发现个隐患：当map匹配成相同元素时，会被认为没有匹配自动跳过……

**Comment by feng-ming** [comment]
@army8735 

"基于后缀匹配" 这地方描述的不太清楚。
意思`uri.replace(rule[0], rule[1])`  直接做了替换，所以如果是 rule[0] 存在包含关系时，就会有问题。如我上面描述的问题。

**Comment by army8735** [comment]
map的设计即是如此。完全匹配的话可以用alias。
