### ISSUE TITLE
hashchange事件中调用require问题

### ISSUE THREAD

**Issue by flicker85** [seajs/seajs#1433]
file1:
define(function(require, exports) {
  var core = {
     run: function() {
         $(window).on('hashchange', function() {
                 require('xxxxx');//无法执行
                 require.async('xxxxx',function(){});//正常
         });
     }
  }
  exports.run = core.run;
});

file2:
var core = require('file1');
core.run();

大概就是这意思，hashchange事件里只能用require.async么？seajs-text插件也得用require.asyn获取html之类的文本么？

**Comment by army8735** [comment]
require那里肯定早于hashchange执行

**Comment by flicker85** [comment]
那我在hashchange里根据url加载相应的js模块，应该用什么方式呢？
我用require.async()加载，当我多次反复点击几个链接的时候，在seajs.cahe里会出现许多
status: 4
uri: "http://localhost:8080/js/*****_async_1"
status: 4
uri: "http://localhost:8080/js/****_async_2"
status: 4
uri: "http://localhost:8080/js/****_async_3"
这个怎么解决呢？

**Comment by army8735** [comment]
加载是一开始就加载好的，只能说你在分支里有条件的选择初始化或执行。

**Comment by flicker85** [comment]
额，那如果我想做一个单页Web应用，要在hashchange事件里通过url的变化，动态加载相应的html模板以及对应的js脚本，并且缓存起来，在hashchange事件里应该怎么用seajs动态加载呢？
app.js
define(function(){
$(window).on('hashchange', function() {
//注册hahschange事件，获取url，如何通过url动态加载html和js文件并缓存？
});
});

**Comment by army8735** [comment]
用async

**Comment by flicker85** [comment]
status: 4
uri: "http://localhost:8080/js/**_async_1"
status: 4
uri: "http://localhost:8080/js/_async_2"
status: 4
uri: "http://localhost:8080/js/***_async_3"

在hashchange中用require.async加载，url每变化一次，seajs.cahe里都会反复添加相应的内容，这个是正常现象？

**Comment by army8735** [comment]
可以自己在hashchange里判断做缓存
