### ISSUE TITLE
TypeError: n.ajax.request is not a function

### ISSUE THREAD

**Issue by ycl2014** [seajs/seajs#1434]
狐火浏览器，在保持状态下，才会出现的一个报错，如果不包吃，他就会一闪而过，但是也不影响功能的使用，不知道什么原因，也不知道是什么类型的错误，我是seajs初学者，麻烦各位大神指教一二，没有源代码，告知 可能导致这种情况发生的可能性饥渴，谢谢了

**Comment by army8735** [comment]
您的错别字我也是醉了……这问题我无法回答。

**Comment by lichunqiang** [comment]
:+1:

**Comment by chenny417** [comment]
醉了醉了

**Comment by kmvan** [comment]
lz是用百度分享的组件？
我最近也遇上这个问题了，垃圾百度分享组件js出错，导致我的其他模块无法正常运行
