### ISSUE TITLE
加载好模块之后，是否应该删除 script 标签？

### ISSUE THREAD

**Issue by hotoo** [seajs/seajs#1437]
seajs 在非调试模式下，加载好模块之后，会删除掉 script 标签。

## 带来的问题：导致 DOM 和实际加载的资源不匹配。

* 就像 seajs 需要 `id="seajsnode"` 来寻找 base 路径，有些模块也使用类似的方式来寻找模块根路径，但 seajs 的 script 不会被删除，而模块的会被删除。（题外话：这个问题是否可以考虑提供类似 node 的 __dirname 参数？）
* DOM 扫描监控时，无法对这些被删除的 script 进行扫描。

## 请问：这样做有什么实际的价值和意义？

很久之前问过 @lifesinger 说是减少 DOM 节点数。

* 但是这样的优化有必要么？
* 有没有数据证明这样提升了多少 DOM 性能？
* 我们是否真的需要这样的『优化』？

**Comment by army8735** [comment]
以我的感觉，删掉似乎是一直遗留下来的洁癖。

**Comment by afc163** [comment]
debug 模式会保留。

**Comment by army8735** [comment]
我认为唯一的优点性能方面，需要实际做测试来证明。

**Comment by lifesinger** [comment]
__dirname 要有源头呀，没看懂和删掉 script 又什么关系。

加载后删掉 script，是当时所有 loader 的一致做法，没求证，有兴趣的可以考古下。

更感兴趣冒顿做的 DOM 扫描监控，具体是解决什么问题？冒顿先科普下？

**Comment by hotoo** [comment]
我中转一个模块到 spm 时，发现它有一个默认的图片资源地址设置，是根据自身的脚本所在地址来进行设置的。

用 script 标签直接引入是没有问题的，但是用 seajs 引入进来因为找不到自己的标签，因此找不到图片了。

DOM 扫描我只是顺便增加的一个场景。

我仍然觉得没有必要删除 DOM，除非有足够的数据证明这样做的必要性。

**Comment by lifesinger** [comment]
图片资源地址这个，实现上不妥当，限定了是同步 script 才能正常获取。异步 script 时，通过 currentScript 等方式，未必能获取到正确的路径，本身就存在问题。

这样倒让我想起一个删除 script 的非常强的理由：用 loader 加载 script 时，script 脚本开发者本身就应该不知道 script 是怎么被加载的，这应该是一个黑盒，脚本里面的功能代码不应该依赖 loader 的实现方式。比如同域下， loader 有可能通过 XHR 来加载 script，在 DOM 中就不存在。

跟性能没关系。
