### ISSUE TITLE
谁能提供一个 seajs 换肤思路？

### ISSUE THREAD

**Issue by honger05** [seajs/seajs#1439]
我的css用seajs2.2加载的（seajs2.3+seajs-css插件，require('a.css')或seajs.use('a.css')加载不了，跟踪代码到seajs-css.js文件的时候 判断url是否是js或css时，url已经在seajs2.3里被加上了.js后缀即a.css.js）。2.3的思路是不是用seajs-style把css模块当js来加载可以和功能js合并。具体要怎样操作才能加载a.css?

**Comment by 178220709** [comment]
不仔细看文档啊,路径后面加个符号#就表示不再追加".js"了
