### ISSUE TITLE
如何加载underscore系列这种对同一对象进行扩展的js插件?

### ISSUE THREAD

**Issue by 178220709** [seajs/seajs#1441]
比如有underscore和underscore.string 
这两个本身没有什么依赖关系,都是对_进行扩展.
我在seajs中如何加载这两者呢?
``` JavaScript
  var arr = [1,2,3,4,5];
    var _ = require("libs/underscore/underscore.string");
    var str1 = _.ltrim("~test~",'~');
     _ = require("libs/underscore/underscore");
     var arr2 = _.filter(arr, function(i) {
         return i % 2 == 0;
     });
     _ = require("libs/underscore/underscore.string");
     var str2 = _.rtrim("~test~", '~');

```
现在有两个思路,第一修改underscore.string,让它依赖underscore,然后直接把underscore声明的_扔给它继续扩展,这样就可能会加载我不用的js模块,二是用其他^&*%之类的去接,但这样肯定更不可取.
以前的shim倒是可以,但现在又不推荐了.

**Comment by Runaria** [comment]
underscore的`_`是定义在全局变量下的，所以简单的办法就是直接加载

    require('path/to/underscore');          // 不需要封装
    require('path/to/underscore.string');   // 不需要封装
    var _ = window._;
