### ISSUE TITLE
在模块文件中，怎么封装和调用内部函数？不用exports

### ISSUE THREAD

**Issue by Sparkinzy** [seajs/seajs#1442]
```
define('a',function(require,exports){
      exports.doSomething=function(){
           outerFunction();//这样调用似乎是无效的！我又不想通过exports再定义一个方法，this.interFunction  不想这么用
     }

     exports.interFunction=function(){}
});


function outerFunction(){
  // 辅助函数
}
```

**Comment by popomore** [comment]
没看懂，是要调用哪个函数？

**Comment by andyforever** [comment]
把整个对象暴露出去，module.exports = {}，对象内部做好私有和公有方法处理

**Comment by popomore** [comment]
你是这个意思么？

```
define('a',function(require,exports){
     exports.doSomething=function(){
           interFunction();
     }

     function interFunction(){}
});
```

**Comment by Sparkinzy** [comment]
popomore的做法就是我现在的做法~但是还是想学一下andyforever的做法~~不过不太清楚用js做对象内部的公有和私有方法！还想请教一下~~

**Comment by popomore** [comment]
JS 很难区分，函数 bind this 可以做到，但代码不好看，建议用下划线之类的区分公有还是私有

不过这已经不是 seajs 的范畴了

**Comment by Sparkinzy** [comment]
原来如此~谢谢了~~~\(^o^)/~~~

**Comment by andyforever** [comment]
像这样

define(function (require, exports, module) {

        function A() {    
        } 

        A.prototype.doSomething() {
        }

        function innerFunc() {
        }

        module.exports = A;

}

发自我的 iPhone
