### ISSUE TITLE
在模块中require多个文件，在发起请求的时候可以合并吗？

### ISSUE THREAD

**Issue by Sparkinzy** [seajs/seajs#1443]
比如说
define('all',function(require,exports){
        exports.init=function(){
                     require('a');require('b');require('c');require('d');require('e');
                     //  这里做其他事

       }
});

当使用seajs.use('all',function(all){ all.init(); })时，就会发送包括all.js在内的6个请求，我看combo和flush没有在这个情况下使用的~a,b,c,d,e全是当前函数执行需要依赖的库
是否应该写成
define('all',['a','b','c','d','e'],function(require,exports){
      exports.init=function(){
              //不需要在require那5个文件了？ 
      }
});

**Comment by army8735** [comment]
还是需要

**Comment by Sparkinzy** [comment]
怎么来合并这6个请求呢？
