### ISSUE TITLE
seajs 如何进行版本管理？

### ISSUE THREAD

**Issue by runningMan0** [seajs/seajs#1444]
seajs 是一个很好用的工具，现在有一种情况：
页面 index.html:

--script--
seajs.use("a");
--/script--

a.js 依赖于b.js 依赖于c.js

a.js var b =require("b")
b.js: var c =require("c")
c.js: console.log("ok")

这个时候 c.js 有变化 : console.log("modify");
并且加了md5戳 变成了 c.a0b0c0.js
由于在require里面 不能用变量名替代 ：
比如 var x = a0b0c0， c = require("c" + x) 这个时候c的值是undefined

请问各位用过seajs的朋友们 该怎么对seajs进行版本管理？
希望高人能够指点一二 , 感激不尽！

**Comment by army8735** [comment]
用map做映射

**Comment by runningMan0** [comment]
搜了很多资料 没有搜到关于map的 详细信息
能指点一下 在map 里面怎么写么？

**Comment by army8735** [comment]
```js
seajs.config({
  "map": Object/Function
});
```
配置url的映射

**Comment by phpcxy** [comment]
```
seajs.config({
map : [
	[
		"path/to/c.js",
		"path/to/c.MD5.js"
	]
]
.......
})
```

**Comment by andyforever** [comment]
seajs配置的时候不是有个vars对象么？
vars:{version: 0.1}
var c = require('path/to/{{version}}/c.js')
