### ISSUE TITLE
用require加载模块时会请求require.js ，这是什么问题呢？

### ISSUE THREAD

**Issue by callmeJozo** [seajs/seajs#1448]
这是测试代码：
        var ec = require('echarts');
	var line = require('echarts/chart/line');
	var bar = require('echarts/chart/bar');

这是浏览器错误信息：
GET http://localhost:8090/src/base/require.js sea.js:2 
o            sea.js:2 
c            sea.js:2 
s.load    sea.js:2 
s.load    sea.js:2 
d           sea.js:2 
d           sea.js:2

**Comment by callmeJozo** [comment]
![Uploading image.png . . .]()

**Comment by callmeJozo** [comment]
![qq 20150303001125](https://cloud.githubusercontent.com/assets/11005827/6444640/e1c0b01c-c139-11e4-98aa-7d70b7c8b7b7.png)

**Comment by popomore** [comment]
给个能跑的例子

**Comment by callmeJozo** [comment]
都出错了-_-||～～

**Comment by army8735** [comment]
就是出错的线上例子

**Comment by wangjianbing925** [comment]
可能是echarts里面引用了require.js

**Comment by ppq1991** [comment]
因为 echarts.js  自带了全局的**require**，把你的污染掉了。
> echarts.js : 这是包含AMD加载器的echarts主文件，需要通过script最先引入
