### ISSUE TITLE
有没有类似AMD的init方法？用来删除暴露在window的变量？

### ISSUE THREAD

**Issue by unknown-coder** [seajs/seajs#1450]
https://github.com/RubyLouvre/avalon/issues/732
问题描述在这里。
用seajs包装avalon的时候，能require到，但同时也暴露到window去了。

![image](https://cloud.githubusercontent.com/assets/9328734/6479493/20d20736-c281-11e4-9901-85c6f5162deb.png)

**Comment by army8735** [comment]
fork修改avalon源码呗，在其最后delete window.avalon

**Comment by unknown-coder** [comment]
好的！
