### ISSUE TITLE
spm build出现错误，应该是2的老版

### ISSUE THREAD

**Issue by zhaiduo** [seajs/seajs#1451]
spm build出现如下提示：

Deprecated: buildArgs.include is deprecated, using sea, standalone and umd
instead.

npm update后，出现上面的问题。

我看dist目录是空的，应该没有build成功。

**Comment by afc163** [comment]
给重现的例子看看。

**Comment by zhaiduo** [comment]
版本是Spam 2.2.12

spm build
----------------------------

start: build xxx@1.0.0
     Deprecated: buildArgs.include is deprecated, using sea, standalone and umd
instead.
      arguments: cwd = $CWD
      arguments: dest = $CWD\dist
      arguments: zip = false
      arguments: force = false
      arguments: withDeps = false
      arguments: install = true
      arguments: ignore = []
      arguments: skip = []
      arguments: idleading = {{name}}/{{version}}
      arguments: global = {}
      arguments: uglify = {"output":{"ascii_only":true}}
      arguments: cssmin = {}
      arguments: entry = []
      arguments: registry = http://spmjs.io
      arguments: include = all
      arguments: alias = {}
      arguments: output = [".....js"]
      arguments: originPkg = {".....js"]}}
        package: analyse infomation
        package: dependencies:
        package: files:
         output: files:
     extra deps: no
           size: total 0.00kB (gzipped)
         finish: build xxx@1.0.0 (110ms)

**Comment by popomore** [comment]
看日志是3呀

**Comment by zhaiduo** [comment]
晕，我删除重装试试
