### ISSUE TITLE
提问:自定义函数调用问题

### ISSUE THREAD

**Issue by Sparkinzy** [seajs/seajs#1452]
定义了如下一个文件：
define('tool',function(require,exports){
          exports.show=function(){
             //working here
            }

          exports.fun=function(){
            /// do something else
         }
})

问题：我想在show里面使用fun函数，有规范的姿势调用吗？

**Comment by army8735** [comment]
exports.fun就可以了

**Comment by afc163** [comment]
```js
var fun = function() {
};

exports.show = function() {
  fun();
};

exports.fun = fun;
```

**Comment by Sparkinzy** [comment]
哦哦~~哈哈~~没绕过这个弯~~
