### ISSUE TITLE
android 首次进入应用，使用webview加载本地化sea.js，有时候出现无法正常加载的情况

### ISSUE THREAD

**Issue by ChenAllan** [seajs/seajs#1455]
在android上本地化sea.js无法正常加载

**Comment by ChenAllan** [comment]
在android4.0.4上使用webview加载assert下的index.html  html中使用了sea.js框架，但是无法正常加载

**Comment by afc163** [comment]
https://github.com/seajs/seajs/blob/master/CONTRIBUTING.md

**Comment by songyihong** [comment]
我也遇到了，请问你解决了没，我的只会在首次安装应用打开才会出现，之后再打开就不会了

**Comment by ChenAllan** [comment]
是首次的时候才会出现

**Comment by army8735** [comment]
能帮忙调试定位下吗
