### ISSUE TITLE
seajs 2.1.1版本用在app的Cordova框架环境中，首次安装应用会出现无法加载配置的资源

### ISSUE THREAD

**Issue by songyihong** [seajs/seajs#1458]
seajs 2.1.1版本用在app的Cordova（phonegap）框架环境中，首次安装应用后打开会出现无法加载seajs config中配置的preload资源，退出应用之后再打开就不会出现。只有在首次安装打开时会出现，而且不会每次都出现。

**Comment by army8735** [comment]
别用preload了吧，2.2以后就取消了

**Comment by liubiqu** [comment]
相对路径也不行呀。https://github.com/seajs/seajs/issues/1569
