### ISSUE TITLE
spm build 后代码问题

### ISSUE THREAD

**Issue by youpinyao** [seajs/seajs#1459]
spm build 后包了两层define

define("/info-debug", [], function(require, exports, module){
define(function(require, exports, module){
    seajs.log('load info');
    
    function refresh(data){
		var info = $('body > .info');
		info.find('.i1 .lv span').eq(1).html(data.level);
		info.find('.i1 .coin span').html(data.coin);
		info.find('.i2 .experience > div').css('width', ( data.exp / data.nextLevelExp) * 100 + '%');
    }
    
    return {
        refresh: refresh
    }
    
})

});

**Comment by afc163** [comment]
https://github.com/spmjs/spm/issues/897

https://github.com/spmjs/spm/issues/1213

https://github.com/spmjs/spm/issues/881

https://github.com/spmjs/spm/wiki/%E8%B0%83%E8%AF%95-CommonJS-%E6%BA%90%E7%A0%81
