### ISSUE TITLE
使用grunt合并模块后，发现会出现404的出错

### ISSUE THREAD

**Issue by dgunzi** [seajs/seajs#1460]
向大家请教一下，
我在用grunt合并模块后出现了404的问题。
在我的示例中使用了seajs 2.3.0，会出现404错误，找不到模块id所对应的js文件。
如果换成seajs3.0，则报出Error: module was broken的异常
示例地址（采用seajs2.3.0，强制刷新会出现404找不到文件的问题）
[http://www.5niu.org/demo/furnace/](http://www.5niu.org/demo/furnace/ "grunt合并demo")

**Comment by army8735** [comment]
http://www.5niu.org/demo/furnace/dist/js/main.js

id不匹配

**Comment by dgunzi** [comment]
那为什么在一般情况下是正确的呢？
我在app/index.main.js里采用的是正确的id啊
    define(function(require, exports, module){
	return {
		init : function(){
			require('dist/js/cssTable/cssTable.interface.js');
			require('dist/js/pagination/pagination.interface.js');
			furnace.cssTable('#main');
    	  	furnace.pager('#main',furnace.tableCallback);
		}
	}						
});
