### ISSUE TITLE
紧急求助....

### ISSUE THREAD

**Issue by unknown-coder** [seajs/seajs#1463]
实际项目使用中 碰到一个 非常玄乎的bug。。只在每次服务器重启后首次进页面才会出现，正常刷新页面不出现。
```javascript
seajs.use(["test"], function(test){
    //test 未提供出来
});
```
请求远程协助。。跪求，拜谢！！

扣扣号： 1669338874

**Comment by unknown-coder** [comment]
找到了问题的原因所在
jsp中使用了
```html
<jsp:include page="test.jsp" flush="true"/>
```
元凶是这个flush="true"，改为false就不再报错。


test.jsp里有一段这样的脚本
```html
seajs.config({
    alias: {
        test: "test"
    }
});
seajs.use(["jquery", "test"], function($, test){
    $(function(){
        console.log(test)  // null
    });
});
```

不是太明白为什么和服务器缓冲搭上关系？
而且只是在服务器重启的第一次访问才报错？
后续刷新访问都不报错？
希望有碰到类似问题的，或者了解这个问题原因的，能讲解下，谢谢了。
@lifesinger

**Comment by army8735** [comment]
http://blog.csdn.net/zw_2011/article/details/7431360

**Comment by unknown-coder** [comment]
虽然不是太明白其中原因，但总算是找到了问题的根源，并且解决也很简单
把flush="false"即可

此贴就 为后来人指路 吧。。不要踩到这么深的坑。

**Comment by army8735** [comment]
属于jsp的东西吧，缓存输出
