### ISSUE TITLE
seajs和jQuery整合

### ISSUE THREAD

**Issue by anglezhang** [seajs/seajs#1465]
问题重现步骤：
1.在项目中引入seajs框架。
2.引入jQuery框架。
3.设置sea全局变量如：
seajs.config({
                base: './lib/'
                , alias: {
                    'jquery': 'jquery/jquery'
                }
            });
问题，浏览器报错，$不是函数。

**Comment by zjgnlzq** [comment]
改成这样，另外jquery文件中不要加id
```
seajs.config({
base: './lib/'
, alias: {
'jquery': 'jquery/jquery',
'$': 'jquery/jquery'
}
});
```

**Comment by anglezhang** [comment]
你是改了个变量名，这个不起作用的，它不是找不到文件，是不能识别$为函数。

**Comment by anglezhang** [comment]
补充说明：如果目录层级结构是 “./lib/jquery/jquery/2.1.0/jquery.js ”   js源码最后添加“  ;$.noConflict(); ”可以直接使用，如果是其他啊目录层级结构，则需要将jquery模块化，即文件前加“ define(function(require, exports, module){   ”，中间部分是jquery源码，文件后面加“});”。

**Comment by zquancai** [comment]
模块化后，暴露接口。用seajs引入后，才能调用接口，接口不一定要是$符号

**Comment by anglezhang** [comment]
1.seaJS
    在seaJS使用jQuyer，如果是任意路径下，则需要将就jQuery进行封装，如图：
如果是在特定路径下，则使用spm安装即可。
    使用seajs框架，需要将sea.js导入项目，然后指定入库js文件。如图：
这个时候，jQuery不需要想图一那样，前部加“define(function(require,exports,module)){ ,”，后面加“});”进行模块化，也可以正常使用。请问，这是为什么？


anglezhang_116@126.com
 
发件人： zquancai
发送时间： 2015-04-01 14:12
收件人： seajs/seajs
抄送： anglezhang
主题： Re: [seajs] seajs和jQuery整合 (#1465)
模块化后，暴露接口。用seajs引入后，才能调用接口，接口不一定要是$符号

**Comment by zquancai** [comment]
@anglezhang 你看看jquery源码的最后几行，它有给出CMD和AMD支持，所以直接用define关键字包裹就行了

**Comment by anglezhang** [comment]
您好！
     上次这个问题我可能没有描述清楚，导致您的理解有误。由于工作原因暂时将问题搁置。
     我的意思是，sea.js引入jquery,如果目录结构是  jquery/jquery/x.xx.x/jquery(x.xx.x表示版本号)，则无需用define(function(require, exports, module){//jquery源码...}) 
进行包装，但如果不是这种结构的话，则需要使用上述方式进行包装，同一个框架，目录不同，使用方式不同，应该可以视为bug吧？


anglezhang_116@126.com
 
发件人： Army
发送时间： 2015-04-05 16:18
收件人： seajs/seajs
抄送： anglezhang
主题： Re: [seajs] seajs和jQuery整合 (#1465)
Closed #1465.
