### ISSUE TITLE
seajs 如何传入自定义变量

### ISSUE THREAD

**Issue by kingviker** [seajs/seajs#1466]
vars传入的变量 只在require加载的路径中有效,有没有可以传入自定义变量的动能?

**Comment by army8735** [comment]
啥意思

**Comment by kingviker** [comment]
就是在 seajs.config{
...
vars:{"aa":"xxx"}
}
定义的变量只能在require('{xxx}/aa')想这样使用 其他js代码里面怎么使用? 比如我要把页面的baseurl传进来 因为是ajax应用 ajax的url需要加上baseurl

**Comment by army8735** [comment]
那个是专为path服务的

ajax的话为何用require？直接xhr相对路径不行？

**Comment by kingviker** [comment]
相对路径可以 不过加上baseurl更保险了 已经习惯都加上了,我没有办法引用config的变量么?比如seajs.config.vars.aa 我可以这样子直接引用么

**Comment by army8735** [comment]
可以用，只是提取依赖失效而已
