### ISSUE TITLE
define()函数中，deps参数的作用是什么?声明依赖用require不就行了吗

### ISSUE THREAD

**Issue by gdut-zdc** [seajs/seajs#1467]
这个deps是模块的依赖部分，但是为什么会需要这个部分呢，我有两方面不懂：
1.我直接使用require("a")来引入依赖不就行了吗？
2.而且直接在deps声明依赖，模块当中又是怎样使用到的，比如我们经常会这样 var a = require("a")；来获取到依赖模块“a”，并且做一个赋值操作给变量  a，才可以使用到模块a提供的接口。但是在deps当中是怎样实现的？

**Comment by army8735** [comment]
deps是供构建使用，免得js分析依赖，提升速度，以及递归依赖时提前加载。

**Comment by gdut-zdc** [comment]
意思是不是说 deps 声明了依赖会被自动的require进来？
那么我们如何使用它呢，比如 deps 为[“a.js”,"b.js"]，我们要怎么用到 a.js 里面的 一个暴露出来的方法（比如 sayHello() 这个方法）

**Comment by army8735** [comment]
和nodejs保持一直，var a = require("a.js"), a.xxx

**Comment by gdut-zdc** [comment]
意思是说如果声明了deps依赖数组[“a","b"]，在factory里面还需要 var a = require("a");var b = require("b")？

**Comment by army8735** [comment]
写的时候不用写deps，直接commonjs。构建工具做的事情就是包define、提取依赖到deps上。运行时无需再分析依赖，提高速度

**Comment by gdut-zdc** [comment]
嗯~那当我没有使用构建工具的时候呢，是不是就是说当我手动写上deps的时候，运行时不再分析依赖了？

**Comment by army8735** [comment]
对

**Comment by gdut-zdc** [comment]
那么关于递归依赖提前加载呢，如果我手动写上的话也是需要把递归依赖也要写上吗？

**Comment by army8735** [comment]
不需要，如果提前写，配合combo的话，相当于把所有依赖一次性加入，节省http请求。这就是构建工具和静态资源服务器方面的优化了。
