### ISSUE TITLE
gulp 打包工具推荐 gulp-cmd

### ISSUE THREAD

**Issue by elover** [seajs/seajs#1468]
给大家推荐一个简单方便的基于gulp打包seajs的插件，[gulp-cmd](https://github.com/elover/gulp-cmd)；
为什么不推荐用spm，主要是因为他很难和gulp或grunt集成，如果你想实现一些自己的需要，会比较麻烦，虽然spm是官方推荐的，但毕竟它主要还是立足于支付宝的需求，所以，也一直希望社区能够出现更好的打包工具，这里推荐的gulp-cmd有相应的example,大家可以下载玩玩，更欢迎提建议并共同维护出一个更大众化的打包工具，官方的团队不要生气哦

**Comment by cnchanning** [comment]
fork别人的代码加点文档改个名字发布是什么心态

**Comment by fundon** [comment]
GitHub 有个功能叫 `Fork`，GitHub 出这个功能什么心态？

**Comment by lichunqiang** [comment]
:8ball:

**Comment by elover** [comment]
不改名字，提交不了npm就这么简单

**Comment by cnchanning** [comment]
那么请问您除了改了个名字以外，[gulp-cmd](https://github.com/elover/gulp-cmd)和[gulp-seajs-combo](https://github.com/chenmnkken/gulp-seajs-combo)有什么区别？

**Comment by elover** [comment]
不得不承认目前除了修复自己已知的bug和给代码添加更详细的注释没有什么区别，不过，和原作者有过交流，gulp-seajs-combo主要是为了满足作者自己公司的需求，我提了一些需求，作者没有时间满足，就建议我fork一份代码，后期，根据自己的公司需求和大家的反馈肯定会出现一些差异，在seajs打包上纠结了很久，不希望大家也这么纠结，所以才产生了这个项目，如果我真的如你所想，我根本就不fork，直接提交一份代码，岂不更好，都是开源，何必计较呢?

**Comment by ccwq** [comment]
肚量决定高度，如果不希望别人fork，请设置为私有。
