### ISSUE TITLE
seajs和fis集成的问题

### ISSUE THREAD

**Issue by ckrad** [seajs/seajs#1469]
现在项目用了fis来加md5戳 不知道怎么管理seajs的config文件 所有的js文件配置在一个config文件里 一旦一个js文件发生变化 config中配置的路径就会发生变化 整个网站的head里面都加在了这个配置文件 这会导致全站包括实际没有改动的页面缓存会失效 有没有好一点的config管理方法

**Comment by army8735** [comment]
config能针对特定的单一js进行么？

**Comment by ckrad** [comment]
@army8735 不明白你的意思 你是对某个js进行单独的config吗 我现在是把第三方的库配置到一个config中 全局加载 别的在模块define之前配置 感觉这样不是很方便 管理起来也有点麻烦

**Comment by army8735** [comment]
我看错了。

html也做静态缓存？除非是静态页面。

想更灵活就得做依赖分析了，每个页面出现的config只有用到的模块才会。

**Comment by ckrad** [comment]
@army8735 怎么做依赖分析 有没有现成的工具支持seajs和fis

**Comment by ckrad** [comment]
@army8735 我一个页面用了很多include 这样可以做依赖分析吗

**Comment by army8735** [comment]
递归分析即可，fis我不知道有没有，自己做解析费点事但不难。
