### ISSUE TITLE
请教下,这样包装 jquery 插件 怎么不行?应该怎么改? 谢谢!

### ISSUE THREAD

**Issue by enng0227** [seajs/seajs#1470]
<html>
<literal>

define(function (require, exports, moudles) {

    return function ($) {
        //插件内容       

        ;(function ($) {
                    ....
        })(jQuery);
        ;
        (function ($) {
                    ....
        })(jQuery);
        ;
        (function ($) {
            // only implement if not provided by jQuery core (since 1.4)
             ....
        })(jQuery);

//自定义validate扩展
        jQuery.extend(jQuery.validator.messages, {
            required: "必选字段",
            remote: "请修正该字段",
            email: "请输入正确格式的电子邮件",
            url: "请输入合法的网址",
            date: "请输入合法的日期",
            dateISO: "请输入合法的日期 (ISO).",
            number: "请输入合法的数字",
            digits: "只能输入整数",
            creditcard: "请输入合法的信用卡号",
            equalTo: "请再次输入相同的值",
            accept: "请输入拥有合法后缀名的字符串",
            maxlength: jQuery.validator.format("请输入一个长度最多是 {0} 的字符串"),
            minlength: jQuery.validator.format("请输入一个长度最少是 {0} 的字符串"),
            rangelength: jQuery.validator.format("请输入一个长度介于 {0} 和 {1} 之间的字符串"),
            range: jQuery.validator.format("请输入一个介于 {0} 和 {1} 之间的值"),
            max: jQuery.validator.format("请输入一个最大为 {0} 的值"),
            min: jQuery.validator.format("请输入一个最小为 {0} 的值")
        });

        jQuery.validator.addMethod("regularExpression", function (value, element, param) {
            if (element) {
                var reg = new RegExp(param);
                return reg.test(value);
            }
            else {
                return false;
            }
        }, "");

        jQuery.validator.addMethod("byteRangeLength", function (value, element, param) {
            var length = value.length;
            for (var i = 0; i < value.length; i++) {
                if (value.charCodeAt(i) > 127) {
                    length++;
                }
            }
            return this.optional(element) || (length >= param[0] && length <= param[1]);
        }, "请确保输入的值在个字节之间(一个中文字算2个字节)");

        jQuery.validator.addMethod("isMobile", function (value, element) {
            var length = value.length;
            return this.optional(element) || (length == 11 && /^(13[0-9]|15[0-9]|18[0-9])\d{8}$/.test(value));
        }, "请正确填写您的手机号码");

        jQuery.validator.addMethod("telphone", function (value, element) {
            var length = value.length;
            return this.optional(element) || (/^[\d|-]+$/.test(value));
        }, '格式错误，仅支持数字和符号“-”');

        jQuery.validator.addMethod("zipcode", function (value, element) {
            var length = value.length;
            return this.optional(element) || (/^[0-9]{6}$/.test(value));
        }, '格式错误，仅支持6位数字');

    };

});

</literal>
</html>

**Comment by enng0227** [comment]
是 jquery 插件 validate

**Comment by army8735** [comment]
应该依赖jQuery吧

**Comment by enng0227** [comment]
因为JQuery 有多个版本,  如果这里 require JQuery 就会指定JQuery版本,   

这样就会产生一个问题, 一个页面  可能会 调用两个不同版本的JQuery.

**Comment by enng0227** [comment]
define(function (require, exports, moudles) {

return function ($){ 
               //jquery插件主体 
}

});


除了依赖Jquery,还有上面的引入方式外,还有没有别的办法? 求指导.

**Comment by Lomyal** [comment]
这种引入方式不错啊，很多jQuery插件都是这么写的，可以在引入该插件时指定jQuery的版本，比如jquery-mousewheel。
不过根据题主插件的内容，开头`return function ($) {`中参数名应该写`jQuery`吧。

**Comment by enng0227** [comment]
@Lomyal  可以了,谢谢!
