### ISSUE TITLE
为什么 parseDependencies() 方法中会存在着这么多对空白符、数字、引用等的处理

### ISSUE THREAD

**Issue by gdut-zdc** [seajs/seajs#1472]
parseDependencies() 方法用来解析依赖，但为什么要一个一个字符去处理，我们去匹配的不是只是去匹配到 require后面的依赖而已吗，为什么还会去检测空白符、引用、数字等

**Comment by army8735** [comment]
```js
if(true)/require('a')/.test('');
//require('a')
'require("a")'
/*
require('a')
/*
```
以及上面所有的排列组合。
实际上这步在构建中做了，源码里有是开发阶段的词法分析而已。

**Comment by army8735** [comment]
可以看到github的高亮第一个就错了

**Comment by gdut-zdc** [comment]
构建是用的什么spm插件？  上面说到的检测注释里面的require()语句，不是也可以使用一个或几个正则来做到，但我看到的parseDependencies()会一个一个字符去检测，这样不会造成效率下降么，而且这样做也没有必要吧？

**Comment by gdut-zdc** [comment]
@army8735

**Comment by army8735** [comment]
构建用的也是这个

**Comment by gdut-zdc** [comment]
不懂~~那为什么要用一个字符一个字符的来检测？望指导

**Comment by army8735** [comment]
你写个把1楼那些匹配出来

**Comment by gdut-zdc** [comment]
==，之前的版本中不是也是用了两个正则就可以达到 parseDependencies的效果了么~不知道新版本这样处理是为了什么原因

**Comment by army8735** [comment]
https://github.com/seajs/crequire

**Comment by keelii** [comment]
原来的正则处理方式会有很多的潜在问题，我自己就遇到过问题，后来换成了新版 seajs 中的基于词法分析的 parseDependencies 方法就没问题。[详情](https://keelii.github.io/2017/11/03/fix-seajs-parse-dep-bug/)
