### ISSUE TITLE
有没有关于 seajs 的QQ群或者旺旺群 ? 

### ISSUE THREAD

**Issue by enng0227** [seajs/seajs#1473]
如题,求分享

我没有找到相关的群,自己创建了一个,在这里公布下QQ群号:438690754

**Comment by afc163** [comment]
有这么优秀的 issues 不用，干嘛非要用 QQ 群。

**Comment by enng0227** [comment]
issues 确实很好,QQ群也有QQ群的好处,有个专门的QQ群或旺旺群来谈论 也没有什么弊端

**Comment by popomore** [comment]
在群里估计只有吐槽闲聊什么的，这里是神圣领地（好中二）。

**Comment by enng0227** [comment]
有思想碰撞,才有智慧火花. 可以禁止闲聊.但是不能禁止别人吐槽

**Comment by fundon** [comment]
有问题在 issues 提，有个好个，管理员可以打 label 之类的，后期还可以搜索。

**Comment by enng0227** [comment]
经验是可以总结出来,汇成文档,方便查阅.
如果没有一个导向,很难找到答案, [ 如果字典没有目录 ]
也许群可以充当一个灵活的目录,
我没有找到相关的群,自己创建了一个,在这里公布下QQ群号:438690754

希望大家能加入进来,相互帮助,相互学习.

**Comment by popomore** [comment]
不打嘴炮，好好干活，其他人有兴趣可以加。
