### ISSUE TITLE
安装spm编译错误

### ISSUE THREAD

**Issue by kissing1540** [seajs/seajs#1474]
[root@localhost hello]# node -v
v0.12.1
[root@localhost hello]# python -V
Python 2.7.5
gcc version 4.8.2 20140120 (Red Hat 4.8.2-16) (GCC) 

npm install spm-build -g

然后抱这个错误

gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/spm-build/node_modules/6to5/node_modules/kexec/.node-gyp"
child_process: customFds option is deprecated, use stdio instead.
make: Entering directory `/usr/lib/node_modules/spm-build/node_modules/6to5/node_modules/kexec/build'
  CXX(target) Release/obj.target/kexec/src/kexec.o
../src/kexec.cc: In function ‘int clear_cloexec(int)’:
../src/kexec.cc:22:30: error: ‘F_GETFD’ was not declared in this scope
     int flags = fcntl (desc, F_GETFD, 0);

**Comment by army8735** [comment]
去spm那边问吧，像是依赖的东西在win上编译有问题
