### ISSUE TITLE
webWorker 判断有误

### ISSUE THREAD

**Issue by gdut-zdc** [seajs/seajs#1476]
这样判断浏览器是否支持 web worker:
var isWebWorker = typeof window === 'undefined' && typeof importScripts !== 'undefined' && isFunction(importScripts);
在最新版 chrome 打印出来就会发现 isWebWorker 为false。是否应该改为var isWebWorker = typeof Worker !== "undefined" ;

**Comment by army8735** [comment]
如果某个js里自定义了Worker对象呢？

**Comment by gdut-zdc** [comment]
这样的话，使用 typeof Worker 的确不保险，但是像上面的判断 typeof window === 'undefined' &&... window在什么情况下会等于 undefined ?这样的话 isWebWorker 一直会是false了吧..

**Comment by army8735** [comment]
@akfish

**Comment by akfish** [comment]
Chrome stable V41.0.2272.118测试无误。
`isWebWorker`并不是用于判断浏览器是否支持Web Worker，而是判断sea.js是否运行于Web Worker环境中。
