### ISSUE TITLE
seajs.use与当前页面define放在一起，请求2次。

### ISSUE THREAD

**Issue by cxwarny2008** [seajs/seajs#1477]
html页面：
"script src="~/Js/Index.js"></script>
Index.js
define(function (require, exports, module) {
//代码
});
seajs.use("/Js/Index");
通过这种方式加载firebug查看网络请以求存在2次请求Index.js，这种可以改变？这个define只属于这个页面使用。

**Comment by army8735** [comment]
id不匹配的话就是再加一次
