### ISSUE TITLE
请教下怎么封装 webuploader,谢谢!

### ISSUE THREAD

**Issue by enng0227** [seajs/seajs#1478]
webuploader 百度的上传组件地址: http://fex.baidu.com/webuploader/

因要考虑到jquery版本,所以用这种方式包装

define(function (require, exports, moudles) {
    
    return function($){
          /* WebUploader 0.1.6 */
          //这里是:webuploader.min.js
    };
});

这样包装后,提示  WebUploader is not defined  ,不知道怎么修改了

**Comment by cnchanning** [comment]
http://spmjs.io/package/webuploader

**Comment by LiXunGuan** [comment]
@enng0227 我之前在github上找到了一个，传到git.osc上面了。[webuploader for seajs](http://git.oschina.net/tgw/webuploader-for-seajs)

**Comment by enng0227** [comment]
谢谢!
