### ISSUE TITLE
关于打包压缩的一个问题

### ISSUE THREAD

**Issue by unknown-coder** [seajs/seajs#1479]
公司项目用seajs模块化改造完成了，这几天刚开始接触学习打包工具gulp，有个疑惑。。

这是目录结构
![image](https://cloud.githubusercontent.com/assets/9328734/7131365/ffeae0ba-e2b0-11e4-9f85-38d70e721277.png)

test.html
```html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
    <script type="text/javascript" src="js/sea.js"></script>
    <script type="text/javascript">
        seajs.use("a/a");
    </script>
</head>
<body>

</body>
</html>
```

a.js
```javascript
define("a/a", ["b/b"], function(require, exports, module){
    console.log("a.js")
    var b = require("b/b");
    b.test();
});
```

b.js
```javascript
define("b/b", [], function(require, exports, module){
    exports.test = function(){
        console.log("b.js");
    };
});
```

假如我把a.js和b.js合并到dist/a&b.js
1. 页面上的 seajs.use("a/a"); 该怎么改？
2. a.js 和 b.js 中define函数的id 和 deps 需不需要改？

**Comment by unknown-coder** [comment]
为什么没人理。。。困扰好几天了。。。。。

**Comment by sorrycc** [comment]
页面上手动引入 `dist/a&b.js`，就可以用 `use('a/a')` 了。

推荐使用 spm 吧。。
https://github.com/spmjs/docs

**Comment by unknown-coder** [comment]
好像我用spm也会遇到同样的问题吧，我现在是还没理解。。
假如我把a.js和b.js合并到dist/a&b.js
1. 页面上的 seajs.use("a/a"); 该怎么改？
2. a&b.js 中 模块a 和 模块b define函数的 id 和 deps 需不需要改？

**Comment by div-wang** [comment]
可以用`spm`自动打包工具;
设置全局`base`路径到你的项目中`/dist/`目录下;
页面引入的是个入口文件use(a&b);
入口文件控制各个模块的引入关系，打包之后直接合并到dist目录下生成一个和入口文件相同名字的js文件，可直接引入，不会有任何错乱和不解

**Comment by unknown-coder** [comment]
@div-wang 

我实际项目中写的模块都是 用的 顶级标识，类似a/a，b/b这样的路径

最近看资料好像看到说要合并的话得用 相对标识，且要保证合并后相对相对路径不变

是否有这样的要求？

**Comment by div-wang** [comment]
我觉得这个可以约定一下目录结构，根据目录结构做相对路径打包；
下面是我们的目录结构：
```javascript
   -- dist
       -- import
           -import.js
   -- import 
       -import.js
   -- jquery 
      -jquery.js
   -- lib
      -a.js
      -b.js
      -c.js
   -package.json
   -sea.js
```
`/import/`目录存放入口文件，入口文件负责整合模块
`/jquery/`目录存放jquery文件和jquery插件
`/lib/`目录存放模块js，都是通用的模块，
配置文件配置好文件打包路径，将入口文件打包进`dist`目录
`sea.js`设置base路径到`/dist/`目录下
页面中直接引入文件`seajs.use(import/import)`
import,js里用require引进来需要的js模块，最后可以写点页面琐碎的js,然后spm build打包；
这样最大限度的解放了大家对id的依赖，是大家更专注对模块的开发；
上线也更简单，只用把`/dist/`目录放到线上就直接可以上线了。

**Comment by honger05** [comment]
spm build 不是只能打类似
  ```bash
    -- a
        - src
            - a.js
            - b.js
        - package.json
```

斗胆问一下 可以合并压缩打包 不在同一文件夹下的 文件吗？

**Comment by afc163** [comment]
文件夹结构可以任意地自定义：

```
    -- a
        - yyy
            - c.js
        - xxx
            - a.js
            - b.js
        - package.json
```

**Comment by honger05** [comment]
比方说 
```
   -- sea-module
         - jquery
                - jquery.js
         - moment
                - moment.js
         - biz
                - index.js
         - package.json
```

这样可以把 jquey 和 moment 打包到我的 index 中了？
