### ISSUE TITLE
seajs.use的加载依赖路径问题？

### ISSUE THREAD

**Issue by elover** [seajs/seajs#1480]
比如说：src文件夹下，有use.js和define.js文件
use.js的内容是：
```
seajs.use('./define');
```
define.js的内容是：
```
define(function(){
      console.log('ok')
})
```
html文件是通过script标签引入use.js,除了配置alias './define'之外，有没有可能通过use.js的相对位置加载define.js呢？我知道seajs.use是通过当前域加载，define是通过文件相对位置加载，这两者为什么要设置成不同的呢？有没有可能统一？

**Comment by army8735** [comment]
当时就是为了区别而故意设置成这样的…… ＝ ＝

**Comment by elover** [comment]
为什么要故意设置成这样呢，那有没有办法seajs.use通过相对位置来加载依赖呢？如果不用seajs.use还能用什么其他作为启动文件

**Comment by elover** [comment]
之所以这么问，是因为我开发的时候用seajs来加载文件，线上上线前会打包，因为存在seajs.use和define加载依赖的规则不同涉及到有些配置要配，如果，都能相对文件路径加载，我几乎都不用太多设置seajs.config

**Comment by army8735** [comment]
use.js应该用require就好了

**Comment by elover** [comment]
seajs.require吗？不需要什么插件？似乎不起作用呢，文件都没有加载，我的版本是 2.3.0

**Comment by elover** [comment]
```
//入口文件
seajs.require('./define_demo'); // 这样写不会加载define_demo.js
```

**Comment by army8735** [comment]
我是说use.js写成cmd，里面加载用require(xxx)

**Comment by elover** [comment]
我是这样在页面引入use.js的，想下面那么写，define里面的代码都不执行的
```
<script src="use.js"></script>
```
use.js
```
define(function(require,exports,module) {
    require('./define_demo');
});
```

**Comment by elover** [comment]
@army8735 有解决办法吗？

**Comment by army8735** [comment]
use.js不要引入，用seajs.use加载

**Comment by elover** [comment]
我之所以把seajs.use放到use.js里，就是因为，我不想在html页面里用seajs.use，最终打包的时候可以把define和use打包到一起的，而且写在页面里，md5处理也麻烦

**Comment by army8735** [comment]
这我也想不出来……

**Comment by elover** [comment]
那谢了，不要勉强，我自己在页面用use了
