### ISSUE TITLE
require.async加载，seajs.cache问题

### ISSUE THREAD

**Issue by flicker85** [seajs/seajs#1482]
index.html
----------------------------------------------------
<code>

    seajs.config({
      base:'./js'
    });
    seajs.use("main",function(main) {
      main.init();
    });

</code>
===================================
js/a.js
-----------------------------------------------------
<code>
define(function(require, exports, module) {
  exports.run = function() {
    $('#testBtn').on('click',function(){
      var name = './b';
      require.async(name,function(b) {
        b.run();
      });
    });
  };
});
</code>
====================================
js/b.js
------------------------------------------------------
<code>
define(function(require, exports, module) {
  exports.run = function() {
    console.log('bb');
  };
});
</code>
===================================
反复点击testBtn按钮
seajs.cahe中出现多个缓存

http://localhost:8080/_use_0: 
thttp://localhost:8080/js/a.js: 
thttp://localhost:8080/js/a.js_async_2: 
thttp://localhost:8080/js/a.js_async_3: 
thttp://localhost:8080/js/a.js_async_4: 
thttp://localhost:8080/js/a.js_async_5: 
thttp://localhost:8080/js/a.js_async_6: 
thttp://localhost:8080/js/a.js_async_7: 
thttp://localhost:8080/js/b.js: t
http://localhost:8080/js/main.js: t
http://localhost:8080/js/main.js_async_1: t

是说seajs这种情况没办法解决么？？还是说我这种写法有问题？？

**Comment by army8735** [comment]
不用担心。如果你有洁癖，可以把sync提出click来

**Comment by flicker85** [comment]
实际应用场景是在hashchange事件里，根据url的变化值使用require.async动态加载页面的相关html和js模块，页面js模块还会依赖于其它的js模块，主要是怕页面反复切换，seajs.cache占用内存过多，或者有什么办法可以手动清理cache么？比如缓存的js数量大于50个就把最旧的缓存清理掉？

**Comment by army8735** [comment]
delete seajs.cache

sync提出click来就行了

**Comment by flicker85** [comment]
没明白你的意思，我就是想通过页面触发的click，hashchange之类得事件，根据事件里得变量，加载相应的js模块，sync提出到哪里呢？不放在事件里又怎么通过事件触发加载js呢？

**Comment by army8735** [comment]
提到click外面，click里面只是执行调用

**Comment by flicker85** [comment]
<code>

define(function(require, exports, module) {
exports.run = function() {
    $('#testBtn').on('click', function() {
      var name = './b';
      loadPage(name);
    });
    function loadPage(name) {
      require.async(name, function(b) {
        b.run();
      });
    };
  };
});
</code>

**Comment by army8735** [comment]
async后callback里写click侦听

**Comment by flicker85** [comment]
不是很明白，能贴个代码出来么0.0~

**Comment by army8735** [comment]
```js
define(function(require, exports, module) {
  exports.run = function() {
require.async('./b', function(loadPage) {
    $('#testBtn').on('click', loadPage);
});
  };
});
```

**Comment by flicker85** [comment]
额，你没明白我的意思，实际场景是这样的，那个name是动态的，不是写死的
```javascript
define(function(require, exports, module) {
  exports.run = function() {
    $('window').on('hashchange', function() {
      //根据url变化，动态加载执行视图以及对应的js
      var name= document.location.hash;
      loadPage(name);
    });
    function loadPage(name) {
      require.async(name, function(page) {
        page.render();
      });
    };
  };
});
```
我想实现这样的功能，不知道该怎么写。
如果这样写是能跑起来的，但是seajs.cache中会出现
<pre>
http://localhost:8080/js/a.js_async_2: 
http://localhost:8080/js/a.js_async_3: 
http://localhost:8080/js/a.js_async_4: 
http://localhost:8080/js/a.js_async_5: 
http://localhost:8080/js/a.js_async_6: 
http://localhost:8080/js/a.js_async_7: 
</pre>

**Comment by army8735** [comment]
```js
define(function(require, exports, module) {
  exports.run = function() {
	require.async('./b', function(loadPage) {
    	$('#testBtn').on('click', function() {
    		var name = document.location.hash;
    		loadPage(name)
    	});
	});
  };
});
```

**Comment by flicker85** [comment]
你的意思是先加载b模块再绑定click事件，当click的时候把name传给b模块里的函数，然后再通过
b模块里的函数执行require.async加载name模块么？

**Comment by army8735** [comment]
对

**Comment by flicker85** [comment]
main.js
```javascript
define(function(require, exports, module) {
  exports.init = function() {
    var load = require('./load');
    $('#testBtn').on('click', function() {
      //name是动态的
      var name = 'page1'; //document.location.hash;
      load(name);
    });
  };
});
```
load.js
```javascript
define(function(require, exports, module) {
  module.exports = function(name) {
    console.log('load page');
    require.async(name, function(page) {
      page.render();
    });
  };
});
```
page1.js
```javascript
define(function(require, exports, module) {
  exports.render = function() {
    console.log('page1');
  };
});
```
反复点击按钮以后的结果，按钮click实际上是模拟hashchange事件
![test](https://cloud.githubusercontent.com/assets/5960708/7196094/9cd89f68-e4fd-11e4-8490-e12110881ab0.jpg)

**Comment by flicker85** [comment]
现在seajs.cache里出现了许多load.js对象，我想要的效果就是当点击按钮时根据参数动态加载不同的页面，可是不希望在seajs.cache中出现那么多重复的缓存

**Comment by army8735** [comment]
动态加载的话可以用json。
非要用的话自己做缓存也行。
Object.keys(seajs.cache)遍历自己去删亦可。

**Comment by flicker85** [comment]
好吧，我再研究下，还有个问题，如果a,b,c都有run函数，我这样写可以么？用工具编译以后会不会有问题？
```javascript
var arr = ['a','b','c'];
require.async(arr,function(){
    for(var i=0,len=arguments.length;i<len;i++) {
        arguments[i].run();
    }
});
```

**Comment by army8735** [comment]
buhui

**Comment by flicker85** [comment]
ok, thx
