### ISSUE TITLE
关于 define 多模块加载，指定加载先后顺序。

### ISSUE THREAD

**Issue by bb729253747** [seajs/seajs#1483]
define(function (require, exports, module) {
    require('jquery');
    require('knockout');
    require('My97');
    require('Bases');
    require('CommonBase');
    require('Common');
    require('Pager');
    ko.applyBindings(viewModels);
});

这个顺序需要强制从上到下，发现执行时，有时候顺序不对。
非常感谢能帮我说说问题的所在，谢谢。

**Comment by bb729253747** [comment]
你好。我想问下 关于多个模块加载中, a b c d e f...  都是依次依赖的  f 依赖 e 依赖 d  到a，我使用 require(a), require(b) .... require(...)  但是执行时发现并不是按照 a b c d ... 来依次加载的。 求教

**Comment by afc163** [comment]
https://github.com/seajs/seajs/issues/1379
https://github.com/seajs/seajs/issues/1231#issuecomment-45723065
https://github.com/seajs/seajs/issues/1367
