### ISSUE TITLE
define中的this问题

### ISSUE THREAD

**Issue by china-liji** [seajs/seajs#1484]
``` javascript
define(function(require, exports, module){
	console.log(this);
});
```
这里的this指向window，按照Nodejs来说，this应该是指向exports。

我本来想结合自己的类库，在define中使用this，结果，this指向window。
你的源码：
``` javascript
var exports = isFunction(factory) ?
      factory(require, mod.exports = {}, mod) :
      factory;
```
应该改成：
``` javascript
var exports = isFunction(factory) ?
      factory.call(mod.exports = {}, require, mod.exports, mod) :
      factory;
```

不然，你的模块化里面不能用this，是件很糟糕的事情，模块化怎么能少了this呢？

**Comment by army8735** [comment]
我也认为

**Comment by china-liji** [comment]
看来seajs很久没人维护了，我自己还是支持国产的，没多去用requirejs。
既然没人维护了，我就自己改动下他的源码，满足下自己先...

**Comment by army8735** [comment]
我就是维护者

**Comment by lifesinger** [comment]
这个不能修改的，是有意设计为 this 指向 window，具体讨论可见 commonjs 与 requirejs 很早以前的讨论。主要原因是，尽量向前兼容，减少封装成本。

现阶段，我推荐直接用 NodeJS 的 CommonJS 规范去书写代码，然后通过 spm3 去打包运行，不再需要 seajs。

**Comment by afc163** [comment]
玉伯从 Github 复出了？

**Comment by popomore** [comment]
玉伯说最近有点闲

**Comment by lichunqiang** [comment]
闲了就更新下博客吧 - -！ 让我们了解下现在的高端技术

**Comment by lifesinger** [comment]
我在跟勺子学设计，一名设计新秀正冉冉升级 -.-

**Comment by army8735** [comment]
commonjs的规范的话，this指向exports。即使打包，运行时如果使用了this，还是会造成web和server不兼容的情况。
如果考虑到历史遗留，2.x版本满足需求。3.0我建议修正之。

**Comment by lifesinger** [comment]
尽量是不要用 this。在 CommonJS 里，也推荐用 module 变量，语义更清晰。在 XMD 里，直接用 window.

**Comment by china-liji** [comment]
谢谢更新，立即下载
