### ISSUE TITLE
2.3版把base路径的自动探测去掉了吗

### ISSUE THREAD

**Issue by stoneChen** [seajs/seajs#1485]
2.2.1版中有这么一段
![qq20150417-1 2x](https://cloud.githubusercontent.com/assets/4470552/7201897/37d4585e-e53f-11e4-9c40-b8f6bea08b1c.png)
现在源码中找不到了，是出于什么原因去掉了呢？
去掉之后，在seajs.config中是不是必须要写base了？

**Comment by army8735** [comment]
对的，交由自己控制

**Comment by stoneChen** [comment]
👌

**Comment by dotnil** [comment]
breaking change... 这个更应该发 3.0
