### ISSUE TITLE
CMD规范所谓的“通用”模块定义的“通用”为何意？

### ISSUE THREAD

**Issue by stoneChen** [seajs/seajs#1486]
之前看过不少于关于AMD规范与CMD规范区别的文章，但都没有对“通用”这个字面义做解释，是指浏览器和NodeJs中都可以运行吗？但AMD模块好像也可以两个环境都能运行吧？还有AMD字面义是异步模块定义，但CMD模块也是异步加载的呀。对两者的字面义表示不是很理解。

**Comment by army8735** [comment]
Common

**Comment by lifesinger** [comment]
C 代表 CommonJS

忘掉 CMD 和 AMD，直接拥抱 CommonJS

**Comment by stoneChen** [comment]
👌
