### ISSUE TITLE
requirejs也支持CMD, seajs的优势何在?

### ISSUE THREAD

**Issue by RoyLING** [seajs/seajs#1487]
看[requirejs的作者写的](https://github.com/jrburke/requirejs/wiki/Differences-between-the-simplified-CommonJS-wrapper-and-standard-AMD-define). 定义模块有2种模式可选，Common JS Wrapper就是seajs所遵守的CMD。
鉴于requirejs的流行程度，seajs的优势何在呢？

**Comment by army8735** [comment]
表面差别应该不是太多，细节上有些。

另外不清楚最近requirejs的发展情况，不知道一些区别后来有没有更新。

* 性能。由于采取了传递引用算法，没有依赖回溯的过程，因此性能上要快O(n)
* 依赖解析。词法分析完全符合commonjs规范，require在这上面采取了偷懒但性能更好的正则匹配，但配上工具的话性能不是问题
* 循环依赖。支持commonjs规范的循环依赖。

但use上作为入口会有语意的不同，这点是使用上的感觉。

**Comment by RoyLING** [comment]
谢谢作答，去研究一下你说的性能这块。
