### ISSUE TITLE
seajs 打包之后 require返回的对象为null

### ISSUE THREAD

**Issue by honger05** [seajs/seajs#1488]
```
   define("tms/login/1.0.0/login-debug", [ "$-debug" ], function(require, exports, module) {
      var $ = require("$-debug"), Utils = require("utils-debug");  // null
   }
```
这样 返回的 $ 、Utils 都为 null 。

```
   define("tms/login/1.0.0/login-debug", function(require, exports, module) {
      var $ = require("$-debug"), Utils = require("utils-debug"); // object
   }
```
`, [ "$-debug" ]`  把依赖删除了 就 正常了。

为什么啊！

**Comment by army8735** [comment]
那个是工具用的，提前解析。如果遇到这个参数就不即时解析加快速度了。第2个参数是undefined，自然没有

**Comment by honger05** [comment]
```
define("att/b/1.0.0/a-debug", [ "b-debug" ], function(require) {
    var b = require("b-debug"), c = require("c-debug");
    console.log(b); // object
    console.log(c); // null
});
```
我刚刚测试发现 如果  `[ "b-debug" ] ` 这里不写成  `[ "b-debug" , "c-debug" ]` 的话 ，下面的c就是null

就是说 `[ "b-debug" ] ` 提前解析了，下面的require将不再解析。如果上面不配置 `[ ] ` 依赖。才会去解析 rquire() 的文件。


那么问题来了！

为什么我的spm2打包的时候 就只自动添加第一个依赖`b-debug`。后面的依赖`c-debug`不会再加上去，导致c的对象是null。

**Comment by army8735** [comment]
@sorrycc

**Comment by honger05** [comment]
另外 请教一个问题

之前 我想用spm3的   但是spm3不能直接打包在本地。  后来放弃了。

后来看了些spm3的资料， 了解到 现在都写成 commonjs规范的

打包的时候 线上再把它封装成 cmd的。

然后再下载下来用。。。


我对 spm3 现在的做法 的理解对吗？

**Comment by army8735** [comment]
spm3可以本地打包

**Comment by afc163** [comment]
`spm build`

**Comment by honger05** [comment]
我用spm2打包 ，又有个问题 
  抽取依赖的时候，相对路径为 ` [ "./lo\\lo-debug"]`  这样会报这个文件找不到的错误
改成 ` [ "./lo/lo-debug"] ` 就没问题。

前者是加载文件，后者是加载模块

**Comment by nimojs** [comment]
@honger05  
关于 spm3 请关注这个issues 
https://github.com/spmjs/spm/issues/1273
