### ISSUE TITLE
3.0版本问题

### ISSUE THREAD

**Issue by siguang1983** [seajs/seajs#1489]
使用3.0版本时use回调找不到外部接口,  

// 错误提示：Cannot read property 'zc' of undefined
seajs.use("distZcLottery", function(zcbuy){
        var zcBuy = window["zcBuy"] = zcbuy.zc(lotteryId, playId);   
})

// 模块
define(function(require, exports, module){

    function Zc(lotId, playId){
           // 业务逻辑
    }

    var zc = function(lotteryId, palyid){
        return new Zc(lotteryId, palyid);
    }

    exports.zc = zc;
})

**Comment by army8735** [comment]
use不匹配吧，看看cache里是不是有2个

**Comment by siguang1983** [comment]
模块调用都引用的没问题，v1.3.0 这个版本就不会出现这个问题，
用grunt来构建的，用1.3.0版本都正常，用3.0这个版本，就提示找不到'zc' of undefined

**Comment by army8735** [comment]
demo

**Comment by siguang1983** [comment]
github还没玩明白，没客户端要不先加一个Q我传给你。632505215

**Comment by army8735** [comment]
army8735@qq.com
邮件即可

**Comment by army8735** [comment]
#930
