### ISSUE TITLE
iphone4s微信6.1.4版本中使用3.0版本加载模块会有问题

### ISSUE THREAD

**Issue by nanedo** [seajs/seajs#1491]
使用的是iphone 4s
Mozilla/5.0 (iPhone; CPU iPhone OS 7_1_2 like Mac OS X) AppleWebKit/537.51.2 (KHTML, like Gecko) Mobile/11D257 MicroMessenger/6.1.4 NetType/WIFI

页面还在开发测试阶段，所有模块未合并，以独立文件方式存在。
加载第一个模块的时间要35秒左右，后续的都正常加载；

换回2.2.3版本后，加载正常，1秒以内。

**Comment by army8735** [comment]
你用了加载css了吗？

**Comment by nanedo** [comment]
没有使用它加载css。

**Comment by army8735** [comment]
能提炼个小demo发上来看看吗

**Comment by nanedo** [comment]
define(function(require, exports, module) {

/* Zepto v1.1.6 - zepto event ajax form ie - zeptojs.com/license */
/* zepto touch plugin */
/* zepto fx plugin */

module.exports = Zepto;
});

发现是引入的zepto文件有问题。
文件结构如上，头尾是我自己加的，主要代码是zepto（1.1.6）与其插件（event ajax touch fx）的源码（未作修改）。

**Comment by army8735** [comment]
只是加载zepto卡住了？其它逻辑不要，单独加载一个zepto

**Comment by nanedo** [comment]
https://github.com/nanedo/seajs-question
刚测试用的是这个

**Comment by army8735** [comment]
呃，我没那个微信开发的号，只pc上看没看出啥问题……

**Comment by army8735** [comment]
https://github.com/seajs/seajs/blob/master/dist/sea-debug.js#L272

可以用这个试试断点，是不是进isWebWorker逻辑了？

**Comment by nanedo** [comment]
改用seajs 2.2.3也没问题。
我试试你说的方法
