### ISSUE TITLE
seajs+angularjs刷新加载错误.求解

### ISSUE THREAD

**Issue by darkbluegood** [seajs/seajs#1493]
<script src="js/sea.js"></script>
	<script type="text/javascript">
		seajs.config({
			alias : {
			},
			preload : ["angular.min","angular-route.min","zepto"],
			debug : true
		});

		seajs.use('main');
	</script>
我是这样引入js文件的..
有时按F5刷新就加载错误了.有时又正常..
错误信息:
Uncaught TypeError: Cannot read property 'module' of undefined(anonymous function) @ angular-route.min.js:7(anonymous function) @ angular-route.min.js:14
index.html:1 GET http://www.xxx.com/project/shangjing/js/angular-route.min.js.map 404 (Not Found)
index.html:1 GET http://www.xxx.com/project/shangjing/js/angular.min.js.map 404 (Not Found)
angular.min.js:6 Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.3.15/$injector/modulerr?p0=app&p1=Error%3A%20…2F%2Fwww.xxx.com%2Fproject%2Fshangjing%2Fjs%2Fangular.min.js%3A17%3A381)

要是换成以下传统方式就正常
/<script type="text/javascript"  src="js/sea.js"></script>
<script type="text/javascript" src="js/angular.min.js"></script>
        <script type="text/javascript" src="js/angular-route.min.js"></script>
	<script type="text/javascript" src="js/zepto.js"></script>
	<script type="text/javascript" src="js/app.js"></script>
	<script type="text/javascript" src="js/main.js"></script>\

**Comment by thonatos** [comment]
我在angular+saejs（或者说是lib与自写模块的使用）的使用上偏好正常使用lib，对自写代码使用seajs进行代码组织，也就是这么使用：

```
/* Javascript Libs */
<script type="text/javascript" src="js/angular-route.min.js"></script>
<script type="text/javascript" src="js/zepto.js"></script>
<script type="text/javascript" src="js/sea.js"></script>

/* Seajs Support */
<script type="text/javascript">
    seajs.config({
        debug : true
    });
    seajs.use('./app', function(app) {
    main=require('./main').create('');    // Main Script Can do something ...
    app.init(main.do());
  });
</script>
```

**Comment by Runaria** [comment]
preload加载的模块/文件是没有先后顺序的，而angular-route.min.js明显对angular.min.js有依赖，当route先载入完成而angular本体还没载入的话，就会报错

**Comment by darkbluegood** [comment]
@Runaria 有什么解决的好办法？
