### ISSUE TITLE
安卓版微信seajs.use callback函数未执行

### ISSUE THREAD

**Issue by li2274221** [seajs/seajs#1498]
之前提交了一个issue说是没加载到文件，其实文件是加载了的。
但是seajs.use('./a',function(A){
    // do something
    // 该函数未能执行，跪求答案。系统已经快瘫痪1天了
 })

**Comment by army8735** [comment]
那估计是 #930

**Comment by li2274221** [comment]
原因找到了，但不知道如何处理。
在加载依赖文件的时候会有部分文件加载失败，具体原因不知道是什么。
因为上述问题只在安卓版的微信浏览器中出现，无法具体debug。而且问题也只是在昨天4月30号才出现的，不知道大神有没有好的解决办法。
