### ISSUE TITLE
seajs引用jquery插件报错Uncaught ReferenceError: $ is not defined

### ISSUE THREAD

**Issue by tylerpanpan** [seajs/seajs#1501]
现在的版本不能用require("./jquery.**.")($)这种写法了吗，试了下报错，现在怎么引用插件的？？

**Comment by army8735** [comment]
**这种写法是啥

**Comment by tylerpanpan** [comment]
就是require各种各样的jquery插件，我省略写的

**Comment by army8735** [comment]
demo

**Comment by tylerpanpan** [comment]
var $ = require("jquery");
require("./jquery-tabs")($);
其中jquery-tabs是我的一个jquery插件，但是报错了，需要怎么处理吗？

**Comment by army8735** [comment]
jquery没引到吧，改写cmd

**Comment by tylerpanpan** [comment]
刚刚找到原因了，是没有对jquery插件进行封装，封装一下就好了，3Q
