### ISSUE TITLE
是否考虑增加require once 函数

### ISSUE THREAD

**Issue by ckken** [seajs/seajs#1502]

**Comment by ckken** [comment]
angular 安需加载 微信加载两次 directive报错

**Comment by army8735** [comment]
require本来就是只加载一次，2次是怎么回事

**Comment by ckken** [comment]
在没export的文件 微信第一次进入加载文件 但微信需要授权 跳转回来之后 重新请求 但是微信已经缓存函数 故报错 目前采取文件路径请求判断

**Comment by ckken** [comment]
是否跟seajs.use有关系

**Comment by army8735** [comment]
use的话同一个文件也是一次的。你那个问题太概述了，没听懂

**Comment by ckken** [comment]
微信 sea use 懒加载  模块 模块里面加载公共组件 两个模块用到 但如果组件注册两次hui报错 就是这样

**Comment by ckken** [comment]
muqian 外置一个对象判断是否已经加载 bixu weixin 才you

**Comment by ccwq** [comment]
当加载器用了吗

**Comment by lifesinger** [comment]
可以提供具体用例代码，而不是文字描述。

require 本来就是加载一次的。

**Comment by ClassJS** [comment]
@ckken 应该是你在模块中使用define定义模块的时候写法有问题，我们团队的新手就是在define内return function($){组件实现}，在用到jQuery组件的时候用require('plugin/jquery.slides')($);去初始化组件，好好去了解一下seajs的加载原理。seajs团队可以考虑画一个seajs的工作原理图，帮助新手更好的理解seajs的思想。

**Comment by ClassJS** [comment]
@ckken
define(function(require, exports, module) {
    var jQuery = require('jquery');
    (function($, window, document) {
        //插件实现
    })(jQuery, window, document);
    /**
    *容错处理，主要兼容旧版本
    *  旧:
    *   var $ = require('jquery');
    *   require('plugin/jquery.slides')($);
    *  新:
    *   require('plugin/jquery.slides');
    */
    return function(){};
});

**Comment by ckken** [comment]
@ClassJS 应该是你说的这个问题 
我引入方式是 require('plugin/jquery.slides')($);
但是 我得 $符号不是全局的 不能像 require('plugin/jquery.slides'); 这样导入 
有更好的解决方案否

**Comment by ClassJS** [comment]
@ckken 上面已给出解决方案，只需要在define中加入var jQuery = require('jquery');就可以了

**Comment by ckken** [comment]
https://github.com/ckken/ngSea/blob/master/app/angularjs/ngSea-0.6.1.js  这是我写的插件 在
 seajs.use(route.controllerUrl, function(m){
                            $rootScope.activeApply(function () {
                                if(angular.isUndefined(m)){
                                    deferred.reject(m);
                                }else{
                                    deferred.resolve(angular.isFunction(m) ? m(register,app) : m);
                                }
                            });
                        });
引入之后 我需要模块化ng 的diretive 引入
    module.exports = function(app){
        require('directive/pjCarousel')(app) //这个模块报错
        require('directive/bottomFix')(app)
        require('directive/productStatus')(app)
        app.controller(app.cname,['$scope', '$routeParams', 'RQ', '$timeout', '$location','$sce',function ($scope, $routeParams, RQ, $timeout, $location,$sce) {
            //$scope.vm = $routeParams

目前解决方案是
        require('plugin/carousel')
        G.loaded_directive = G.loaded_directive||[]
        if(G.loaded_directive.indexOf('pjCarousel')===-1) {
            G.loaded_directive.push('pjCarousel')

注意只有微信会报错 其他场景都正常 在微信第一次进去没错 第2次进去就报错了

**Comment by ClassJS** [comment]
@ckken 哥你代码的可读性太差了，你自己用chrome调试一下，跟一下流程应该就能找到问题了！这个时候真希望你们能用面向对象的编程思想写js，可以了解下class.js能直接打印function的调用链...

**Comment by ckken** [comment]
@ClassJS 难道你就是传说中百年难得一遇的练武奇才 失敬失敬！
