### ISSUE TITLE
我用最新的3.0.1，为什么请求不到模块？ 冰天雪地跪求

### ISSUE THREAD

**Issue by baijunjie** [seajs/seajs#1503]
![qq 20150512100819](https://cloud.githubusercontent.com/assets/7956480/7578958/092853f8-f88f-11e4-8507-eaeeb9fc8d9b.png)
jquery 是最新的 2.1.1
![qq 20150512100840](https://cloud.githubusercontent.com/assets/7956480/7578959/09d81982-f88f-11e4-8fed-aefd19a76ac0.png)
输出两个空对象？？？
![qq 20150512101037](https://cloud.githubusercontent.com/assets/7956480/7578970/2b20cea4-f88f-11e4-97d8-b8792423bab2.png)
我用的是 dsit 目录下的 sea.js

**Comment by afc163** [comment]
1. https://github.com/seajs/seajs/blob/master/CONTRIBUTING.md
2. 可能是 #930

**Comment by baijunjie** [comment]
你好，这些我全部都看过，我想可能是我引入的 sea.js 有问题
![qq 20150512105303](https://cloud.githubusercontent.com/assets/7956480/7579344/2758fef8-f895-11e4-8751-9fed9ca0906a.png)
![qq 20150512105322](https://cloud.githubusercontent.com/assets/7956480/7579348/2b7985c0-f895-11e4-8735-65f3ce03e21a.png)
我用的是seajs  github 中 dist 目录下的 sea.js 文件， 是今天才下载的，版本3.0.1

**Comment by afc163** [comment]
建议用已发布的版本。

**Comment by baijunjie** [comment]
我使用了 3.0.0  、  2.2.3 、 2.2.0  都不行？我看jquery关于cmd的定义
![qq 20150512113012](https://cloud.githubusercontent.com/assets/7956480/7579724/e7b58072-f89a-11e4-9dd6-2c6a741efeba.png)
jquery 首先要判断在全局环境下 module 对象存在，才会去定义cmd模块
网上现在都用一种通用的模块定义方法来定义模块
![qq 20150512113637](https://cloud.githubusercontent.com/assets/7956480/7579747/3fc6caa0-f89b-11e4-856e-0ab7aa569b02.png)
问题应该就在这里！sea.js 不支持？

**Comment by afc163** [comment]
https://github.com/seajs/seajs/issues/971

**Comment by army8735** [comment]
define.amd删掉……

**Comment by baijunjie** [comment]
恕我直言，作为一个广泛应用的框架，应该海纳百川，既然删除一句define.amd就能解决的问题，seajs没什么不伪装一个amd对象来兼容主流模块？为什么一定要让别人来兼容自己？

如果我去修改jquery，那是不是就等于放弃了使用CDN？有多少人会愿意这么做？

连requireJS都主动兼容cmd的定义，seajs为什么不可以？

**Comment by lichunqiang** [comment]
忘掉seajs，拥抱commonjs。

**Comment by afc163** [comment]
忘掉 Sea.js，拥抱 CommonJS。

**Comment by army8735** [comment]
我倒是一直想加上去……

唯一的麻烦是怕不兼容，但如果都是写common的话其实是兼容的……
