### ISSUE TITLE
在手机浏览器上require缓慢，不知道是什么原因

### ISSUE THREAD

**Issue by littlehey** [seajs/seajs#1504]
电脑模拟手机浏览器也挺快的
就是手机浏览器执行这段代码耗了9秒多

var time1,time2;
require.async(['mobileec', 'ic', 'front', 'event'], function(ec, ic, front, event){
	time2 = new Date().getTime();
	alert((time2-time1)/1000);
});
time1 = new Date().getTime();

**Comment by army8735** [comment]
webview加载执行太卡了吧

**Comment by littlehey** [comment]
不是的，是用手机浏览器打开的，safari  没有webview的

**Comment by army8735** [comment]
说错了，就是移动浏览器

**Comment by littlehey** [comment]
没有任何道理啊。。。

**Comment by xiatian** [comment]
我有个webapp在ios上浏览器和webview也很卡顿，andriod正常，换requirejs就没问题。。。

**Comment by liushuigs** [comment]
我在safari上同样遇到这类问题。多个js用require.async加载时，他们并不是异步的。是等所有都加载成功了，一次性出来结果。页面卡顿太长时间。

**Comment by liushuigs** [comment]
好像是个bug，用3.0.1版本的卡。换成2.3.0的就没事了

**Comment by littlehey** [comment]
我放弃了，改用requirejs完全没这问题

**Comment by littlehey** [comment]
我放弃了，改用requirejs完全没这问题

**Comment by army8735** [comment]
请使用构建后的第2个参数deps显示指明依赖，避免实时解析造成的性能消耗。

**Comment by xiatian** [comment]
算了，投奔requirejs了

**Comment by djx314** [comment]
就是因为 requirejs 搞 knockout 有 bug 才投奔 seajs 的，换回 2.x 试试。

**Comment by Hi-Rube** [comment]
seajs + react 本来在android测试一点问题都没有，，，今天到ios上测试一下就卡死了，搞到现在真是研究不下去了。。。过来提下问http://dev.tripwy.com/app_view/V2.0/main.html#/index 这个地址，android 和 ios测试下，，，ios 上微信打开微信直接卡蹦，qq也是，uc也是

**Comment by Hi-Rube** [comment]
经过测试问题不在react - -

**Comment by nightost** [comment]
我也回归了版本，确实是版本问题。
代码很多，无法逐个的“使用构建后的第2个参数deps显示指明依赖”
