### ISSUE TITLE
为什么exports不能放入构造函数

### ISSUE THREAD

**Issue by ioriandy4** [seajs/seajs#1506]
如下，a.js  require b.js ,

-------------a.js代码：------------------------
define(function(require,exports,module){
	var a=require('export_test/b.js');
	console.log(a);
	a.sayName(); //报错
})

------------b.js代码--------------
define(function(require,exports,module){
	function c(){
		this.theName='tom';
	}
	c.prototype.sayName=function(){
		alert(this.theName);
	}

	//传递c类
	exports.a=c;
})

在b.js声明了构造函数（大多数插件都是这样的），想传递出去用，在a.js里面用却报错了，请问应该如何写呢

**Comment by afc163** [comment]
你暴露的对象是 `exports.a = c`。

所以调用的应该是 `require('export_test/b.js').a`。

**Comment by ioriandy4** [comment]
但是我想整个构造函数都暴露出去，怎么写呢？如果直接require 文件的b.js进去，在a.js里面用new实例化，是可以，但这样是不是违反了规范

**Comment by ioriandy4** [comment]
用了 require('export_test/b.js').a 。  也只能暴露出
function c(){
		this.theName='tom';
}
但是
c.prototype.sayName=function(){
		alert(this.theName);
}

却没有暴露出来

**Comment by afc163** [comment]
1. `sayName` 在 c 的 prototype 上啊。

2. 不想多一个累赘的 a 的话，可以使用 `module.exports = c;` 来暴露。

https://github.com/seajs/seajs/issues/242

**Comment by ioriandy4** [comment]
还是不行，我的代码这样的，怎么写呢

----------b.js-------
define(function(require,exports,module){
	function c(){
		this.theName='tom';
	}
	c.prototype.sayName=function(){
		alert(this.theName);
	}
	//传递c类
	 module.exports=c; 
})



----------------a.js-----------------------
define(function(require,exports,module){
	var a=require('export_test/b.js');
	console.log(module.exports);//空对象
	a.sayName(); //报错
})

**Comment by afc163** [comment]
```js
// ----------------a.js-----------------------
define(function(require,exports,module) {
  var A= require('export_test/b.js');
  console.log(A);//空对象
  var a = new A();
  a.sayName();
});
```

可以补点 JS 关于 prototype 的基础知识。
