### ISSUE TITLE
link标签支持onload事件，但是不触发onload

### ISSUE THREAD

**Issue by lincheng0803** [seajs/seajs#1507]
请问下，为什么判断版本号低于536的为旧版的webkit呢？有啥资料吗？ 现在问题是这样的，我的魅族，userAgent为 "Mozilla/5.0 (Linux; U; Android 4.4.2; zh-cn; MX4 Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Mobile Safari/537.36" ，它被判断为新版webkit，且 supportOnload = ‘onload’ in node返回true，但是通过创建link标签加载css却无法触发onload，所以导致后续的代码无法被回调执行。把版本改为低于538，可以正常运行，就是不知道会不会引起其他问题？谢谢

**Comment by army8735** [comment]
mx4的原生是534，你这个用的像是chrome，支持onload的。你是用老的AppleWebKit的问题吧。

**Comment by lincheng0803** [comment]
在线升级过一次，用的是自带的浏览器，测试的结果却是有onload属性，但是加载时不触发，你一般是如何 验证onload是否触发呢？要不用你的方法再测下试试

**Comment by army8735** [comment]
创建个link标签侦听onload……，魅族不会去改webkit内核改出bug吧，我的flyme是4.2.2.1A
