### ISSUE TITLE
3.0.0 在 ietester 和 ie8 下面不能正常工作，已经不支持低版本 ie 了么

### ISSUE THREAD

**Issue by djx314** [seajs/seajs#1510]
手贱下载 3.0.0 试用，在 ietester 和 原生 ie8 下面或者死了，或者 cpu 占用 25% （我4核）一段时间之后才加载到页面，在ff和chrome没有问题，降级到 2.3.0 一切正常，经过试验，如果 define 内部没有 require 语句的话正常（例如只有alert），有 require 语句的话就悲剧了，总结一下：
条件：
1、浏览器： ietester（6，7，8）， 原生 ie8
2、版本： 3.0.0
3、seajs.use(xx) 这句话对应的那个主模块的 define 内部有 require ，这个模块 require 的其他模块貌似没问题
现象：
1、cpu 占用满一个核一段时间才正常加载
2、或者 ietester（6，7，8） 直接死掉
解决方法：
1、降级到 2.3.0

**Comment by army8735** [comment]
把你有require语句的贴一下

**Comment by djx314** [comment]
<https://github.com/djx314/seajs-issue/blob/master/public/miao.js>
刚搭了个 mini 的，如果去除 ko 那句 require 就正常，如果就这样运行的话访问 miao.html 在 ietester 和 ie8 下会有那么几秒的cpu占用满一个核，我的工程会有十来秒。
ps:1、knockout 我是改造过的，在一头一尾加了个 define ，
2、用旁边那个 seajs1111.js(2.3.0) 的就没问题。

**Comment by army8735** [comment]
等我回去看

**Comment by army8735** [comment]
没发现问题，暂时没有原生ie8。估计是解析依赖太耗时，用构建后的看看，就是加上第2个参数。

**Comment by djx314** [comment]
我把 knockoutjs 换成构建后的，然后复制了 10 份，用不同的 alias 加载，速度快了 5-6 倍，但我用 win2003 的 virtualbox 虚拟机的 ie6 解析还是有一段时间cpu占用满一个核
![win2003](http://b30.photo.store.qq.com/psb?/V128gsIv2NwlRF/ybAy2H5Qp7KyxNOgYiuLRBcryWmHjeD*PYbzPsJI*TI!/b/dB4AAAAAAAAA&amp;amp;bo=9gGmAPYBpgAFACM!&rf=viewer_311)
win8 虚拟机 的 ie10 好一点，但也会占用满一个核
![win8](http://a1.qpic.cn/psb?/V128gsIv2NwlRF/zoXssj4i3F5v3*hz1wMhzNB6qoVSV5A4bNOM6o6gm38!/b/dGQAAAAAAAAA&ek=1&kp=1&pt=0&bo=0QSvANEErwADCC0!&sce=50-1-1&rf=viewer_311)

另外，win2003，win8，ubuntu 的 firefox 都没问题，换回 seajs 2.3.0 全部都没问题。

**Comment by army8735** [comment]
有了虚拟机在查

**Comment by army8735** [comment]
构建的第2个参数没有指明。

knockout.js中没有依赖的话要
```js
define([],function(require...
```js
另外里层还有define.amd判断，这里要改写成commonjs的写法。
