### ISSUE TITLE
一个模块同步 require 无返回， async.require 有返回，如何理解错误出现在什么地方？

### ISSUE THREAD

**Issue by kmvan** [seajs/seajs#1511]
模块 a，别名是 a，实际路径是 a.php?xxx=a.js，内容是 :
```js
// code 0
// module a
define({
	"user": {
		"logged": false
	},
	"theme-nonce": "202462219c"
});
```
上面的模块 a，是存在的，返回文件类型是 js，但可能会有***数秒的 loading 延迟***。
那么问题来了，我在模块 b 中调用 a，如下：
```js
// code 1
// module b
define(function(require, exports, module){
	var a = require('theme-cache-request');
	console.log(a);
});
```
此时 b 模块居然没有任何东西被输出，但 a 模块已经能在请求中看到。将 b 模块换成异步调用：
```js
// code 2
// module b async
define(function(require, exports, module){
	async.require(['theme-cache-request'],function(a){
		console.log(a);
	});
});
```
此时 b 模块异步调用 a，能获取 a 的返回对象。

那我就想不通了，为啥会出现这种情况，没有任何错误提示哦。而且在 code 1 的例子里面，有时候浏览器刷新多几次，说不定就***有一次能成功输出 a***。感觉好奇怪啊。
我猜测有可能是因为 a 模块由 php 输出，有一定的 loading 时长，所以导致了一些奇怪的问题。（等会去试验一下）
不知道各位有没有遇过？

**Comment by Nuintun** [comment]
检查下id与路径的对应关系

**Comment by kmvan** [comment]
情况有些复杂，可能上述例子太单一……
不过我从 seajs 3.0.1 换成 seajs 2.3.0 后，就 100% 成功无异常了……

**Comment by army8735** [comment]
#1510
#1504

**Comment by kmvan** [comment]
虽然不是很明白……
