### ISSUE TITLE
为什么这样暴露不出接口啊

### ISSUE THREAD

**Issue by ioriandy4** [seajs/seajs#1512]
define('iama', [], function(require, exports, module) {
  exports.show =10;
});

为什么暴露不出

**Comment by afc163** [comment]
https://github.com/seajs/seajs/blob/master/CONTRIBUTING.md

**Comment by army8735** [comment]
估计自己定了id遇到 #930

**Comment by justnode** [comment]
定义模块的时候不要使用id，单独一个factory参数就ok
