### ISSUE TITLE
请问seajs引用库都要用define封装一下吗？

### ISSUE THREAD

**Issue by jerrydong** [seajs/seajs#1515]
我们的项目，经常需要引用一些框架，插件，来做快速开发。
此外，开发过程中也会有一些自己的库。
目前，正在考虑用seajs把前端文件整理一下，可是，发现引用jQuery之类的库必须用define重写。jquery倒还好，我们的项目还用了baidu的tangram库及插件（请不要鄙视，用了很多地方，项目快上线了），我还要包装tangram吗，以后可能用别的库，也都要封装一下？

谢谢解惑~~

**Comment by army8735** [comment]
可以用工具做

**Comment by jerrydong** [comment]
请问是什么工具哈，spm或者grunt吗，谢谢这位大神~~~

**Comment by nuintun** [comment]
自己写个最好，生产环境模块最好都转换成标准模式
define(id, [deps], factory);
这样的结构。
