### ISSUE TITLE
在最新的IOS微信中调用seajs.use()非常慢。

### ISSUE THREAD

**Issue by liuyanhui** [seajs/seajs#1516]
在最新的IOS微信中调用seajs.use()非常慢，然而在Android下确没有这个问题。大概有5s左右的延迟，现在还不明确是那个步骤的问题。

**Comment by afc163** [comment]
建议用 seajs@2.3.x 试试。

**Comment by liuyanhui** [comment]
@afc163 多谢。已经换成2.2.3，一切正常。对于这个问题有说法么?

**Comment by afc163** [comment]
具体情况不清楚。

我猜是 3.0 的词法分析碰到巨大文件的性能问题？

- 3.0：https://github.com/seajs/seajs/blob/3.0.0/src/util-deps.js
- 2.3：https://github.com/seajs/seajs/blob/2.3.0/src/util-deps.js

**Comment by afc163** [comment]
@army8735

**Comment by army8735** [comment]
ios下确实有点慢，很神奇为何字符串遍历如此慢，即便是最新浏览器。
也包括ipad。还有像Symbol等缺失，都和桌面不一致。

上线还是用build的吧，那个是给开发时的便捷和构建的工具。
