### ISSUE TITLE
无法监听DOMContentLoaded事件

### ISSUE THREAD

**Issue by anntiantian** [seajs/seajs#1521]
使用了seajs就无法监听到DOMContentLoaded事件了
seajs.use(["zepto"], function(zepto){
     document.addEventListener("DOMContentLoaded", function(){
         alert("DOMContentLoaded");
      });
 });
不会弹出alert

第一行改成seajs.use([], function(){
就可以弹出

**Comment by army8735** [comment]
因为已经发生过了。判断是否DOMcontentloaded。

**Comment by anntiantian** [comment]
是因为seajs加载模块太快了吗？
因为想使用avalon.js，才发现这个问题，没有办法，只好改了avalon的源码，注释了这些代码
//    if (W3C) {
//        avalon.bind(DOC, "DOMContentLoaded", fn = function() {
//            avalon.unbind(DOC, "DOMContentLoaded", fn)
//            flush()
//        })
//    } else {
        var id = setInterval(function() {
            if (document.readyState === "complete" && document.body) {
                clearInterval(id)
                flush()
            }
        }, 50)
//    }
感觉现在的模块监控DOMcontentloaded事件的应该不少，是否需要修复一下
如：http://requirejs.org/docs/api.html#pageload

**Comment by army8735** [comment]
是因为异步加载模块发生在DOMcontentloaded之后。

应用自己侦听时自己应该先判断ready是否发生过了

**Comment by anntiantian** [comment]
哦，了解了，谢谢
