### ISSUE TITLE
模块定义别名后,找不到模板文件了.

### ISSUE THREAD

**Issue by gutun** [seajs/seajs#1522]
define(function(require, exports, module) {
    console.log(module.uri);
    var html = require('./modules/example/test/test.tpl');
    console.log(html);
});
正常的输出html
define('demo.init.js',[],function(require, exports, module) {
    console.log(module.uri);
    var html = require('./modules/example/test/test.tpl');
    console.log(html);
});
返回 null

**Comment by army8735** [comment]
你这说明也太简单了……

#930

**Comment by gutun** [comment]
https://github.com/gutun/seajsdemo/tree/master/demo001  示例已经上传

**Comment by gutun** [comment]
我是根据 seajs-text的示例改造了下,发现定义模块Id后,找不到模板文件,但是我输出模块的url是可以访问的.

**Comment by gutun** [comment]
自己尝试出来了.还是把id机制去掉了.
