### ISSUE TITLE
是不是3.0.1中的写法改变了。

### ISSUE THREAD

**Issue by miaojiangmin** [seajs/seajs#1523]
seajs.use(['jquery'],
	function($){
	alert(123);
	console.log($);
	console.log(jQuery);
这种写法在以前2.1.1是没有问题的
但是今天尝试了一下3.0.1 的版本发现
第一个是undefine
第二个是有对象的。

后来我修改成
seajs.use(['jquery'],
	function($){
	var $ = require('jquery');
	console.log($);
	console.log(jQuery);
就没有报错了，如果是写法改变了，希望能够兼容以前的写法，毕竟以前的文件都是这样写的

**Comment by army8735** [comment]
没有改变，你的应该是#930

另外jQuery要改造成commonjs兼容的。

**Comment by miaojiangmin** [comment]
thanks
