### ISSUE TITLE
Firefox下路径斜线被替换为%5C，require失败

### ISSUE THREAD

**Issue by zhaiduo** [seajs/seajs#1525]
比如：
var lib = require('../my/lib');
在firefox下路径变成%5Cmy%5Clib.js，导入require文件失败，如何破？版本为Firefox36

**Comment by army8735** [comment]
demo

**Comment by zhaiduo** [comment]
貌似 ../my/lib.js 被替换成了 ..\my\lib.js

**Comment by zhaiduo** [comment]
替换替换后，lib.js有能被正常解析，也不影响程序执行。只是会提示：

"NetworkError: 403 Forbidden - ..%5Cmy%5Clib.js"
