### ISSUE TITLE
seajs有Local Storage缓存插件吗？

### ISSUE THREAD

**Issue by teng315** [seajs/seajs#1526]
比如像腾讯这样的，把js第一次读取后放入Local Storage里，下次require时，如果发现已经在本地缓存（Local Storage）里，就直接从Local Storage里读取
图片无法上传。。。。

**Comment by afc163** [comment]
https://github.com/pigcan/seajs-plugin-storage.js

**Comment by teng315** [comment]
谢谢  刚才找了个
https://github.com/QzoneTouch/commonWidget/tree/master/seajs-plugin/src
在研究下你这个，谢谢

**Comment by huanz** [comment]
可以看看这个，比较简单的：[https://github.com/huanz/seajs-cache](https://github.com/huanz/seajs-cache)

**Comment by teng315** [comment]
@huanz 不错，谢谢
先试试去，这就三个了
前面2个确实不太会用，要配置mainfest。。。
