### ISSUE TITLE
3.0.1+seajs-css插件时，crossorigin配置失效

### ISSUE THREAD

**Issue by kidney** [seajs/seajs#1527]
`seajs.config`配置`crossorigin`，并使用`seajs-css`时候，`script`标签没有加上`crossorigin`属性

### 原因：
seajs-css的`request`函数[#L149](https://github.com/seajs/seajs-css/blob/master/src/seajs-css.js#L149)
覆盖了
seajs/src/util-request.js的`request `函数[#L90](https://github.com/seajs/seajs/blob/master/src/util-request.js#L90)

希望把seajs-css更新一下。

**Comment by army8735** [comment]
thx
