### ISSUE TITLE
cdn缓存问题

### ISSUE THREAD

**Issue by sunylt** [seajs/seajs#1529]
求助！
使用seajs，模块修改发布后，cdn缓存清理有没有可靠有效的方式（现在问题1.不能修改模板  2.使用cdn清缓存接口不保险  而且combo的文件缓存没法清理）
支付宝针对静态资源的缓存更新及模块版本号的控制是怎么样的呢？希望能提供一些思路，谢谢。

**Comment by popomore** [comment]
使用版本号，上传 cdn 后不能覆盖只能增加版本。
sunylt <notifications@github.com>于2015年6月9日 周二上午9:38写道：

**Comment by sunylt** [comment]
谢谢。那这个版本号是自动处理还是手动维护？
另外假如一个公共模块 arale/cookie  被10个地方引用了，现在修改后发布了，有没有好的办法确保每个引用都更新过来，谢谢。

**Comment by sunylt** [comment]
我想能做到是能维护页面入口的更新，但是如果是入口依赖的模块，或者是依赖的模块的依赖想更新就没有办法了，心塞 。

**Comment by army8735** [comment]
做为被异步加载的全局模块，应该在发布系统里做版本记录。然后每个页面vm里引入全局模块版本读取系统，进行缓存实时更新。

**Comment by sunylt** [comment]
嗯 谢谢二位的回答。这边会再想办法解决的。你们的cdn缓存（包括combo的url）是可以做到想更新的时候就能更新过来的嘛？

**Comment by army8735** [comment]
你也可以放在导航里手动管理。
cdn除非特殊需要，否则应该不更新只新增才对。

**Comment by sunylt** [comment]
是的，指望去更新cdn是没辙了，我也不想了。之后会做好模块的版本与对应版本更新的记录工作，然后交给后端读取了。谢谢了。本来是看了FIS考虑用ta的，但是seajs也用了好些时间了，就这个问题fis能解决，seajs总会也有好的办法的。
