### ISSUE TITLE
ie10下模块加载错误

### ISSUE THREAD

**Issue by ikun** [seajs/seajs#1531]
- 背景：

A、B两个页面中都use了两个模块x,y
这两个模块都依赖了a模块，而a模块又依赖a-1模块

- 浏览器环境：

IE10
版本:10.0.9200.17267
更新版本:10.0.25(KB3032359)
产品ID:00150-20000-00003-AA459

- 问题描述：

先访问页面A，再访问页面B的时候，页面B内use的2个模块都无法加载完毕

目前只在ie10下复现次现象

- bug demo

http://pan.baidu.com/s/1c0nSbAC

**Comment by nuintun** [comment]
脚本执行的时候DOM树还未构建完成，```document.body```还是```null```，
执行脚本放在```DOMContentLoad```后执行就可以了。或者将```sea.use```放在```body```标签最后面。
另外```use```可以简写成```sea.use(['./js/pa.js', './js/pb.js'])```。
