### ISSUE TITLE
seajs官方示例examples的自定义构建

### ISSUE THREAD

**Issue by pisse** [seajs/seajs#1533]
seajs官方示例标准构建很简单，
但是我npm spm一直不成功，一直报shasum check failed...错误。
所以尝试自定义构建，始终没能成功。
希望大牛给个示例。感谢！

**Comment by nuintun** [comment]
我这没用 ```spm``` 而是自己写了个 [gulp-sample](https://github.com/nuintun/gulp-sample)

1、下载示例
2、```npm i -g gulp-cli```
3、```npm i```
3、```gulp```

```gulp```命令有三个模式
```gulp``` 开发模式，只转换模块，不压缩合并
```gulp watch```监听模式，监听文件变换，自动构建，用于开发模式自动构建
```gulp product```生成环境，模块会进行合并和压缩

**Comment by pisse** [comment]
按照这个[seajs-grunt-build](https://github.com/twinstony/seajs-grunt-build)
自己试了一下，转换之后依赖路径是双斜线，如下所示：
```javascript
define("dist/static/todo/src/main-debug", [ "backbone-debug", "./views\\app-debug", "./views\\todos-debug", "./common-debug", "./collections\\todos-debug", "./models\\todo-debug", "./routers\\router-debug" ], function(require) {
    var Backbone = require("backbone-debug");
    var app = require("./views/app-debug");
    var Workspace = require("./routers/router-debug");
    new Workspace();
    Backbone.history.start();
    new app();
});
```

**Comment by nuintun** [comment]
那就是他工具的问题了
