### ISSUE TITLE
seajs.config里面配置有map参数时与seajs-combo插件一起用时会有问题

### ISSUE THREAD

**Issue by kangmingfei** [seajs/seajs#1536]
seajs.config里面配置有map参数时与seajs-combo插件一起用时，会导致??后面的每个链接都会加上版本号的bug，这样合并功能就失效了。除了修改seajs源码这种途径，想请教下有没有其它别的解决方案。

**Comment by army8735** [comment]
服务器端路由忽略呢？

**Comment by kangmingfei** [comment]
@army8735 服务器端做的话应该是可以解决。我最后修改了一行seajs的源码，发送请求之前正则过滤了一下中间的版本号

**Comment by shi2713** [comment]
碰到同样的问题，如果输出类似这样的拼接呢：
http://xxx.com/??a.js,b.js?v=20150814
有没有更好的解决方案？
