### ISSUE TITLE
打包压缩是先合并后压缩还是先压缩后合并？

### ISSUE THREAD

**Issue by nuintun** [seajs/seajs#1538]
如题：
 - 先合并后压缩便于整体压缩优化，但是每个模块可能都要被压缩很多次。
 - 先压缩后合并不利于整体优化，不过对于 ```common``` 模块来说并没什么影响，但是如果要生成 ```sourcemap``` 就麻烦了很多，优点就是打包速度很快，一个模块只要压缩一次就行了。

各位 ```JSer``` 用的哪种 或者 更倾向于哪种 :smiley:

**Comment by army8735** [comment]
打包时就应该去重

**Comment by nuintun** [comment]
打包时肯定会去重的，我说的重复压缩是这样的

有页面 A，B
调用入口脚本 A，B

A，B 脚本都依赖 C 脚本，这样先合并后压缩的时候 C 就会被压缩两次！

**Comment by army8735** [comment]
生产环境的构建工具需要这么苛求性能么……

**Comment by nuintun** [comment]
构建工具在不 ```live edit``` 的情况下不用苛求性能，不过快点总是好些 :grinning: 现在暂时用的先合并后压缩，在正常网站脚本量的情况下1分半左右还可以接受吧~
