### ISSUE TITLE
nodejs 和 browserify以及其他的js 框架有何不同

### ISSUE THREAD

**Issue by xianlin** [seajs/seajs#1540]
刚刚看seajs的文档，感觉和browserify的`require module`一样一样的，有何惊艳之处么？

也有人在stackoverflow上问了个问题，虽然不太对，但是你懂的，就是难道别的框架就没有用到`require module`来解决如何管理和组织javascript的文件么？
http://stackoverflow.com/questions/29062514/whats-the-difference-between-seajs-module-and-nodejs-module-definition

比如说`ampersandjs`，会和seajs有不同么？
https://ampersandjs.com/learn/npm-browserify-and-modules

谢谢！

**Comment by army8735** [comment]
实际都是在围绕这如何将commonjs浏览器化转
