### ISSUE TITLE
3.0.0 config配置的preload功能去掉了？

### ISSUE THREAD

**Issue by andyforever** [seajs/seajs#1542]
之前用的2.2.0版本，今天试着升级3.0.0，发现preload里的文件都没有加载
![1](https://cloud.githubusercontent.com/assets/3242791/8326808/5455a302-1a96-11e5-833d-2a77b7081948.png)

**Comment by army8735** [comment]
删掉了

**Comment by andyforever** [comment]
请问建议这部分怎么加载？标签还是seajs.use?

**Comment by army8735** [comment]
用标签吧，这个功能有点鸡肋其实，导航标签即可。

**Comment by andyforever** [comment]
get√ 
谢谢
