### ISSUE TITLE
请教合并教程

### ISSUE THREAD

**Issue by cxh80301983** [seajs/seajs#1543]
大家用的是  spm  还是 grunt 呢？
我查到的 spm build main.js --combine --app_url name  没成功

请教一下大家用的什么工具？

**Comment by LiXunGuan** [comment]
我在研究用grunt构建，但是遇到了个问题。提取依赖的时候只提取了第一个

**Comment by nuintun** [comment]
自己根据项目写更好使

https://github.com/nuintun/gulp-sample 不知道适合你不

**Comment by army8735** [comment]
一般情况下spm就够用了，除非有自己的定制需求。我觉得写个自己的构建工具也不是什么难事，只是个深度递归遍历+去重的合并逻辑。可能设计到一些映射的替换。提取依赖有专门的crequire可以用。
