### ISSUE TITLE
seajs 3.0 firefox esr 會導致瀏覽器假死，腳本停止響應

### ISSUE THREAD

**Issue by haozileung** [seajs/seajs#1545]

**Comment by army8735** [comment]
demo

**Comment by haozileung** [comment]
<script type="text/javascript" src="js/lib/seajs/sea.js"></script>
<script type="text/javascript" src="js/seajs-config.js"></script>

<script type="text/javascript">
    seajs.use("controller/main");
</script>

**Comment by haozileung** [comment]
同樣的代碼，用2.2.1版本沒有出現假死~

**Comment by army8735** [comment]
不要贴本地的，我怎么看……

**Comment by haozileung** [comment]
http://xajh.8888play.com/index_1.html

**Comment by army8735** [comment]
哪里出现假死了？正常打开了。

**Comment by haozileung** [comment]
Firefox ESR 31.7.0

**Comment by army8735** [comment]
#1516 
build一下试试，源码的话会即时分析依赖，某些浏览器下js引擎还未优化得很好

**Comment by haozileung** [comment]
瞭解~感謝~
