### ISSUE TITLE
seajs.use 函数的回调函数没有执行，remain 等于2 导致callback无法回调

### ISSUE THREAD

**Issue by jack833** [seajs/seajs#1548]
遇到一个偶发的问题，但是出现的频率比较高，使用的是3.0.0版本，seajs.use的回调函数不能执行的问题，
调试跟进 发现remain 最小值等于2 导致callback无法回调，这个是什么可能的原因导致？

```
Module.prototype.onload = function() {
  var mod = this
  mod.status = STATUS.LOADED

  // When sometimes cached in IE, exec will occur before onload, make sure len is an number
  for (var i = 0, len = (mod._entry || []).length; i < len; i++) {
    var entry = mod._entry[i]
    if (--entry.remain === 0) {
      entry.callback()
    }
  }

  delete mod._entry
}
```

希望能够给点思路好解决问题，谢谢！

BTW：
1、由于脚本比较复杂+外加公司的某些规定的，不能贴上源码和截图。请见谅。
2、有使用seajs-shim 插件。

**Comment by army8735** [comment]
有demo么

**Comment by jack833** [comment]
没有，代码在公司里面，在公司里面不能访问外网和上玩贴代码，很抱歉！

我先用jquery把JS加载回来，再require 就正常。但是用seajs.use的时候就没有回调，那个remain为2.不是每次都是2，多数情况下都可以正常回调。

另外，我将浏览器的缓存disable掉后，比较容易出现，刷新20次，就有3-4次的不正常，缓存打开后，很难重现。

请帮忙看看，有哪些场景可能会出现这种问题，谢谢！

PS，我在家也试试看能不能重现。

**Comment by jack833** [comment]
count++
        m._entry.push(entry)  // 这个地方，
        if(m.status === STATUS.LOADING) {
          m.pass()
        }

先count++， 再push到依赖module的_entry中，然后再这个依赖的模块如果在loading状态时，再pass，是不是会导致这个entry的remain被重复的多次的计数？

**Comment by army8735** [comment]
能提出个小例子吗？
这个逻辑最后有去重。
按理说test覆盖了很多异常情况，不重现很难找到真因。

**Comment by jack833** [comment]
周一到公司再看看能不能整个出来，现在在家里模拟不出来。

**Comment by freeskycn** [comment]
我发现使用3.0版本之后 在pc端本地访问html没有任何问题，但是在移动端访问就会出现不加载模块的情况。使用的是use。只要我在use之前操作一下dom元素就又可以加载了。就是第一次进去不加载。通过手机刷新的时候就正常了。

**Comment by jack833** [comment]
回退到2.2.3版本也不行，只好不用shim，手工加几个define包装shim。
不知道是不是shim插件的问题。

**Comment by army8735** [comment]
shim插件不是我写的，不太清楚……

**Comment by guohuihot** [comment]
我也遇到这个问题，和插件没关系

**Comment by anyhit** [comment]
这个问题我也遇到了。应该是seajs的bug。army兄 邮件给你qq邮箱了。麻烦帮忙看下

大概流程如下 
   a -> a1 ->a2
   b -> c -> a1 ->a2
   当a 加载成功后。去异步require 模块b。则c的回调函数无法正常执行
   我这边大概追了下代码。大概原因如下 a 加载完后。 a1 为loadding状态。a2 为loaded状态
   c 请求加载a1的时候，会增加 b的remain计数。但a2的onload方法一直不会执行。导致remain无法减下去

**Comment by anyhit** [comment]
已经确认2.2.3 版本没有改问题。但2.2.3 使用gulp压缩后。会有require失效的问题（怀疑是正则找require 关键字出的问题， 因为出问题的情况都是出现了特殊字符 /）
