### ISSUE TITLE
关于seajs的相对路径../的疑问

### ISSUE THREAD

**Issue by freeskycn** [seajs/seajs#1552]
在seajs的模块化下自己封装了一套组件。。测试代码也没问题。。但是到把组放到别的项目里面的时候，由于设置了base 导致引用出错。。原因貌似如下：

目录结构：
    -app
        -1001
            index.html
    -common
        -components
            -mobilechart
                -chart
                    line.js
                    bar.js
                    ...
                 charts.js

index.html 里面这样写：
    seajs.config({
         base:'../../',
         alias:{
            "charts":"common/components/mobilechart/charts"
        }
   });

seajs.use("charts",function() {});
这时候就会报错。。
原来我的mobilechart里面会引用到它目录里面的模块。。。存在很多../形式的引用。。。这时候如果设置了base属性。。则seajs会自动的拼接base和相对路径。。导致出错。。。请问有什么方法不拼../../.....这种形式的相对引用方式。。。

**Comment by memoryza** [comment]
这个base你写成针对于网站根目录的路径

**Comment by guohuihot** [comment]
和我的问题一样https://github.com/seajs/seajs/issues/1638
