### ISSUE TITLE
spm3有没有压缩合并css功能？官网资料少的可怜啊，如果有，要如何操作？

### ISSUE THREAD

**Issue by adhehe** [seajs/seajs#1553]
JS压缩合并实现了，但是这个css就是不行，请教达人们，谢谢！

**Comment by ppq1991** [comment]
这个用gulp就行吧，gulp-concat，gulp-minify-css。

**Comment by adhehe** [comment]
gulp是行，就是感觉开发个项目，合并js和css还得用两个工具太麻烦了

**Comment by sorrycc** [comment]
spm3 可以的。说下你的操作步骤，我看下是哪里出问题了。

**Comment by memoryza** [comment]
grunt、gulp css-min这类的都可以实现的

**Comment by adhehe** [comment]
原来我是发在这里的，可惜没人回答
http://segmentfault.com/q/1010000002960420

**Comment by sorrycc** [comment]
是个 windows 系统下的 bug，记录到这了。https://github.com/spmjs/spm/issues/1343

--

下次到这里提问吧：https://github.com/spmjs/spm/issues

**Comment by adhehe** [comment]
感谢回复！现在暂时使用gulp来操作，期待完善。

在 2015-07-10 17:28:04，"chencheng (云谦)" <notifications@github.com> 写道：


是个 windows 系统下的 bug，记录到这了。spmjs/spm#1343

下次到这里提问吧：https://github.com/spmjs/spm/issues
