### ISSUE TITLE
Build 和 Loader 完全是两回事，不要在本地打包seajs？

### ISSUE THREAD

**Issue by nimojs** [seajs/seajs#1557]
**我觉得使用者将seajs 和 spm3没有弄清楚时很容易踩进大坑**，所以开这个 issues 想跟大家一起讨论下本地构建和 seajs 的使用建议。

官网的介绍一直是
```
A Module Loader for the Web
```
社区一直有打包的需求。官方推荐的打包方式是 spm。

起初 spm 是为 seajs 服务的，而现在 spm3 已经与seajs "划清界限"了。

> spm3 在本地打包任何前端资源

> seajs 通过运行时分析依赖加载资源

----

我 seajs 用的很舒服，因为我基于 [seajs-combo](https://github.com/seajs/seajs-combo/issues/3) 让服务器打包js,而不是本地构建。这样只需要维护自己团队的 CMD库 [seajs-cmd](https://github.com/nimojs/seajs-cmd)。对于开发人员来说完全不需要考虑打包的事。

因为我将 seajs 理解为 **A Module Loader for the Web**。这样做也有缺点，比如并不能做到一个页面只加载一个js,如果存在多级依赖会增加几个 JS请求。

---

既然 spm 可以在本地打包任何前端静态资源，那么就用 spm 直接打包。而不将 seajs 与 spm 混用。

spm 不再是 seajs 配套的构建工具，而是一个静态资源生态环境，类似 NPM 。(其实 spm 的作者们早就在说这一点了)

---

seajs 基于 spm 的生态环境获取 cmd 版本的模块，使用 seajs-combo 完成打包。我觉得这是 seajs 最合适的用法。

如果想做到极致的打包，就只使用 spm 吧。

@army8735 @afc163  @sorrycc

**Comment by army8735** [comment]
就是说推荐在本地搞好一切打包的过程。可以脱离seajs。

如果业务中用到动态加载的话，那么就必须seajs了。

**Comment by afc163** [comment]
seajs 的配套工具现在应该是 [spm-sea](https://github.com/spmjs/spm-sea)，它可以负责 CMD 模块的依赖提取和构建。

spm 3.6 之后基于 webpack，和 seajs 早已无任何联系。

**Comment by lichunqiang** [comment]
把seajs忘记吧
