### ISSUE TITLE
seajs配置中的map问题

### ISSUE THREAD

**Issue by xinglie** [seajs/seajs#1558]
问题描述如下：
目录app下有一个default.js

```js
define('app/default',function(){

});
```

配置文件config.js
```js
seajs.config({
   paths:{
     app:'path/to/app'
   }
});
```
出于某种原因，我需要在页面中直接引入default.js如下

```html

<script src="path/to/seajs"></script>
<script src="path/to/app/default.js"></script>
<script src="path/to/config.js"></script>
```

到目前一切正常。
如果我在config文件中增加map的配置：

map:[['.js','-min.js']]之后。

我在另外的js文件中依赖或使用app/default的时候，seajs动态的去加载app/default-min.js。完全忽略掉我页面上本身就放了的app/default.js。

我不理解是：页面上已经放了app/default.js，里面直接调用define函数，已经告诉seajs定义了app/default模块，为什么多了map配置后，还要去获取-min文件？难道不是先看是否已经定义了这个模块，然后使用即可？

**Comment by army8735** [comment]
因为map的映射逻辑在path之后。这两步都要走一遍，可以在map中配置function来自定义过滤。

**Comment by xinglie** [comment]
@army8735 感谢回复，是我弄错了，我应该把配置文件放到app/default.js这个文件前面。否则define时配置还不存在，导致路径不对。见笑了。
