### ISSUE TITLE
使用seajs.use加载js时,如果要加载的js地址不对返回404异常,要等很久才抛出异常

### ISSUE THREAD

**Issue by geekv** [seajs/seajs#1561]
如题所示.
有没有哪个设置,让等待的时间可配置,比如说我设置好了,这个模块的js,如果3秒没down下来,就不去加载了 ,同时抛出异常什么的

**Comment by army8735** [comment]
没这功能。。。

**Comment by geekv** [comment]
你想一下,一般我们如果引用了一个错误的js地址,浏览器马上就会识别出来,同时抛出network异常;而用seajs加载的js则要足足等待20秒才会抛出异常,然后浏览器在这段时间内就会一直处于加载中状态,然后我写在window.onload里面事件和方法就要等待20秒后才会执行;基于此,我觉得不正常

**Comment by army8735** [comment]
应该不是404吧，你的请求估计是很慢，404是立刻报错的。

你的需求应该是，低网速情况下，某个请求hold了很长的时间，这个应不应该加个超时功能？

着急的话可以自己在request时开个timestart，回调timeend做一下，这个功能加有点犹豫。

window.onload应该是document.ready吧。

**Comment by geekv** [comment]
document.ready暂时倒是能解决问题...
看到有人这样用 
seajs.config({
　　base: 'path/to/jslib/',
　　alias: {
       　　'app': 'path/to/app/'
　　},
　　charset: 'utf-8',
　　timeout: 20000,
　　debug: false
});

里面有个timeout参数,表示下载文件的最大时长，以毫秒为单位。   事实上似乎没有什么用,这是老版本的吧

**Comment by army8735** [comment]
没啥印象，很老的版本的话就不清楚了。。
