### ISSUE TITLE
把压缩的后的seajs，格式化后，使用不了。

### ISSUE THREAD

**Issue by shupan** [seajs/seajs#1563]
为什么压缩的seajs可以使用。而格式化后就会报语法错误。

![image](https://cloud.githubusercontent.com/assets/9160070/8926073/75ce691a-353f-11e5-97cb-7c6ff13e43f3.png)

**Comment by shupan** [comment]
![image](https://cloud.githubusercontent.com/assets/9160070/8926085/8b153902-353f-11e5-908a-cc3fa47f5d87.png)

**Comment by army8735** [comment]
压缩问题吧，正则压缩成注释了。而且有压缩好的版本。

**Comment by shupan** [comment]
麻烦发一下压缩好的版本路径~

**Comment by army8735** [comment]
npm i之后能找到非-debug结尾的就是压缩版本，https://github.com/seajs/seajs/releases 压缩包里也有
