### ISSUE TITLE
Jquery 2.1.4支持CMD吗

### ISSUE THREAD

**Issue by ZimmerHao** [seajs/seajs#1581]
各位，是不是Jquery2.1.4还不支持CMD?

**Comment by army8735** [comment]
得自己改造

**Comment by ZimmerHao** [comment]
我准备用django+backbone+seajs，我试了examples里的例子（没有问题），我把依赖都换成examples里的，发现requeire后，backbone还是为undefined。感觉好奇怪。
index.html：
<script>
      // Set configuration
      seajs.config({
        base: "{% static "" %}",
        alias: {
          "$": "components/jquery/dist/jquery.js",
          "underscore": "components/underscore/underscore.js",
          "backbone": "components/backbone/backbone.js"
        }
      });
      // 加载入口模块
      seajs.use("{% static "src/js/main" %}");
    </script>

main.js：
define(function(require){

    var Backbone = require('backbone');
    alert(Backbone);
    var AppRouter = require('./routers/router');
    new AppRouter();
    Backbone.history.start();

});
我看到seajs，backbone，jquery，underscore的确都加载下来了，但是就是不可以require。

**Comment by army8735** [comment]
#930 
匹配上就能require到了

**Comment by ZimmerHao** [comment]
谢谢，另外想问一下用gulp来构建有什么插件吗，例如grunt-cmd-transport，grunt-cmd-concat
