### ISSUE TITLE
请问是否可以使用seaJS对React项目进行包管理?

### ISSUE THREAD

**Issue by astwyg** [seajs/seajs#1586]
我们希望在项目中使用React, 调试开发阶段不希望使用gulp或者webpack打包, 所以需要处理问题有二:
1. jsx语法转移.
2. 对js(x)文件的包管理.

第一个问题可以通过React自带的JSXtransform.js解决, 请问: seaJS能否解决第二个问题, 使React项目可以在前端不打包运行?

我们进行过一些搜索, 但是没有发现这方面的尝试, 如大家有经验, 请分享. 
十分感谢!

**Comment by army8735** [comment]
可以，本身jsx就是翻译为js运行的

**Comment by astwyg** [comment]
@army8735  有没有可以直接运行的工程或者项目分享参考一下?

十分感谢!

**Comment by liaolunhui** [comment]
@army8735 公司的项目刚刚用上SEAJS，配置base目录为/sea-module，以前还有很多未模块化的文件在其他目录，比如js/abc.js，也可以seajs.use('/js/abc.js')方式引入，这样异步引入其他东西可以先显示，非常不错，但是console.log(123)出来的东西显示123 VM4352 abc.js，而且每次VM后面的数字都不一样。这样就无法在chrome浏览器里断点调试+关联文件系统保存。放在/sea-module目录下又没有VM，可以断点调试+关联文件保存。但是项目很多其他JS文件，不敢一下子全部转移到sea-module，如何保留在原来目录实现断点调试+关联文件系统保存？

**Comment by army8735** [comment]
没有可以分享的项目……

断点可以的吧，那个随机数是因为整个文件被认为是个非cmd模块，use时候回调封装了个匿名模块导致。原始文件里可以加debugger不行吗？

**Comment by popomore** [comment]
react 的项目个人不建议使用 seajs，可以参考下 http://ant.design/

Army <notifications@github.com>于2015年9月15日周二 下午7:11写道：

**Comment by astwyg** [comment]
@popomore  非常给力! 我们现在在做的就是这样一个东西, 这个项目有非常多的宝贵经验可以参考!

**Comment by liaolunhui** [comment]
原始文件也无法debug，必须放入sea-module才能debug+关联保存，求解决方案。

**Comment by liaolunhui** [comment]
@army8735 原始文件也无法debug，必须放入sea-module才能debug+关联保存，求解决方案。
