### ISSUE TITLE
模块依赖关系解析错误

### ISSUE THREAD

**Issue by nichengaxiang** [seajs/seajs#1606]
模块的代码如下：
define(function (require,exports,module){function a(a){1000/32}var b=require("a"),d="a/b"});
上述代码只有一行，是压缩之后的代码，工厂函数在执行时，当前模块的依赖模块数量为 0，变量 b 的值为 null。

结合 seajs 源码，分析问题如下：
有问题的依赖解析代码：
'function (require,exports,module){function a(a){1000/32}var b=require("a"),d="a/b"}'.replace(/\\\\/g, "").replace(/"(?:\\"|[^"])*"|'(?:\\'|[^'])*'|\/\*[\S\s]*?\*\/|\/(?:\\\/|[^\/\r\n])+\/(?=[^\/])|\/\/.*|\.\s*require|(?:^|[^$])\brequire\s*\(\s*(["'])(.+?)\1\s*\)/g, function (m, m1, m2) {
    console.log(m2)
    if (m2) {
        ret.push(m2)
    }
})
	  
	  
没有问题的依赖解析代码：
'function (require,exports,module){function a(a){100032}var b=require("a"),d="a/b"}'.replace(/\\\\/g, "").replace(/"(?:\\"|[^"])*"|'(?:\\'|[^'])*'|\/\*[\S\s]*?\*\/|\/(?:\\\/|[^\/\r\n])+\/(?=[^\/])|\/\/.*|\.\s*require|(?:^|[^$])\brequire\s*\(\s*(["'])(.+?)\1\s*\)/g, function (m, m1, m2) {
    console.log(m2)
    if (m2) {
        ret.push(m2)
    }
})

上述依赖解析的源码取自 seajs~2.3.0 版本。

**Comment by army8735** [comment]
正则分析是偶尔会出现极端情况不准确的……

**Comment by nichengaxiang** [comment]
这种极端情况，能否在后续版本中解决呢？我这边这种问题出现概率较高。

**Comment by afc163** [comment]
https://github.com/seajs/seajs/issues/426

https://github.com/seajs/seajs/issues/478

**Comment by nichengaxiang** [comment]
我这边目前使用 grunt 来构建线上代码，我换成 spm 试下。
