### ISSUE TITLE
请问目前有没有Seajs迁移到webpack项目的解决方案？

### ISSUE THREAD

**Issue by andyforever** [seajs/seajs#1609]
@lifesinger @afc163 @army8735 
No 欣喜若狂，No大失所望。咱们坐下来谈谈，有没有一个当前seajs项目可以迁移到webpack的解决方案？

**Comment by hxgdzyuyi** [comment]
+ 1

**Comment by afc163** [comment]
http://webpack.github.io/docs/amd.html#using-require-to-load-dependencies

**Comment by hxgdzyuyi** [comment]
@afc163 seajs 自己好像还有一些插件 比如 seajs-text 什么的。

**Comment by kmvan** [comment]
我刚好这几天在重构，从seajs2webpack，累得我。。。

**Comment by andyforever** [comment]
@kmvan 打算这样改，工作量在哪？求教
