### ISSUE TITLE
The question is undefined about "$".

### ISSUE THREAD

**Issue by chomyeong** [seajs/seajs#1620]
Hi,friend!
I have a question,took a look at code below:
 seajs.use(['zepto','frozen','layzr','{:ADDON_PUBLIC_PATH}/js/Course'],function(Zepto,frozen,layzr,course){
        console.log(Zepto);
        course.init();
    });

Why is "Zepto" undefined?

**Comment by saury** [comment]
open your browser's console to check if your zepto.js is loaded

**Comment by chomyeong** [comment]
Thanks friend,I have resolved this question.
