### ISSUE TITLE
求助在seajs.config添加了paths后如何正确构建打包

### ISSUE THREAD

**Issue by saury** [seajs/seajs#1628]
例子如下：
  seajs.config({
        base: "./sea-modules/",
        paths: {
            'bs': './depends/bootstrap'
        },
        alias: {
            "$": "jquery.js"
        },
    });
这样在seajs.config加入paths设定后，用spm（3实在有点看不懂，用的2.X）构建打包模块，尽管没有报错，但并没有顺利打包成功，看了下输出文件，并没有解析到seajs.config中预设的路径，搜了issue（似乎有人提过，但没人回答），百度，so，谷歌，似乎没有见到如何解决的方案，求菊苣们指点如何配置

**Comment by fedwatch** [comment]
用spm
