### ISSUE TITLE
seajs配套的构建工具SPM倒下了，请问现在使用什么工具打包构建呢？

### ISSUE THREAD

**Issue by NeFx** [seajs/seajs#1663]
seajs配套的构建工具SPM倒下了，请问现在使用什么工具打包构建呢？有相关的demo吗？

**Comment by vrbvillor** [comment]
我现在用自己研究的部署方案，都用PHP压的，不过依赖时遇到问题，实名里边require匿名的，路径对，文件对，就是返回NULL，无解，问题提出三四天了，到现在也没有人回答。

**Comment by kidney** [comment]
@victoryboss grunt-cmd-transport + grunt-cmd-concat，或者转用webpack

**Comment by kbqncf** [comment]
转用webpack吧

**Comment by gafish** [comment]
直接用webpack，兼容cmd规范

**Comment by NeFx** [comment]
谢谢！
