### ISSUE TITLE
咨询：请问seajs有没有像Angularjs那样的数据双向绑定功能？

### ISSUE THREAD

**Issue by Metoyo** [seajs/seajs#1664]
请问seajs有没有像Angularjs那样的数据双向绑定功能，谢谢！

**Comment by army8735** [comment]
这2个不是同一种东西，seajs只是模块管理器，不是mvvm之类的。

**Comment by zhazhage** [comment]
@army8735  同意。 @Metoyo 你最好明白构建工具和mvvm框架的区别。
总结
**这丫完全就是两个东西，他们的关系就好像是雷锋和雷锋塔一样。**
