### ISSUE TITLE
sejs开发团队是不是有点不负责任啊

### ISSUE THREAD

**Issue by thomas2010** [seajs/seajs#1675]
两年前曾经研究过seajs，那时感觉挺火的，各方都宣传如何如何好，在知乎上还有跟其他同类型插件的比较文章，看得我一时热血沸腾啊，怎么说也得支持下国货啊，国产开源这块做的实在不咋的，我辈再不多支持怎么会有更好的发展呢，更何况还是阿里出品。可惜那时候工作出了点状况，改做其他项目了，没用到，更种子已经埋下。

最近重新开始做两年前的那个项目，由于期间电脑换过，环境需要重新搭建。
时间太久，之前的知识也已模糊，就把官方文档重新看了下。
seajs脚本写了测了也没问题，现在有进行压缩合并了，安装官方推荐安装spm3，真是各种坑啊
其实最大问题就是压缩合并后根本没法用啊。
百度了下，据说spm已经倒下了，我不清楚spm开发团队跟sesjs开发团队是什么关系，
不论什么关系，seajs开发团队也应该发个公告说明下吧。
继续用spm的话请说明具体怎么用，demo也该更新上啊
如果不行或者说seajs也倒下了，也公告下啊
不要浪费了广大码农的一腔热血跟时间啊

**Comment by afc163** [comment]
https://github.com/seajs/seajs/issues/1605

**Comment by thomas2010** [comment]
@afc163 没想到你还在啊
其实都怪自己这两年没怎么学习、关注前端技术
不过还是建议你们能不能在首页做个不维护说明呢
另外个人认为seajs在某些场景下还是有应用价值的，目前就缺了个打包插件
ES6真正应用我想还需要较长时间吧，
Webpack我刚了解了下，似乎就是一个打包工具，主要加了ES6转ES5功能，在目前阶段还是直接写ES5的人多吧（也许是我孤陋寡闻了），如果ES5还是主流，那何必着急使用ES6呢，特别是对已一个已成熟稳定的团队跟产品，贸然引入新的技术会带来很多问题

**Comment by afc163** [comment]
ES6 现在已经是主流了，很快 ES7 就出来了。

**Comment by thomas2010** [comment]
@afc163 
看来是跟不上了
像我这种产品面向传统企业的团队，大多用户使用的还是IE8，团队里还没有专职前端开发人员的
好难选择用ES6啊
