### ISSUE TITLE
怎么样同步加载，今天做Demo遇到的问题，Google很久也没有答案，多谢解答。

### ISSUE THREAD

**Issue by rockjins** [seajs/seajs#1677]
今天用React做一个Demo，我在index.html的script标签内用`seajs.use('lib/react-dom')`语句请求这个react-dom文件，然后在这条语句下面引入入口模块`seajs.use('js/Layout')`，结果发现Layout比react-dom先加载进来。
因为Layout要用到react-dom中的功能，导致页面无法运行，我又在Layout中用`ReactDOM=require('../lib/react-dom')`去请求依赖，结果react-dom文件中没有module.export设置，导致ReactDOM是一个错误的对象。
所以我想问问大伙，Seajs又没有可以同步加载文件的方法，这个加载结束，下个才能开始。
多谢！

**Comment by suyuTech** [comment]
难道不是在seajs.use的第一个参数中先加载依赖嘛

**Comment by afc163** [comment]
```html
<script src="1.js"></script>
<script src="2.js"></script>
```

**Comment by rockjins** [comment]
的确，试了下用'<script src="1.js"></script>
<script src="2.js"></script>`确实没问题，但是我把react-dom放在seajs.use第一个参数中加载，后面的Layout放在他的回调里，网速快没问题，但是网速慢还是会显示ReactDOM.undefined，只有用标签引入这一种方法吗

**Comment by rockjins** [comment]
的确，试了下用
```
<script src="1.js"></script>
<script src="2.js"></script>
```
确实没问题，但是我把react-dom放在seajs.use第一个参数中加载，后面的Layout放在他的回调里，网速快没问题，但是网速慢还是会显示ReactDOM.undefined，只有用标签引入这一种方法吗

**Comment by afc163** [comment]
https://github.com/seajs/seajs/issues/1379
