### ISSUE TITLE
调用自己定义的saveData()方法，chrome console提示“Uncaught TypeError: Cannot read property 'saveData' of null”

### ISSUE THREAD

**Issue by zhoubhin** [seajs/seajs#1679]
我在base.js里定义了saveDate()方法：`    var T = {
        'sid': (function () {
            return storage.getItem('sid');
        })(),
    };
...
module.exports = T;
`
在login.js里调用saveData()方法：`base.saveData('sid', data.datas[0].sessionUuid);`，chrome console提示

> login.js:38 Uncaught TypeError: Cannot read property 'saveData' of null

**Comment by zhazhage** [comment]
问题都说不清楚 没有人可以帮你i的

**Comment by zhoubhin** [comment]
@zhazhage  后来发现是引用base.js的路径不正确，导致不能调用base.js里的方法
