### ISSUE TITLE
纯属瞎扯淡！

### ISSUE THREAD

**Issue by xgqfrms-GitHub** [seajs/seajs#1695]
<quoteblock>两者代码质量有差异。RequireJS 是没有明显的 bug，SeaJS 是明显没有 bug。</quoteblock>
纯属瞎扯淡！是程序都存在bug,只是你还没有发现而已！
摆脱长的常识好不好，不要再这里瞎误导！

**Comment by afc163** [comment]
有时间吐槽五年前的一句推广语，不如花时间看看 ES2015。

**Comment by differui** [comment]
当年看到这句话就是觉得挺好玩。
