### ISSUE TITLE
求思路：SeaJS and Unit Test，基于SeaJS的项目如何做单元测试？

### ISSUE THREAD

**Issue by ChrisShen93** [seajs/seajs#1696]
我的Java web前端基于SeaJS，也使用到了jQuery。现在想把单元测试加上。请问该怎么做？包括使用哪些测试工具、框架。。
Asking for help, that how I can add unit test to my Java Web project whose front end is based on seajs?
Just tell me which framework I should use. I am a fresh man in IT.
Thanks in advance.

**Comment by Zzzen** [comment]
https://www.cnblogs.com/SCOOL/p/4372090.html

**Comment by ChrisShen93** [comment]
> https://www.cnblogs.com/SCOOL/p/4372090.html

thanks a lot
