### ISSUE TITLE
我能配置让他不缓存么？

### ISSUE THREAD

**Issue by godtoy** [seajs/seajs#1718]
我能配置让他不缓存么？由于我正在升级一套系统，用了seajs，手机上我没办法强制刷新，seajs拿到的可能是一个缓存没有更新的代码 。我项配置一下 例如  demo.js?v=123123

**Comment by YeChuan-Xing** [comment]
我也尝试了几种
```
seajs.config({
  'map': [
    [ /^(.*\.(?:css|js))(.*)$/i, '$'+new Date().getTime() ]
  ]
});

``
放放貌似还会引发其它bug。
希望作者能够对这个地方引起重视。

**Comment by fenglinzeng** [comment]
我是这么写的，一直没遇到问题。
var version = '2020042401';
seajs.config({
    ...
    map: [
        [".js", ".js?" + version],
        [".css", ".css?" + version],
    ],
    ...
});
