### ISSUE TITLE
Fix simple typo: themeselves -> themselves

### ISSUE THREAD

**Issue by timgates42** [seajs/seajs#1749]
# Issue Type

[x] Bug (Typo)

# Steps to Replicate

1. Examine tests/specs/util/events.js.
2. Search for `themeselves`.

# Expected Behaviour

1. Should read `themselves`.

**Comment by gt333** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
