### ISSUE TITLE
X-UA-Compatible bug

### ISSUE THREAD

**Issue by lifesinger** [seajs/seajs#185]
ytzong ytzong
SeaJS 的 bug，后加载的 js 被插在了 head 的最前边，这样会导致 X-UA-Compatible 失效 http://bit.ly/J7S2MG @lifesinger

**Comment by PetersonLian** [comment]
@dotnil 想来，这个BUG是针对IE8的X-UA-Compatible而做的处理。所以，应该默认是有个相关性。即，IE8使用了X-UA-Compatible之后，使用seajs，为了不导致出现X-UA-Compatible引起的BUG，需要显示地添加一个base元素，配合seajs一起使用。
应该是有这么个逻辑在里头。
