### ISSUE TITLE
模块系统

### ISSUE THREAD

**Issue by lifesinger** [seajs/seajs#240]
## 什么是系统

在生活和工作中，我们会接触到大量系统：自然界生态系统、计算机操作系统、软件办公系统，还有教育系统、金融系统、网络系统、理论系统等等。究竟什么是系统呢？

来看下维基百科的解释：

> 系统泛指由一群有关连的个体组成，根据预先编排好的规则工作，能完成个别元件不能单独完成的工作的群体。系统分为自然系统与人为系统两大类。

简言之，系统有两个基本特性：
1. 系统由个体组成。
2. 个体之间有关连，按照规则协同完成任务。

系统中的个体可称之为系统成员，这样，要构建一个系统，最基本层面需要做两件事：
1. <strong>定义系统成员</strong>：确定成员是什么。
2. <strong>约定系统通讯</strong>：确定成员之间如何交互，遵循的规则是什么。

只要把这两个问题描述清楚，我们就可以构建出系统。
## 模块系统

Sea.js 是一个适用于 Web 浏览器端的模块加载器。在 Sea.js 里，一切皆是模块，所有模块协同构建成模块系统。Sea.js 首要要解决的是模块系统的基本问题：
1. 模块是什么？
2. 模块之间如何交互？

在前端开发领域，一个模块，可以是JS 模块，也可以是 CSS 模块，或是 Template 等模块。在 Sea.js 里，我们专注于 JS 模块（其他类型的模块可以转换为 JS 模块）：
1. 模块是一段 JavaScript 代码，具有统一的基本书写格式。
2. 模块之间通过基本交互规则，能彼此引用，协同工作。

把上面两点中提及的基本书写格式和基本交互规则描述清楚，就能构建出一个模块系统。对书写格式和交互规则的详细描述，就是模块定义规范（Module Definition Specification）。比如 CommonJS 社区的 [Modules 1.1.1](http://wiki.commonjs.org/wiki/Modules) 规范，以及 NodeJS 的 [Modules](http://nodejs.org/api/modules.html) 规范，还有 RequireJS 提出的 [AMD](https://github.com/amdjs/amdjs-api/wiki/AMD) 规范等等。

Sea.js 遵循的是 [CMD](https://github.com/cmdjs/specification/blob/master/draft/module.md) 规范，会在接下来的文档中详细阐述。
## 延伸阅读
- [function / bind 的救赎](http://blog.csdn.net/myan/article/details/5928531)
- [继承与混合，略谈系统的构建方式](http://blog.csdn.net/aimingoo/article/details/6062997)

**Comment by 1129778586** [comment]
看了3天才入门。。

**Comment by lizzie** [comment]
@1129778586 好吧。如果跟你说这都快过时了，会打击你更多么？:sob:

**Comment by beckgoal23** [comment]
支持支持

**Comment by janryWang** [comment]
@beckgoal23 看看我的kvm吧，简单，强大https://github.com/janryWang/kvm

**Comment by selenium888** [comment]
订单

**Comment by JamesSky** [comment]
开始使用中...

**Comment by wangguozheng** [comment]
还是没搞明白啊，如何搭建环境啊，没有更详细的入门讲解吗？

**Comment by ianguyue** [comment]
没搞明白define(function(require,exports,module){
   var a = require('./jquery')
})
与
seajs.config({
    base: "../sea-modules/",
    alias: {
      "jquery": "jquery/jquery/1.10.1/jquery.js"
    }
  });
中  require('./jquery')   与 alias: { "jquery": "jquery/jquery/1.10.1/jquery.js"}  这两者有什么关系

**Comment by ChristopherMa2012** [comment]
@ianguyue jquery是“jquery/jquery/1.10.1/jquery.js”这一大串的别名

**Comment by clywind** [comment]
50天都没入门，血奔。。。

**Comment by jiajinning** [comment]
一天了都还没有入门，云里雾里哈！这都是给高手看的

**Comment by JackieDark** [comment]
这个确实挺好的，个人感觉比requireJs更适合模块化开发的新手。

**Comment by liuch0228** [comment]
看到有人评论3天才入门，我就放心了。。。五分钟入门，那是对高手来说的~

**Comment by kimmieIS** [comment]
我就想问问这个现在还有人在用seajs嘛，公司新开的项目要用这个来开发，我……

**Comment by chenxuyaun** [comment]
大神，我想请问一下，我bootstrap-table怎么使用

**Comment by chenqiang19910904** [comment]
mark

**Comment by Huanglei2010** [comment]
mark

**Comment by Winsist** [comment]
证明我来过~心累，一个很早之前的项目现在加功能了，之前用这个写的，我现在接手了，心累

**Comment by Zzs2016** [comment]
打卡，维护老项目要啃远古代码了。

**Comment by angelaQoQ** [comment]
sea  + vue 才 骚....
