### ISSUE TITLE
require 书写约定

### ISSUE THREAD

**Issue by lifesinger** [seajs/seajs#259]
# require 书写约定

使用 Sea.js 书写模块代码时，需要遵循一些简单规则。

> 只是书写和调试时的规范！！！构建后的代码完全不需要遵循下面的约定！！！！！！
### 1. 正确拼写

模块 factory 构造方法的第一个参数 **必须** 命名为 `require` 。

``` js
// 错误！
define(function(req) {
  // ...
});

// 正确！
define(function(require) {
  // ...
});
```
### 2. 不要修改

不要重命名 `require` 函数，或在任何作用域中给 `require` 重新赋值。

``` js
// 错误 - 重命名 "require"！
var req = require, mod = req("./mod");

// 错误 - 重定义 "require"!
require = function() {};

// 错误 - 重定义 "require" 为函数参数！
function F(require) {}

// 错误 - 在内嵌作用域内重定义了 "require"！
function F() {
  var require = function() {};
}
```
### 3. 使用直接量

`require` 的参数值 **必须** 是字符串直接量。

``` js
// 错误！
require(myModule);

// 错误！
require("my-" + "module");

// 错误！
require("MY-MODULE".toLowerCase());

// 正确！
require("my-module");
```

在书写模块代码时，必须遵循这些规则。其实只要把 `require` **看做是语法关键字** 就好啦。
## 关于动态依赖

有时会希望可以使用 `require` 来进行条件加载：

``` js
if (todayIsWeekend)
  require("play");
else
  require("work");
```

但请牢记，从静态分析的角度来看，这个模块同时依赖 play 和 work 两个模块，加载器会把这两个模块文件都下载下来。 这种情况下，推荐使用 `require.async` 来进行条件加载。
## Why?

这些约定初看起来会有些小不爽，其实也的确可以通过每次都编译的方式来去掉这些限制。但编译的方式，会给开发调试带来麻烦，代码的实现复杂度也会增加。Sea.js 的核心设计原则是保持简单，遵循 [New Jersey Approach](http://blog.jobbole.com/19062/)：

> 简单性：设计必须简单，这既是对实现的要求，也是对接口的要求。实现的简单要比接口的简单更加重要。简单是设计中需要第一重视的因素。

因为简单，所以可靠！
## 参考文档
- [为什么要用构建工具来压缩 CMD 模块](https://github.com/seajs/seajs/issues/426)

**Comment by meiyouqing** [comment]
define("base/easing/1.3.0/easing", ["jquery"], function(require) {
  var jQuery = require("jquery"); 
})
请问为什么浏览器提示“jQuery”是null了？路径都没有错，jquery也顺利加载了

**Comment by helloqinqin** [comment]
我的代码是这样的
require('charts/component/colorFac');
var color = new gradientColor('#013548','#554851',10);

colorFac文件为  (这个文件在网上找的)
(function(win){
  'use strict';
   /*渐变颜色
    // 作者 yanue
    // 参数：
    // startColor：开始颜色hex
    // endColor：结束颜色hex
    // step:几个阶级（几步）
   */
   function gradientColor(startColor,endColor,step){
       startRGB = gradientColor.colorRgb(startColor);//转换为rgb数组模式
       startR = startRGB[0];
       startG = startRGB[1];
       startB = startRGB[2];

       endRGB = gradientColor.colorRgb(endColor);
       endR = endRGB[0];
       endG = endRGB[1];
       endB = endRGB[2];

       sR = (endR-startR)/step;//总差值
       sG = (endG-startG)/step;
       sB = (endB-startB)/step;

       var colorArr = [];
       for(var i=0;i<step;i++){
           //计算每一步的hex值 
           var hex = gradientColor.colorHex('rgb('+parseInt((sR*i+startR))+','+parseInt((sG*i+startG))+','+parseInt((sB*i+startB))+')');
           colorArr.push(hex);
       }
       return colorArr;
   }

   // 将hex表示方式转换为rgb表示方式(这里返回rgb数组模式)
   gradientColor.prototype.colorRgb = function(sColor){
       var reg = /^#([0-9a-fA-f]{3}|[0-9a-fA-f]{6})$/;
       var sColors = sColor.toLowerCase();
       if(sColors && reg.test(sColors)){
           if(sColors.length === 4){
               var sColorNew = "#";
               for(var i=1; i<4; i+=1){
                   sColorNew += sColors.slice(i,i+1).concat(sColors.slice(i,i+1));
               }
               sColors = sColorNew;
           }
           //处理六位的颜色值
           var sColorChange = [];
           for(var s=1; s<7; s+=2){
               sColorChange.push(parseInt("0x"+sColors.slice(s,s+2)));
           }
           return sColorChange;
       }else{
           return sColors;
       }
   };
.....
})(window);


然后总是报错，gradientColor is not defined。我不清楚这是什么原因，看着colorFac.js文件已经加载了~~

我想知道这是为啥呢？难道colorFac非得按照seajs的写法写？还是new的时候，colorFac.js文件没加载？

**Comment by zlstone** [comment]
@helloqinqin  一般不会有这种情况发生，gradientColor is not defined说明全局肯定没有这个类存在，你得先确定库文件内部对外的接口是如何处理的，可能是进行过模块化的兼容，试试gradientColor=require('charts/component/colorFac');获取文件对外的api。还不行的话，确认一下gradientColor类名是否正确

**Comment by helloqinqin** [comment]
@zlstone
首先谢谢了~
1.确定及肯定名字没错~
2.gradientColor=require('charts/component/colorFac'); 断点，gradientColor为空
3.从sources可以看到colorFac.js是加载了的

不过没有对colorFac.js用defined模块化。我想着，这个也不能强制要那么写的

**Comment by zlstone** [comment]
@helloqinqin 不需要强制写，至少我用的2.1.0不需要，还是文件本身的问题，如果确定加载成功，全局没有，看看文件代码吧...

**Comment by helloqinqin** [comment]
@zlstone  
1.我按照define进行模块化了，并且把colorFac.js中的gradientColor方法前面的g大写了，然后就能行了~

2.我又把colorFac.js按照原来的，并且把gradientColor方法前面的g大写了，还是不行

我的seajs是2.3.0  具体什么原因还得多做实验，才能得出啊

**Comment by zhs23** [comment]
这种是不是以后加反射来处理了

**Comment by DennisEllen** [comment]
用$=require('jquery')时，为什么alert($)返回的是null

**Comment by tbx19930222** [comment]
希望有大牛帮我解答一下，为什么在safari浏览器下http://www.51go.me/加载的这么慢，是seajs的原因吗，有几个js我是require进来的

**Comment by xxiiaass** [comment]
第一个参数'require'，在压缩时候会改名，导致无法正常执行，有什么好的办法吗

**Comment by virtuecai** [comment]
@xxiiaass 同问

**Comment by catFishTail** [comment]
IE10 如果用require加载模块会得到结果NULL,这里指的不是jquery，而是项目里面的其他JS文件。

**Comment by zengxiaoluan** [comment]
> @afc163 截图这个模块就是整个项目的入口，之前没有定义过jquery之类的东西.....我log打印出来第一个参数，不管是不是require结果都一样，应该不提前获取模块依赖，也可以请求加载吧，问题是现在的项目，修改require就解析错误，exec解析失败，why，好奇怪.....

感觉 seajs 的作者有点故弄玄虚，看一下源码就知道问题所在了。

**Comment by zengxiaoluan** [comment]
> 第一个参数'require'，在压缩时候会改名，导致无法正常执行，有什么好的办法吗

require 关键字不压缩
