### ISSUE TITLE
配置

### ISSUE THREAD

**Issue by lifesinger** [seajs/seajs#262]
# 配置

可以对 Sea.js 进行配置，让模块编写、开发调试更方便。

---
## seajs.config `seajs.config(options)`

用来进行配置的方法。

``` js
seajs.config({

  // 别名配置
  alias: {
    'es5-safe': 'gallery/es5-safe/0.9.3/es5-safe',
    'json': 'gallery/json/1.0.2/json',
    'jquery': 'jquery/jquery/1.10.1/jquery'
  },

  // 路径配置
  paths: {
    'gallery': 'https://a.alipayobjects.com/gallery'
  },

  // 变量配置
  vars: {
    'locale': 'zh-cn'
  },

  // 映射配置
  map: [
    ['http://example.com/js/app/', 'http://localhost/js/app/']
  ],

  // 预加载项
  preload: [
    Function.prototype.bind ? '' : 'es5-safe',
    this.JSON ? '' : 'json'
  ],

  // 调试模式
  debug: true,

  // Sea.js 的基础路径
  base: 'http://example.com/path/to/base/',

  // 文件编码
  charset: 'utf-8'
});
```

支持以下配置选项：
### alias `Object`

当模块标识很长时，可以使用 `alias` 来简化。

``` js
seajs.config({
  alias: {
    'jquery': 'jquery/jquery/1.10.1/jquery',
    'app/biz': 'http://path/to/app/biz.js',
  }
});
```

``` js
define(function(require, exports, module) {

   var $ = require('jquery');
     //=> 加载的是 http://path/to/base/jquery/jquery/1.10.1/jquery.js

   var biz = require('app/biz');
     //=> 加载的是 http://path/to/app/biz.js

});
```

使用 `alias`，可以让文件的真实路径与调用标识分开，有利于统一维护。
### paths `Object`

当目录比较深，或需要跨目录调用模块时，可以使用 `paths` 来简化书写。

``` js
seajs.config({
  paths: {
    'gallery': 'https://a.alipayobjects.com/gallery',
    'app': 'path/to/app',
  }
});
```

``` js
define(function(require, exports, module) {

   var underscore = require('gallery/underscore');
     //=> 加载的是 https://a.alipayobjects.com/gallery/underscore.js

   var biz = require('app/biz');
     //=> 加载的是 path/to/app/biz.js

});
```

`paths` 配置可以结合 `alias` 配置一起使用，让模块引用非常方便。
### vars `Object`

有些场景下，模块路径在运行时才能确定，这时可以使用 `vars` 变量来配置。

``` js
seajs.config({
  vars: {
    'locale': 'zh-cn'
  }
});
```

``` js
define(function(require, exports, module) {

  var lang = require('./i18n/{locale}.js');
     //=> 加载的是 path/to/i18n/zh-cn.js

});
```

`vars` 配置的是模块标识中的变量值，在模块标识中用 `{key}` 来表示变量。
### map `Array`

该配置可对模块路径进行映射修改，可用于路径转换、在线调试等。

``` js
seajs.config({
  map: [
    [ '.js', '-debug.js' ]
  ]
});
```

``` js
define(function(require, exports, module) {

  var a = require('./a');
     //=> 加载的是 path/to/a-debug.js

});
```

更多用法可参考：[调试实践](https://github.com/seajs/seajs/issues/263)
### preload `Array`

使用 `preload` 配置项，可以在普通模块加载前，提前加载并初始化好指定模块。

``` js
// 在老浏览器中，提前加载好 ES5 和 json 模块
seajs.config({
  preload: [
    Function.prototype.bind ? '' : 'es5-safe',
    this.JSON ? '' : 'json'
  ]
});
```

`preload` 中的空字符串会被忽略掉。

**注意**：`preload` 中的配置，需要等到 `use` 时才加载。比如：

``` js
seajs.config({
  preload: 'a'
});

// 在加载 b 之前，会确保模块 a 已经加载并执行好
seajs.use('./b');
```

`preload` 配置不能放在模块文件里面：

``` js
seajs.config({
  preload: 'a'
});

define(function(require, exports) {
  // 此处执行时，不能保证模块 a 已经加载并执行好
});
```
### debug `Boolean`

值为 `true` 时，加载器不会删除动态插入的 script 标签。插件也可以根据 debug 配置，来决策 log 等信息的输出。
### base `String`

Sea.js 在解析顶级标识时，会相对 `base` 路径来解析。详情请参阅 [模块标识](https://github.com/seajs/seajs/issues/258)

**在 `seajs@2.3.0` 之前，Sea.js 会根据 sea.js 的路径去猜测 `base` 路径，一般为路径上含有 seajs 字符串的上一级路径。在 `seajs@2.3.0` 后，去掉了这个模糊的猜测。我们推荐始终手动设置一个准确的 `base` 路径**。
### charset `String | Function`

获取模块文件时，`<script>` 或 `<link>` 标签的 `charset` 属性。 默认是 `utf-8`

`charset` 还可以是一个函数：

``` js
seajs.config({
  charset: function(url) {

    // xxx 目录下的文件用 gbk 编码加载
    if (url.indexOf('http://example.com/js/xxx') === 0) {
      return 'gbk';
    }

    // 其他文件用 utf-8 编码
    return 'utf-8';

  }
});
```
### 多次配置自动合并

`seajs.config` 可以多次运行，每次运行时，会对配置项进行合并操作：

``` js
seajs.config({
  alias: {
    'jquery': 'path/to/jquery.js',
    'a': 'path/to/a.js'
  },
  preload: ['seajs-text']
});
```

``` js
seajs.config({
  alias: {
    'underscore': 'path/to/underscore.js',
    'a': 'path/to/biz/a.js'
  },
  preload: ['seajs-combo']
});
```

上面两处 `config` 运行的结果是：

``` js
 alias = {
   'jquery': 'path/to/jquery.js',
   'underscore': 'path/to/underscore.js',
   'a': 'path/to/biz/a.js'
 };

 preload = ['seajs-text', 'seajs-combo'];
```

即：`config` 会自动合并不存在的项，对存在的项则进行覆盖。
### 插件的配置

插件可以给 Sea.js 添加配置项，请查看具体插件了解相关配置。
### 配置文件

配置可以直接写在 html 页面上，也可以独立出来成为一个文件。

config.js

``` js
seajs.config({
  ...
});
```

独立成一个文件时，一般通过 script 标签在页面中同步引入。

---

常用的配置项是 `alias`、`paths`、`base`，其他配置项有需要时，来查查文档就会用了。

**Comment by lay139217** [comment]
为什么我用
 seajs.use(['jquery','customjs/user/login'],function($){
       $(function(){
          $("#test").userLogin();
       });
   });
报
 http://192.168.1.103:8080/assets/js/seamodules/seajs/2.3.0/common-plugin/jquery/1.11.2/jquery.js?20150113 404 (Not Found) ，
不是说带版本号的seajs的基路径是 http://192.168.1.103:8080/assets/js/seamodules/这一段吗

**Comment by rebornvip** [comment]
加载jquery mobile 由于放在底部，加载时会闪一下，因为先加载了内容后才启用mobile，如何在页面加载前就引入呢？加载顺序问题，请帮忙点点。
![image](https://cloud.githubusercontent.com/assets/5562776/6690384/47eacee6-ccfb-11e4-9e65-35585e623ddb.png)

**Comment by Tonyee** [comment]
老师，在单页模式应用中，首页加载好之后，加载一个模块页面后使用seajs.use("business/userInfo")请求相应的模块内容初始化js，js中是一些ajax请求，用于页面内容加载；若这时我返回上一页，然后再点击相应链接进还这个模块，此时也是使用seajs.use("business/userInfo")来请求相应js初始化页面，但是因为这是单页模式应用，重新进入这个模块页时因为userInfo.js已经存在，所以seajs.use("business/userInfo")并没有再次加载，这是这个模块页的内容就是空的，我应该怎么再次初始化这个页面的内容？

**Comment by wushilong** [comment]
为什么不能在config里面配置各个插件的依赖关系嘞,感觉很实用啊!

**Comment by lyndonliao** [comment]
说明文档是老版本的了，3.0 不是已经不支持preload配置了么

**Comment by myqldx** [comment]
不太懂config配置里面alias和paths的区别？

**Comment by guohuihot** [comment]
alias和paths有什么实质的区别,别说让看文档,看懂了就不在这里问了

**Comment by pingmac** [comment]
真好的东西，特来支持下

**Comment by hskww** [comment]
有个问题，文件加载成功，但里面代码没执行，导致后面使用时这个模块是null,后面发现是base配置有问题只能是当前根目录，不能再加层级，这算是个大坑吧

**Comment by qianet** [comment]
**请教这么一个问题:**
譬如我有一个大模块(像Jquery Easyui)
可否在配置中设定: 本模块使用的时候是需要批量加载其中的2个js文件2个css文件.
在页面中使用的时候, 只要写一个sea.use("easyui")...就同时加载和这个模块设定有关的所有js和css文件?

**Comment by zhishaofei3** [comment]
@qianet 数组吧 sea.use(['.css', '.js'], function(css, js){});

**Comment by qianet** [comment]
@zhishaofei3 好的,多谢,我尝试下看看.

**Comment by qianet** [comment]
请教这么一个问题, 我的web程序前段是: html+js+css的.
遇到文件客户端缓存的问题.
即: 即使我在config中变更了js文件的版本号.
但是, html文件是没有变化的.
那么, 客户端访问的时候, html是用的客户端缓存. 导致加载的js文件依然还是老版本的js文件
这个问题如何解决呢?
难道, 我的每个页面的sea-config.js文件都不使用缓存? 这个可以解决其他js文件的缓存.
但是config文件每次都是请求新的.

**Comment by zlstone** [comment]
@qianet 你确定config文件每次都是请求新的？如果那样配置map之后不应该有缓存，你遇到的问题是因为html文件没有修改，所以加载的config文件一直都是缓存，所以即使config修改也不会加载新版本的js文件。所以你需要修改的不是config.js而是html的入口文件的缓存。你可以吧seajs.config在html里也写一个，只配置map，对所有文件添加时间戳后缀，然后使用seajs.use()，又或者直接将入口文件script引入html中，直接给入口文件添加时间戳，都是可以的。

**Comment by mazhenxiao** [comment]
使用preload预加载js文件，未执行加载，请教！
seajs.config({
	 	vars:{path:"./js/bower_components"},
	 	// debug: true,
	 	alias:{
	 		"seajsCSS":"{path}/seajs-css/dist/seajs-css.js",
	 		"seajsTEXT":"{path}/seajs-text/dist/seajs-text.js",
	 		"underscore":"{path}/underscore/dist/underscore-min.js",
	 		"zepto":"{path}/zepto/zepto.min.js",
	 		"backbone":"{path}/backbone/backbone-min.js"
	 	},
	 	preload:["seajsCSS","seajsTEXT","underscore","zepto","backbone"]
	 })
	 seajs.use("./main/main.js")

**Comment by jeff6957** [comment]
我遇到了一个问题，就是

**Comment by jeff6957** [comment]
我遇到了一个问题，就是这种写法   require('../css/loading.css'); 写的引入的css默认会在后面加 .js   ;变成  loading.css.js  不知道怎么解

**Comment by ericyin168** [comment]
define(function (require) {
          var $ = require('jquery')
          alert($);//null
});
define('init', ['jquery'], function (require) {
          var $ = require('jquery')
          alert($); //null
});
就是想在init文件内使用jquery的方法而已，怎么就这么多问题。有没有一些思路说的比较清晰的案例参考》
不论是按照ID标识，还是以匿名的方式$对象都为null
报错：Uncaught TypeError: Cannot read property 'onUpdated' of undefined

**Comment by ericyin168** [comment]
define('init', ['jquery'], function (require) {
var $ = require('jquery')
alert($); //null
});
以上代码是在init.js内，也就是程序的入口。那么define('第一参数',['第二参数'],function(){});
第一参数到底是jquery的文件路径，还是init的文件路径？
第二参数应该指的是init.js的依赖？
查了很多案例，每个人写的都不一样，尤其是涉及到路径，毕竟每个团队项目的文件路径肯定不是一样的，一旦牵扯到路径，真实太麻烦。而且不知道错误在哪。
谁能来指点一下，快被被搞疯了...

**Comment by ericyin168** [comment]
同上一个朋友问的，文件加载了，但是使用模块时一直提示对象null，
比如:
define(function (require) {
          var $ = require('jquery')
          alert($);//null
});
直接在jquery文件内调试，发现文件已经被加载。

**Comment by elma-cao** [comment]
你是不是模块id不对呀，你比对一下

**Comment by baiduoduo** [comment]
@ericyin168 jquery.js没有模块化，我是这样解决的
define(function(){ 
	   [省略，这里全是jqueryv1.11.3的代码，代码完成后接下一句]
	    return $.noConflict(true);
});

**Comment by gongph** [comment]
您好请问下，sea.js 3.x.x版本不支持jquery模块吗？
---
我的 `sea.config.js`是这样配置的：
```js
seajs.config({
	alias : {
		'jquery' : 'jquery-3.1.0.js'
	}
})
```
`main.js` 是这样写的：
```js
define(function (require, exports, modules) {
	var $ = require('jquery');
	console.log($); //undefined
});
```
`index.html` 页面是这样引入的：
```html
<body>
	<script src="js/sea.js" type="text/javascript" charset="utf-8"></script>
	<script src="js/sea-config.js" type="text/javascript" charset="utf-8"></script>
	<script type="text/javascript">
	  seajs.use('main');
	</script>
</body>
```
jquery文件能够加载，但是显示的是 `undefined` 是因为 jquery是 `amd` 模块吗？ 在线等...
