### ISSUE TITLE
Sea.js 的调试接口

### ISSUE THREAD

**Issue by lifesinger** [seajs/seajs#263]
# Sea.js 的调试接口

使用 Sea.js，无论开发时还是上线后，调试都很方便。下面一一阐述。
## seajs.cache `Object`

通过 `seajs.cache`，可以查阅当前模块系统中的所有模块信息。

比如，打开 [seajs.org](http://seajs.org/)，然后在 WebKit Developer Tools 的 Console 面板中输入 `seajs.cache`，可以看到：

```
Object
  > http://seajs.org/docs/assets/main.js: x
  > https://a.alipayobjects.com/jquery/jquery/1.10.1/jquery.js: x
  > __proto__: Object
```

这些就是文档首页用到的模块。展开某一项可以看到模块的具体信息，含义可参考：[CMD 模块定义规范](https://github.com/seajs/seajs/issues/242) 中的 module 小节。
## seajs.resolve `Function`

类似 `require.resolve`，会利用模块系统的内部机制对传入的字符串参数进行路径解析。

``` js

seajs.resolve('jquery');
// => http://path/to/jquery.js

seajs.resolve('./a', 'http://example.com/to/b.js');
// => http://example.com/to/a.js

```

`seajs.resolve` 方法不光可以用来调试路径解析是否正确，还可以用在插件开发环境中。
## seajs.require `Function`

全局的 `require` 方法，可用来直接获取模块接口，比如

``` js
seajs.use(['a', 'b'], function() {

  var a = seajs.require('a')
  var b = seajs.require('b')

  // do something...
})
```
## seajs.data `Object`

通过 `seajs.data`，可以查看 `seajs` 所有配置以及一些内部变量的值，可用于插件开发。当加载遇到问题时，也可用于调试。
## seajs.log `Function`

由 seajs-log 插件提供，详见：https://github.com/seajs/seajs-log
## seajs.find `Function`

由 seajs-debug 插件提供，详见：https://github.com/seajs/seajs-debug

---

Sea.js 还有 debug 插件：[seajs-debug](https://github.com/seajs/seajs-debug)

有了这些方法和插件，能极大地方便开发维护，赶快试试吧。

**Comment by jack-Lo** [comment]
在seajs.use的回调里输出seajs.cache，第一项“_use_0”是什么？如果我要拿到所有的模块，我要怎么筛选？

**Comment by ruofeng086** [comment]
seajs.resolve和seajs.use 有什么区别？

**Comment by helei2015** [comment]
我不是很懂这个sea.config中的映射是怎么回事，请大家帮帮忙。。。

**Comment by Say-Hello** [comment]
我用了map以后，为什么在IE10下加载js 不执行define里面的函数了呢
paths:{
	  	"common":path+"/assets/common/sea_module/",
	  	"utils":path+"/assets/common/sea_module/utils",
	  	"core":path+"/assets/common/sea_module/core",
	  	"plug":path+"/assets/common/plug/",
	  	"dealer":path+"/assets/dealer/",
	  	"front":path+"/assets/front/",
	  	"manage":path+"/assets/manage/",
	  	"supplier":path+"/assets/supplier/"
	  },
	  preload: [
		Function.prototype.bind ? '' : 'es5',
		'common'
	  ]
	  ,
	  map: [[/^(.*\.(?:css|js))(.*)$/i, '$1?v='+staticVersion+'']],
