### ISSUE TITLE
API 快速参考

### ISSUE THREAD

**Issue by lifesinger** [seajs/seajs#266]
# API 快速参考

该页面列举了 Sea.js 的常用 API。只要掌握这些用法，就可以娴熟地进行模块化开发。

---
### seajs.config

用来对 Sea.js 进行配置。

``` js
seajs.config({

  // 设置路径，方便跨目录调用
  paths: {
    'arale': 'https://a.alipayobjects.com/arale',
    'jquery': 'https://a.alipayobjects.com/jquery'
  },

  // 设置别名，方便调用
  alias: {
    'class': 'arale/class/1.0.0/class',
    'jquery': 'jquery/jquery/1.10.1/jquery'
  }

});
```

更多配置项请参考：#262
### seajs.use

用来在页面中加载一个或多个模块。

``` js
// 加载一个模块
seajs.use('./a');

// 加载一个模块，在加载完成时，执行回调
seajs.use('./a', function(a) {
  a.doSomething();
});

// 加载多个模块，在加载完成时，执行回调
seajs.use(['./a', './b'], function(a, b) {
  a.doSomething();
  b.doSomething();
});
```

更多用法请参考：#260
### define

用来定义模块。Sea.js 推崇一个模块一个文件，遵循统一的写法：

``` js
define(function(require, exports, module) {

  // 模块代码

});
```

也可以手动指定模块 id 和依赖，详情请参考：#242
`require`, `exports` 和 `module` 三个参数可酌情省略，具体用法如下。
### require

`require` 用来获取指定模块的接口。

``` js
define(function(require) {

  // 获取模块 a 的接口
  var a = require('./a');

  // 调用模块 a 的方法
  a.doSomething();
});
```

注意，`require` 只接受字符串直接量作为参数，详细约定请阅读：#259
### require.async

用来在模块内部异步加载一个或多个模块。

``` js
define(function(require) {

  // 异步加载一个模块，在加载完成时，执行回调
  require.async('./b', function(b) {
    b.doSomething();
  });

  // 异步加载多个模块，在加载完成时，执行回调
  require.async(['./c', './d'], function(c, d) {
    c.doSomething();
    d.doSomething();
  });

});
```

详细说明请参考：#242
### exports

用来在模块内部对外提供接口。

``` js
define(function(require, exports) {

  // 对外提供 foo 属性
  exports.foo = 'bar';

  // 对外提供 doSomething 方法
  exports.doSomething = function() {};

});
```

详细说明请参考：#242
### module.exports

与 `exports` 类似，用来在模块内部对外提供接口。

``` js
define(function(require, exports, module) {

  // 对外提供接口
  module.exports = {
    name: 'a',
    doSomething: function() {};
  };

});
```

`module.exports` 与 `exports` 的区别，以及详细说明请参考：#242

---

以上 7 个接口是最常用的，要牢记于心。

这里提供一个不错的社区贡献的 API 文档：http://yslove.net/seajs/

**Comment by jack-Lo** [comment]
还是希望能够提供一些其他的压缩合并代码方案，比如提供一些api，结合后台（java/php）实现线上动态压缩。在本地实现压缩再迁移到服务器上，比较适合那些改动少且由个人维护的网站，对于改动频繁或者多人协作的的网站，这一操作实在是无法忍受。毕竟不是所有项目都是跑在nodejs下的，如果能够提供一套java/php下的压缩方案，对seajs的推广应该是很有帮助的。

**Comment by lifeforfun** [comment]
seajs里有没有一种方法，在seajs.use调用之前运行一个过滤器方法

**Comment by mozackye** [comment]
我按模块化jquery的方法模块化 zepto  会出现undefined is not a function的问题
define(function () {   
    //zepto源码
   return $.noConflict();
});   并且如果引入的第三方js插件都要手动模块化 是不是太繁琐  能写个通用方法解决不

**Comment by tbx19930222** [comment]
不知道是不是seajs的原因，http://www.51go.me在safari浏览器中加载草鸡慢，但其他浏览器加载都没问题啊？有没有大牛帮我看看，其中慢的有几个js和图片，js都是require进去的外部依赖，都是自己写的

**Comment by zouchengzhuo** [comment]
有个建议，在文档里边能否注明一下各个配置生效的版本？  我们的项目以前用的是2.2.1，paths配置就无法使用。这个配置到2.3.0才可以用吧。 担心还遇到其他的这样的问题，给开发者看文档造成困扰...

**Comment by JohnsonHuang94** [comment]
调用某个模块后不能立即得到其属性，可是为什么可以立即执行其函数

**Comment by ericyin168** [comment]
看着官网的5分钟入门，我居然真的信了，但是接下来花费的不仅仅是一个5分钟，而是成百上千的5分钟！下载的案例看起来千奇百怪，我就不明白为什么不能用一个简单的功能来做案例，里面放的文件一层嵌套一层，以至于找不到自己想要的。而且并没有考虑不是所有人都能熟练的或者编写过NODE，往上搜索到的教程也是千奇百怪，好像拥有各种写法，然后让人无从下手，特别是官网的文档，根本就不清楚需要表达什么内容。并不是不尊敬大神，初学者本身就没接触过这个东西，案例还做得那么复杂，又没有比较清晰明了的说明，真的感觉无从下手

**Comment by githubzhaoqian** [comment]
IE8 下use 执行方法 无响应

**Comment by SorrowX** [comment]
大神，我另一个js页面使用了这段代码

**Comment by SorrowX** [comment]
//载入手势
	var Hamme = require('./hamm');
	var hamObj = new Hamme();

**Comment by SorrowX** [comment]
页面就白屏了

**Comment by SorrowX** [comment]
被调用的js页面是把一个类抛出去了
module.exports = Hamm;

**Comment by SorrowX** [comment]
然后另一个js页面载入
![Uploading image.png…]()
就白屏了，除非不引人，就好了

**Comment by gonmin** [comment]
```
var $ = require('jquery');
  var Spinning = require('**./**spinning');
```
引入模块时，什么有时候是直接require+名称就可以了，什么时候要加**./**
