### ISSUE TITLE
SeaJS Users

### ISSUE THREAD

**Issue by lifesinger** [seajs/seajs#272]
目前 SeaJS 的使用者非常多，包括阿里、腾讯、网易等公司，还包括发现啦、好知等大量创业公司。
如果你也有使用 SeaJS，欢迎提交信息。凡是提交上来的，都有机会放到 [seajs.org](http://seajs.org/) 首页的 logo 墙里。

提交范例：

```
微博：[@Macji](http://weibo.com/macji)
公司：[发现啦](http://faxianla.com/)
logo：![logo](http://seajs.org/docs/assets/companies/faxianla.png)
```

按照上面的格式回复就好。

注：logo 的高度必须是 44 像素，宽度不超过 200 像素。

---

累积超过十个 logo 时会更新到 SeaJS 首页。更新到首页后，会从这里删除掉。

**Comment by li2274221** [comment]
微博：无
公司：[校校](http://www.xiaoxiao.la/organization/index.html)
logo：![logo](http://www.xiaoxiao.la/favicon.ico)

**Comment by lichunqiang** [comment]
微博：[@留学评估网](http://weibo.com/liuxuepinggu)
公司：北京评学优选科技教育有限公司
logo：![logo](https://cloud.githubusercontent.com/assets/2433916/7648998/6487cb0a-fb1b-11e4-90e8-7d8d36c01022.png)

**Comment by kuailingmin** [comment]
微博：[@前端艺术者](http://weibo.com/kuailingmin)
公司：[苏宁易购](http://www.suning.com/)
logo：![logo](http://img.suning.cn/public/v3/images/logo/snlogo.png?v=2015042703)

**Comment by noahzhu** [comment]
微博：无
公司：[Ping++](https://pingxx.com/)
logo：![logo](https://avatars1.githubusercontent.com/u/7113953?v=3&s=44)

**Comment by eyson** [comment]
微博：[@分期乐](http://weibo.com/fenqile)
公司：[分期乐](http://www.fenqile.com/)
logo：![logo](http://res.fenqile.com/res/img/global/logo.png)

**Comment by html580** [comment]
微博：<a href="http://weibo.com/fenqile">@html580</a>
个人站长:<a href="http://www.html580.com/">HTML我帮您</a>
logo:<a href="http://www.html580.com/"><div style="background:0288bb"><img style="max-width:100%;" alt="html580_com-logo" src="http://static.html580.com/assets/images/html580-logo.gif" ></div></a>

**Comment by fachilles** [comment]
微博：[@cheche365](http://weibo.com/cheche365)
公司：[车车车险](http://cheche365.com/)
logo：
![cheche365](https://cloud.githubusercontent.com/assets/3346188/12226337/6a541a6e-b855-11e5-900c-3416cd21707d.png)

**Comment by 0x0010** [comment]
微博：[@途牛旅游网](http://weibo.com/u/1286659964)
公司：[途牛旅游网](http://www.tuniu.com/)
logo：![logo](http://img3.tuniucdn.com/u/mainpic/logo/logo0127.png)

**Comment by adengweb** [comment]
微博：无
公司：[车秀网](http://www.chexiu.com/)
logo：![logo]( http://cxstatic.img16888.com/dist/images/cherry/logo-min-v2.png)

**Comment by bojue** [comment]
![2017-02-10 10-44-56](https://cloud.githubusercontent.com/assets/14350577/22812390/60828e6e-ef7f-11e6-96b1-f9140ccced36.png)
为什么样式一定要凌乱点呢

**Comment by tangyang8942** [comment]
不错，赞一个，目前公司暂未使用SeaJS
