### ISSUE TITLE
与 RequireJS 的异同

### ISSUE THREAD

**Issue by lifesinger** [seajs/seajs#277]
## 相同之处

RequireJS 和 Sea.js 都是模块加载器，倡导模块化开发理念，核心价值是让 JavaScript 的模块化开发变得简单自然。
## 不同之处

两者的主要区别如下：
1. **定位有差异**。RequireJS 想成为浏览器端的模块加载器，同时也想成为 Rhino / Node 等环境的模块加载器。Sea.js 则专注于 Web 浏览器端，同时通过 Node 扩展的方式可以很方便跑在 Node 环境中。
2. **遵循的规范不同**。RequireJS 遵循 AMD（异步模块定义）规范，Sea.js 遵循 CMD （通用模块定义）规范。规范的不同，导致了两者 API 不同。Sea.js 更贴近 CommonJS Modules/1.1 和 Node Modules 规范。
3. **推广理念有差异**。RequireJS 在尝试让第三方类库修改自身来支持 RequireJS，目前只有少数社区采纳。Sea.js 不强推，采用自主封装的方式来“海纳百川”，目前已有较成熟的封装策略。
4. **对开发调试的支持有差异**。Sea.js 非常关注代码的开发调试，有 nocache、debug 等用于调试的插件。RequireJS 无这方面的明显支持。
5. **插件机制不同**。RequireJS 采取的是在源码中预留接口的形式，插件类型比较单一。Sea.js 采取的是通用事件机制，插件类型更丰富。

还有不少差异，涉及具体使用方式和源码实现，欢迎有兴趣者研究并发表看法。

总之，如果说 RequireJS 是 Prototype 类库的话，则 Sea.js 致力于成为 jQuery 类库。
## 最重要的

最后，向 RequireJS 致敬！RequireJS 和 Sea.js 是好兄弟，一起努力推广模块化开发思想，这才是最重要的。
## 更新
- 2013.06.30 推荐一篇图片并茂的文章：<a href="http://www.douban.com/note/283566440/">Sea.js 与 RequireJS 最大的区别</a>
## 参考
- [LABjs、RequireJS、Sea.js 哪个最好用？为什么？](http://www.zhihu.com/question/20342350)
- 从 RequireJS 到 Sea.js 系列：[（1）](http://lifesinger.wordpress.com/2011/10/30/comparing-requirejs-with-seajs-1/) [（2）](http://lifesinger.wordpress.com/2011/10/30/comparing-requirejs-with-seajs-2/) [（3）](http://lifesinger.wordpress.com/2011/10/30/comparing-requirejs-with-seajs-3/) [（4）](http://lifesinger.wordpress.com/2011/10/30/comparing-requirejs-with-seajs-4/) [（5）](http://lifesinger.wordpress.com/2011/10/30/comparing-requirejs-with-seajs-5/) （要翻墙）
- [Sea.js 和 RequireJS 的异同](http://lifesinger.wordpress.com/2011/05/17/the-difference-between-seajs-and-requirejs/)（要翻墙）
- [AMD 与 CMD 的区别](http://www.zhihu.com/question/20351507)

**Comment by Galen-Yip** [comment]
@army8735 我想问下关于底层中 requirejs和seajs中 loader的差别 不知道能否告知 望赐教。。。

**Comment by Galen-Yip** [comment]
玉伯大大 我看了推荐文章里面关于seajs按需执行这块 当初这一功能设计成这样一定是支付宝场景所需 能不能举一个大体的例子，

**Comment by terranc** [comment]
@lifesinger 第 3 条差异具体是什么意思？“三方类库” 是指 jquery 这样的类库吗？seajs 不一样需要 jquery 更改源码来接入吗？“自主封装” 具体是怎样的过程呢，求文档~

**Comment by afc163** [comment]
github 还有机器人水军的...?

**Comment by ysmood** [comment]
@afc163 大概是在黑这个 po 吧

**Comment by lucifercha** [comment]
seajs要使用的模块都必须是cmd规范的，以前项目中要使用的代码都需要改变成cmd规范看起来好复杂，有没有什么好办法解决这个问题的

**Comment by adhehe** [comment]
还好吧，大多数常用的插件都有相关的CMD和AMD规范的源码，真没有的话自己稍改就行了，如果真想简单点，就用requirejs吧，里面有个shim: 为那些没有使用define()来声明依赖关系、设置模块的"浏览器全局变量注入"型脚本做依赖和导出配置。

在 2015-07-11 11:08:29，"lucifercha" <notifications@github.com> 写道：


seajs要使用的模块都必须是cmd规范的，以前项目中要使用的代码都需要改变成cmd规范看起来好复杂，有没有什么好办法解决这个问题的

**Comment by pecker** [comment]
不错，就像java和.net的不同规范语言一样

**Comment by HassanChiang** [comment]
Mark

**Comment by DarrenMan** [comment]
#### 视自己需求而定吧

**Comment by yolynn-bird** [comment]
能否结合ES6再来对比下呢

**Comment by mygaochunming** [comment]
@lifesinger 

从 RequireJS 到 Sea.js 系列：1~3打不开，是文章地址修改了吗？希望能够拜读一下

**Comment by dhlolo** [comment]
用CMD同步的思路去处理异步问题：
- lazy import使脚本模块复杂时效率方面得不到保证
- 把setTimeout内部的代码认为需要符合同步顺序似乎也没啥好处
- 倒是对于开发者节省了麻烦

**Comment by gt333** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
