### ISSUE TITLE
seajs.use是否是在页面加载完成后运行

### ISSUE THREAD

**Issue by movever** [seajs/seajs#326]
一直没有考虑过这个问题

<pre>
seajs.use('module', function(){
    // 这里是否是在document加载完成后运行？
    // 还是只加载好对应的模块，而不去管document的状态？
    //code
})
</pre>

我一直当它是考虑document加载状态的，即类似于$(document).ready

在opera中遇到如下问题

<pre>
&lt;script&gt;
seajs.use([modules], function(){
    // some code ...
    // 闭包
    (function(){
       $('#test').length > 0; //return false
    })();
    // some code ...
})
&lt;/script&gt;
&lt;a id="test"&gt;&lt;/a&gt;
</pre>

但是在别的浏览器中返回true
所以不是很明白seajs.use是否确保了document加载完毕？

**Comment by lingyange** [comment]
HTML是按顺序加载的，JS也是按顺序执行的
