### ISSUE TITLE
本地安装 nginx 并启动 combo 服务

### ISSUE THREAD

**Issue by soda-x** [seajs/seajs#337]
不好意思本教程适用于mac用户 

macport和homebrew方式二选一，注意 ： 两者不兼容！ 本地安装了homebrew 就使用homebrew！
# macport

---

mac 用户 首先安装 `macport`  ---> http://www.macports.org/install.php 有dmg安装包，非常简便

再可以通过`macport` 安装`pcre`

`$port install pcre`

之后去nginx官网下载最新 stable 1.2.3 版本 http://nginx.org/en/download.html

下载下来后 放在 /usr/local/src  并解压  

`cd /usr/local/src` 

如果没有`src`目录，可新建一个

压缩 `$tar xvzf nainx-1.2.3.tar.gz`

之后进入解压后的目录并加入自己所需要的模块 

`sudo ./configure --prefix=/usr/local/nginx --user=www --group=www --with-http_ssl_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_gzip_static_module --with-http_stub_status_module --http-proxy-temp-path=/var/nginx/proxy --http-fastcgi-temp-path=/var/nginx/fastcgi --http-client-body-temp-path=/var/nginx/client --add-module=/usr/local/src/nginx-http-concat`

注意`--add-module=/usr/local/src/nginx-http-concat`  这个就是由我们淘宝开发的`combo`插件

github地址为：https://github.com/taobao/nginx-http-concat

`$sudo make`

`$sudo make install`
# homebrew方式

---

首先确保安装了homebrew

homebrew安装非常非常简易 one line 
- `ruby -e "$(curl -fsSkL raw.github.com/mxcl/homebrew/go)"`

安装完毕之后
-  `brew install wget`

使用`wget`来获取稳定版本的`nginx`
- `wget http://nginx.org/download/nginx-1.2.4.tar.gz`

解压
- `tar -zxvf nginx-1.2.4.tar.gz`

进入解压出来的nginx目录

安装PCRE  
- `brew install pcre`

之后进入解压后的目录并加入自己所需要的模块 
- `sudo ./configure --prefix=/usr/local/nginx --user=www --group=www --with-http_ssl_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_gzip_static_module --with-http_stub_status_module --http-proxy-temp-path=/var/nginx/proxy --http-fastcgi-temp-path=/var/nginx/fastcgi --http-client-body-temp-path=/var/nginx/client --add-module=/usr/local/src/nginx-http-concat`

注意`--add-module=/usr/local/src/nginx-http-concat`  这个就是由我们淘宝开发的`combo`插件

github地址为：https://github.com/taobao/nginx-http-concat
- `$sudo make`

此时控制台会报如下错 

```
Undefined symbols for architecture x86_64:

  "_pcre_free_study", referenced from:

      _ngx_pcre_free_studies in ngx_regex.o

ld: symbol(s) not found for architecture x86_64

collect2: ld returned 1 exit status

make[1]: *** [objs/nginx] Error 1

make: *** [build] Error 2
```

需要修改如下：
- `sudo ./configure --prefix=/usr/local/nginx --user=www --group=www --with-http_ssl_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_gzip_static_module --with-http_stub_status_module --http-proxy-temp-path=/var/nginx/proxy --http-fastcgi-temp-path=/var/nginx/fastcgi --http-client-body-temp-path=/var/nginx/client --add-module=/usr/local/src/nginx-http-concat -with-ld-opt="-L /usr/local/lib"`

注意修改点： `-with-ld-opt="-L /usr/local/lib"`

最后一步
- `$sudo make` &  `$sudo make install`
# 使用nginx

---

最后开启`nginx`

`$sudo /usr/local/nginx/sbin/nginx`

如果嫌输入那么一大段路径麻烦可以建个软连接

`sudo ln -s /usr/local/nginx/sbin/nginx  /usr/bin`

如果想看看安装是否都ok 可以 具体使用如下命令 

`$sudo /usr/local/nginx/sbin/nginx  -t`

`$sudo /usr/local/nginx/sbin/nginx -s reload` 为重启

安装好`nginx`好后 

需要对其进行一些配置 

比如 `root 目录的更换` , `文件条目的罗列`, `combo服务的配置`

随便举例一下：

首先得先打开 配置文件夹  `open   /usr/local/nginx/conf` 

然后用编辑器 当然你也可以用`vim` 打开 `nginx.conf`文件

主要修改 `server` 内内容

``` javacript

server {
        listen       80;
        server_name  localhost;
        autoindex on;  // 支持罗列
        root   /Users/pigcan/workspace;  //更改根目录

        #charset koi8-r;

        #access_log  logs/host.access.log  main;




        location / {                
            index  index.html index.htm;
        }
        // 指定需要combo的路径
        location /path/to/combo/ {
            concat on;
            concat_max_files 20;
        }
}


```

到此你就可以在本地实现特定目录下js或者css 文件 的 combo服务了

**Comment by louisluodong** [comment]
sudo ./configure --prefix=/usr/local/Cellar/nginx/1.10.1 --user=www --group=www --with-http_ssl_module --with-openssl=/usr/local/Cellar/openssl/1.0.2h_1 --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_gzip_static_module --with-http_stub_status_module --http-proxy-temp-path=/usr/local/Cellar/nginx/1.10.1/proxy --conf-path=/usr/local/etc/nginx/nginx.conf --http-fastcgi-temp-path=/usr/local/Cellar/nginx/1.10.1/fastcgi --http-client-body-temp-path=/usr/local/Cellar/nginx/1.10.1/client --add-module=/usr/local/src/nginx-http-concat --with-cc-opt="-L /usr/local/lib"

**Comment by tttlkkkl** [comment]
编译选项：
configure arguments: --prefix=/usr/local/nginx/ --user=www --group=www --prefix=/usr/local/nginx --with-http_stub_status_module --with-http_ssl_module --with-http_spdy_module --with-http_gzip_static_module --with-ipv6 --with-http_sub_module --add-module=/home/m/nginx-http-concat
确认错误日志中没有异常问题。
按照说明已经配置如下：
server {
       listen       9004;
       index index.html index.htm;
       root /home/34team/mwpqy/;
   #location ~ .*/\.(css|js)$ {
       location /test/css/ {
           concat on;
           concat_max_files 20;
       }
      location /test/js/ {
          concat on;
          concat_max_files 20;
      }
      access_log  /tmp/damon.com.log;
  }
然后在以上配置的两个文件夹中分别放入1.css,2,css和1.js,2.js 两个文件,http://127.0.0.1:9004/??1.css,2.css没有成功。求助：这个地方到底应该怎么配置？所有说明文档都是随便说一下没有告知该如何根据服务器路径进行配置，新手根本猜不透，先感谢大神解答。
