### ISSUE TITLE
5 分钟上手 SeaJS

### ISSUE THREAD

**Issue by fool2fish** [seajs/seajs#374]
请先查看 [线上演示](http://seajs.org/docs/examples/hello/index.html) ，或下载 [源码包](http://seajs.org/docs/examples/hello.zip) ，解压后访问 index.html 。 
## 文件结构
- hello/
  - index.html
  - main.js
  - hello.js
## index.html
- 在页面中引入 sea.js
- 通过 data-main 属性配置启动脚本，路径相对于当前页面

``` html
<!doctype html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Hello, SeaJS!</title>
    </head>
    <body>
        <script src="http://seajs.org/dist/sea.js" data-main="./main"></script>
    </body>
</html>
```
## main.js

main.js 作为启动脚本只干两件事：
- 通过 [seajs.config(options)](https://github.com/seajs/seajs/issues/262) 进行配置。本例中 alias 用于配置模块的加载路径，稍后 hello.js 模块的 require(module) 会用到
- 通过 [seajs.use(id, callback)](https://github.com/seajs/seajs/issues/260) 加载模块，use 的模块路径相对于当前页面

``` js
seajs.config({
    alias: {
        'jquery': 'http://modules.seajs.org/jquery/1.7.2/jquery.js'
    }
});

seajs.use(['./hello'], function(Hello) {
    new Hello()
});
```
## hello.js

hello.js 是一个标准的模块文件，其中：
- [define(factory)](https://github.com/seajs/seajs/issues/242) 定义一个模块
- [require(module)](https://github.com/seajs/seajs/issues/242) 调用其他模块，本例中用到的 jquery 路径通过 seajs.config 的 alias 配置
- 通过 return 返回定义的模块

``` js
define(function(require, exports, module) {

    var $ = require('jquery')

    function Hello(){
        this.render()
    }

    Hello.prototype.render = function(){
        $('<h1 style="display:none;">Hello SeaJS !</h1>').appendTo('body').fadeIn(2000)
    }

    return Hello

});

```
## 结束语

怎么样，SeaJS 入门真的只要5分钟吧：）

通过这个例子你已经掌握了 SeaJS 最核心的功能。接下来推荐按顺序阅读 [使用文档](http://seajs.org/docs/#api) 中的其他文档，会让你对 SeaJS 有更全面的了解。

**Comment by seqwait** [comment]
嘎嘎....
