### ISSUE TITLE
关于多模块组成的包合并后的使用问题。

### ISSUE THREAD

**Issue by onlytiancai** [seajs/seajs#387]
整整看了两天多的seajs文档，感觉seajs和spm很强大，考虑的很周全。

可能文档有看的不细的地方，或有些地方理解的不对，我现在写了一个包含多个模块的包。

用spm把里面所有的模块打包后，sea.use只能使用这个主包，其实这个打包后的文件里把其它模块也打进去了，却不知道如何使用。

说起来可能有些不清晰，我写了个Demo演示这个问题，请教一下最佳的做法应该是怎样的？

https://github.com/onlytiancai/codesnip/tree/master/javascript/seajs_test

另外我看官方文档，基本没介绍defind(moduleid,dep,factory)这种形式，而spm打包全打成这样的了。

一般我们写模块都是define(function(require, exports, module){})，这时候moduleid就是自己的文件名，别人可以用require('./a')来使用。

而我的a.js如果是define("xxx",[],function(require,exports, module){})的话，我应该用require("./a")和，还是require("xxx")呢？

**Comment by heiliuer** [comment]
use(["a_b.js"],funciton(){
    //此时怎么调用 a_b.js（定义了a，b两个模块）中的a模块
    //require函数只有通过seajs.require调用，是全局的吗
});
