### ISSUE TITLE
构建工具

### ISSUE THREAD

**Issue by lifesinger** [seajs/seajs#538]
## 标准构建

> spm3 已经发布，建议使用最新的构建工具。http://spmjs.io/documentation/develop-a-package#build

---

如果项目遵循推荐的标准目录结构：

```
foo-module/
  |-- dist                    存放构建好的文件
  |-- src                     存放 js、css 等源码
  |     |-- foo.js
  |     `-- style.css
  `-- package.json      模块信息   
```

那么构建很简单。首先安装 spm 工具（spm2）：

```
$ npm install spm@2.x -g
$ npm install spm-build@0.x -g
```

然后运行构建命令：

```
$ cd foo-module
$ spm build
```

这样，就会根据 `package.json` 中的信息，将文件自动构建到 `dist` 目录下。构建后，还需要将 dist 目录下的文件部署到 `sea-modules` 目录中，比如 examples 中的 `make deploy` 命令：[Makefile](https://github.com/seajs/examples/blob/master/static/hello/Makefile)

详细可参考 http://docs.spmjs.org/

推荐将 [seajs/examples](https://github.com/seajs/examples) clone 到本地，实际操作一下就清楚。
## 自定义构建

如果标准构建无法满足需求，可以直接使用 Grunt 来完成。Grunt 是一个非常优秀的构建工具，详见：http://gruntjs.com/

利用 Grunt 来构建 CMD 模块需要使用到以下 Grunt Tasks：
- [grunt-cmd-transport](https://github.com/spmjs/grunt-cmd-transport)
- [grunt-cmd-concat](https://github.com/spmjs/grunt-cmd-concat)

这一块真的很简单，只要你熟悉 Grunt，因此先阅读 Grunt 的文档吧，然后有任何问题，欢迎回复。

推荐几篇社区贡献的文章：
- [CMD 模块构建，从认识 Grunt 开始](https://github.com/seajs/seajs/issues/670)
- [如何使用 Grunt 构建一个中型项目](https://github.com/seajs/seajs/issues/672)
- [使用 spm 构建业务模块的个人经验](https://github.com/seajs/seajs/issues/690)

非常欢迎大家的使用经验总结。

---

有任何问题，欢迎留言交流。
注意：已解决的问题，会在整理后删除掉。

**Comment by brucecham** [comment]
目前项目中一直在用spm2的版本，看了spm3的版本文档，写法上成了commonjs风格，更靠近nodejs，不再是以前的cmd。
commonjs主要运行在服务端，以这样的写法，如果在构建之前，也就是源码，怎么在浏览器上调试呢？spm3总不能先构建后调试吧？
有点迷惑

**Comment by afc163** [comment]
1. http://spmjs.io/documentation/develop-a-package
2. https://github.com/spmjs/spm-server

**Comment by wangxiao2012** [comment]
![qq 20150115101617](https://cloud.githubusercontent.com/assets/9691800/5751782/f802a17e-9ca3-11e4-9fb8-34ab9c00e0b9.jpg)

已经按照上面的要求安装了 npm install spm-build -g
安装的过程中也没有任何的error ..但是执行的时候就是如图.试了很多次还是那样

@afc163  @lifesinger

**Comment by brucecham** [comment]
@wangxiao2012 用 spm-build 试试

**Comment by wangxiao2012** [comment]
@brucecham   


![Uploading 2.jpg . . .]()

**Comment by bingoyan** [comment]
通过spm压缩后代码为
define("demo/1.1.1/lib/main-debug", [], function(require, exports, module){
define(function(require, exports) {
    var query = require("demo/1.1.1/lib/queryRandom-debug")
      , flbox = require("demo/1.1.1/lib/flbox-debug");
    exports.bind = function(element) {
        element.onclick = function() {
            var href = this.href;
            flbox.open(query.queryRandom(href));    
            return false;
        };
    };
});
});
多出了一个define，这个怎么解决？

**Comment by afc163** [comment]
Write your code in CommonJS.

**Comment by bingoyan** [comment]
@afc163 Thank you

**Comment by bingoyan** [comment]
@afc163  请教下code in CommonJS，是我调用seajs的地方还是，build的js代码？

**Comment by bingoyan** [comment]
@afc163  请教下code in CommonJS，是我调用seajs的代码还是spm build里面的js代码？

**Comment by afc163** [comment]
类似：https://github.com/aralejs/base/tree/master/src

**Comment by bingoyan** [comment]
@afc163 看了这个demo，里面的js代码头少了define定义模块，用spm打包后可以正常seajs.use，但是这里遇到一个问题，我在开发环境下，代码由
define(function(require,exports,module){
    var query = require("./demo1");
    var flbox = require("./demo2");
    exports.bind = function(element) {
	element.onclick = function() {
		var href = this.href;
		flbox.open(query.queryRandom(href));    
		return false;
	};
    };
});
改为:
var query = require("./demo1");
    var flbox = require("./demo2");
    exports.bind = function(element) {
	element.onclick = function() {
		var href = this.href;
		flbox.open(query.queryRandom(href));    
		return false;
	};
    };
会导致use调用不成，缺少define定义

这种情况，有什么好的建议？

**Comment by afc163** [comment]
看 `something you may need`

**Comment by bingoyan** [comment]
@afc163 spm-server 看了不是很明白，可能刚接触seajs，现在这个跨越较大。有没有新版本的入门demo?  目前我们的项目正在准备整合阶段，就像我上面说的，打包的时候套了两层define是因为commonjs规范，去掉代码中的define后，打包后，测试可以，但是开发的时候确出现问题了。

**Comment by afc163** [comment]
目前有四种针对 CommonJS 源码线下的调试方案，也是我们自己使用的调试方式。

1. `spm doc watch` 动态包裹 define。适合于标准 spm 模块的调试开发。http://spmjs.io/documentation/develop-a-package#code-and-debug
2. `spm-server` 动态包裹 define 。适合于项目中的 CommonJS 调试。https://github.com/spmjs/spm-server
3. `seajs-wrap` 静态方式包裹 define，适合于不想使用本地动态服务的调试方案。https://github.com/seajs/seajs-wrap
4. `serve-spm` 动态包裹 define 的中间件，兼容于 express 和 koa。1 和 2 其实后面都依赖这个库，适合团队搭建自己的调试方案。

你可以根据自己的情况挑选合适的方案，如果都不能满足，欢迎自行探索和建议。

**Comment by afc163** [comment]
https://github.com/spmjs/spm/wiki/%E8%B0%83%E8%AF%95-CommonJS-%E6%BA%90%E7%A0%81

**Comment by dahai300** [comment]
我的项目目录是这样的：
TESTSS
----------dist
----------src
--------------seajs
--------------------sea.js
--------------application.js
--------------utils.js
----------index.html
----------package.json
我运行spm build 之后，在dist文件夹下生成了一个空的main.js，请问下是什么原因？

**Comment by auslee** [comment]
spm工具使用方法，这个网址怎么404了？ 有没有介绍spm的使用的新网址 ，最好有示例，多谢

https://github.com/seajs/spm/

**Comment by lepture** [comment]
@auslee 上面那么多链接，就没有一个是你说的这个链接，哪里找的？

**Comment by yyzph** [comment]
![qq 20150227164214](https://cloud.githubusercontent.com/assets/8059286/6409493/840b7796-be9f-11e4-9b2c-1e0bbc2a7691.png)
请问，安装spm的时候这样，是什么问题？

**Comment by wsdqr001** [comment]
我的项目目录是这样的：
spm
----------src
--------------a.js
--------------b.js
----------package.json
我运行spm build 之后，没有任何反应，不生成dist文件夹。又尝试了下手动建立dist文件下，但是还是无法生成文件。

**Comment by zjgnlzq** [comment]
需要在package.json中的output配置要输出的文件

2015-03-20



bigcow



发件人：wsdqr001 <notifications@github.com>
发送时间：2015-03-20 16:39
主题：Re: [seajs] 构建工具 (#538)
收件人："seajs/seajs"<seajs@noreply.github.com>
抄送：

我的项目目录是这样的：
spm
----------src
--------------a.js
--------------b.js
----------package.json
我运行spm build 之后，没有任何反应，不生成dist文件夹。又尝试了下手动建立dist文件下，但是还是无法生成文件。

**Comment by siguang1983** [comment]
为什么用提取完文件后在调用模块，模块也加载进来，但确调用不了，
transport这块好折磨人啊，总会存在文件路径的问题.

**Comment by siguang1983** [comment]
使用grunt，也需要安装spm吗，还是直接装这几项grunt-cmd-transport、grunt-cmd-concat、grunt-contrib-uglify就可以了

**Comment by zhenn** [comment]
请教：如果seajs配置了paths，在打包时如何配置package，可以让根据paths路径引用的模块也打包进来

**Comment by zhenn** [comment]
额外引用的路径，无法打包啊

**Comment by az8321550** [comment]
怎么把html里的js src也跟着替换掉啊？

**Comment by wonyun** [comment]
有知道的朋友请赐教：
seajs定义的模块若按不带id的CMD格式书写的话如A模块，未合并时对模块所依赖的其它模块如B和C会发送请求获取B和C，这很正常，但是若合并B和C模块为一个D文件时，这时A模块依赖的D就可以了吧，这时浏览器还会发送两次请求分别加载B和C模块么？？？？

**Comment by az8321550** [comment]
我只能说这个太难用了，而且没人维护，提个问题，半天没有人回答！

**Comment by adhehe** [comment]
有同感，使用spm3压缩合并CSS总是不行，类似的文档或问题找都找不到

**Comment by lucifercha** [comment]
恩我也感觉这样 加个QQ群半天没人搭理 加个阿里旺旺也没人搭理 文档写的乱七八糟真的无语了

**Comment by auslee** [comment]
transpaort打包seajs时 为什么只提取第一个require的引入？？？

看到上面说 打包seajs 这个真的很简单，感觉这么可笑啊， 打包真的很费劲，文档各种不全，能不能给个例子？
万分感谢

**Comment by anthonyli** [comment]
@auslee 其实这个过程需要你自己慢慢领会，我当时也和你一样，不过后面看了很多次这个文档领会了是挺简单，慢慢来别急，源码下载下来 有例子 多看几次 注意package里面的属性。

**Comment by auslee** [comment]
@anthonyli  grunt打包seajs 引入了transport那两个 没有一次打包成功的 各种配置 真的很烦 也没人问

**Comment by VanquisherMe** [comment]
忙了两天 依然没法用 gulp 打包 seaJs，主要是 transport，尝试了 gulp-seajs-transport ，gulp-cmd-pack，gulp-transport ，一直卡在 模块id 的生成上【主要原因：生成出来的 id 一直不对，其实就是没有 grunt 里面的  ---format: '../js/hellosea/{{filename}}' --- 设置】，希望作者 能提供一个 比较官方的 gulp 打包流程方式

**Comment by brucecham** [comment]
id提取的问题，可以试下 
gulp-cmd-transit     
gulp.src("/*.js")
        .pipe(transport({
        	dealIdCallback: function(id){
                     // codes for id  对默认提取的id进行过滤处理
                    return id;
               }
        }))

**Comment by VanquisherMe** [comment]
@brucecham 能看下具体实例么  看下gulpfile 文件

**Comment by brucecham** [comment]
@VanquisherMe https://github.com/brucecham/crm2/blob/master/Gulpfile.js#L167

**Comment by VanquisherMe** [comment]
@brucecham 非常感谢！

**Comment by zeroone001** [comment]
不错哦

**Comment by lwyi188** [comment]
正在研究gulp 构建seajs,  赞! @brucecham

**Comment by muzi131313** [comment]
之前好像见到玉伯在微博上说应该给seaJS立个碑了，不过小米的网站好像是用seaJS做的吧，还有一些也是用seaJS做的；最近在学习模块化，知道了有requireJS和seaJS，requireJS已经用gulp写出一个optimizer方式的打包的demo了；seaJs正准备些，准备用官方推荐的spm打包。话说，现在都用spm2打包，还是spm3打包啊？https://github.com/seajs/examples，给出的示例demo中，下面好像还是spm2打包的方式？还有，现在seaJS现在用的人还多么？

**Comment by wnow20** [comment]
@muzi131313 spm 源服务将会在 2016-03-15 下线

**Comment by muzi131313** [comment]
@wnow20  刚看到了[https://github.com/spmjs/spm/issues/1416](url)，那这些大神的demo再学习就没有什么意义了吧。[https://github.com/seajs/seajs/issues/690](url)，这个是issues

**Comment by shimadongxue** [comment]
过期了， 能不能更新一下， 细节。
