### ISSUE TITLE
关于主js文件（入口，data-main）应该怎么写的问题

### ISSUE THREAD

**Issue by xingrz** [seajs/seajs#539]
用了一段时间的SeaJS，不知道对SeaJS的理解有没有错。

假设我有一个html页面，负责处理它的交互的js文件是`main.js`（是否称之为入口？）

``` html
<script src="path/to/sea.js" data-main="main" />
```

之前main（先不用管config）是一个普通的js文件

``` js
seajs.use(['module-a', 'module-b'], function (moduleA, moduleB) {
  moduleA.init()
  moduleB.myFunc('haha!')
})
```

但刚刚无疑中发现了 [seajs/examples](https://github.com/seajs/examples) 这个repo，按照里面的例子，main本身也是一个module

``` js
define(function (require) {
  moduleA.init()
  moduleB.myFunc('haha!')
})
```

这样我就产生了一个疑问，作为一个html页面特定的js，一般不会被其它页面使用，本身是否需要是一个cmd module？

按照我之前的理解，module应该是可重用的代码，比如一个UI控件，比如一个数学函数库，等等等等，他们是已经被spm打包过的；而main.js（入口？不太懂，不敢滥用术语）是调用这些模块并且控制他们，类似用Node写命令行工具时的那个./bin目录里的东西，或者说直接敲`node xxx.js`时执行的那个`xxx.js`，本身不是CMD模块，发布的时候我也可以用普通的方式来进行压缩等等操作，不用理会匹配`require()`之类的，也不用用spm打包。

所以我想请教一下，如果有最佳实践的话，这个main.js应该是一个模块还是一个普通的js？

**Comment by git874997967** [comment]
你好  关于data-main 的用法  我想简单的问一下  如果在项目中有50个页面 ，每个页面使用的 js模块  及逻辑 各不相同，其中使用data-main 的sea.config文件需要和页面一一对应吗？
