### ISSUE TITLE
shim 插件

### ISSUE THREAD

**Issue by lifesinger** [seajs/seajs#579]
# 注意：从 Sea.js 2.1 开始已经去除该插件，非常不推荐使用。

理由：#744

---
# shim 插件

Sea.js 中的模块默认都遵守 CMD 规范，但现实中已存在大量普通 JavaScript 类库，比如 jQuery、Underscore 等。使用 shim 插件，可以将这些普通 JS 文件转换成 CMD 模块，从而能在 Sea.js 中正常使用。

激活 shim 插件：

``` js
seajs.config({
  plugins: ['shim']
});
```

一旦激活后，`alias` 配置项就可以接受 `shim Object` 配置。

``` js
seajs.config({
  // 激活 shim 插件
  plugins: ['shim'],

  // shim 配置项
  alias: {
    // jQuery 的 shim 配置
    'jquery': {
      src: 'lib/jquery-1.9.1.min.js',
      exports: 'jQuery'
    },

    // jquery.easing 插件的 shim 配置
    'jquery.easing': {
      src: 'lib/jquery.easing.1.3.js',
      deps: ['jquery']
    }
  }
});
```
## `shim Object`

`shim Object` 是一个对象：

``` js
'key': {
    src: String,
    deps: Array,
    exports: String | Function
  }
```

`src` 是字符串，表示文件路径。

`deps` 是数组，指定模块依赖。

`exports` 表示 `require(key)` 时应该返回哪个全局变量，比如 jquery 的是返回 `jQuery` 全局变量。`exports` 也可以是一个函数：

``` js
'jquery': {
  'src': 'lib/jquery-1.9.1.min.js',
  exports: function() {
    return jQuery.noConflict();
  }
}
```

通过 shim 插件，可以加载任何非 CMD 模块。

---

还可以自己开发插件，请参考：[插件开发指南](https://github.com/seajs/seajs/issues/264)

**Comment by shupan** [comment]
去除了插件，然后使用什么来替代啊~~
