### ISSUE TITLE
style 插件

### ISSUE THREAD

**Issue by lifesinger** [seajs/seajs#595]
## 已转移到 https://github.com/seajs/seajs-style/issues/1

---

给 seajs 增加 importStyle 方法。

``` js
seajs.config({
  plugins: ['style']
})

seajs.use('main', function(main) {
  // 使用 importStyle 导入样式
  seajs.importStyle('div { color: red }', 'a.css')
})
```
## `seajs.importStyle(cssText, id?)`

`importStyle` 方法会创建一个  `style` 元素，并将其内容设置为 `cssText`，然后插入到当前文档中。
- `cssText` 是文本字符串，存储要添加的样式内容。
- `id` 可选，如果传入，会给创建的 `style` 元素添加该 id 值。
## 注意事项
1. 传入的 `cssText` 字符串，如果中间有 `\0` 等转义字符，需要在传入前提前转义成 `\\0` 等字符，这样才能确保插入的内容无误。构建工具在实现时要注意这一点。
2. 在 IE 下，当前页面的 style 标签数不能超过 31 个。超过 31 后，插入的 style 无效。这时 seajs 会抛出异常：
   
   ``` js
   // http://support.microsoft.com/kb/262161
   if (doc.getElementsByTagName('style').length > 31) {
       throw new Error('Exceed the maximal count of style tags in IE')
   }
   ```
3. 构建工具在将 css 文件转换成 js 文件时，可以遵守以下格式：
   
   ``` js
   define('path/to/cssfile.css', [], function(require, exports, module) {
      seajs.importStyle('css text', module.uri)
   });
   ```
   
   传入 `module.uri` 的好处是，通过 style 的 id 可以清晰看到样式来源，有利于调试排错。

**Comment by Anikinly** [comment]
我只想问下这个插件有什么实际的使用场景如果我使用jquery，即便是原生也是一句话的事啊~
