### ISSUE TITLE
请教关于定义模块的时候，id以及deps的问题

### ISSUE THREAD

**Issue by zhoushun49** [seajs/seajs#685]
按照官网的文档说法，define一个模块时可以指定ID,以及deps模块的。如下：
define('hello', ['jquery'], function(require, exports, module) {...}
然后，又说ID,以及deps的话，推荐在写代码时不指定，通过构建工具来构建。

个人感觉用grunt构建比较麻烦，所以项目中暂将构建延后，用的还是未压缩构建的JS代码。
开发过程中，发现如果不指定id和deps的话好像也没问题。
但是总归有点担心，可否简单说明下，如果不指定id和deps ，有什么坏处没有？

**Comment by lwyi188** [comment]
@lifesinger   http://xx.com/path/to/js/app/z.js 的 id 就是 aa/z   >>    id 应该是 app/z ， 最近开始接触seajs，也是遇到了 同@zhoushun49 类似的问题。慢慢理解吧。
