### ISSUE TITLE
去除 shim 插件

### ISSUE THREAD

**Issue by lifesinger** [seajs/seajs#744]
从 Sea.js 2.1 开始去除 plugin-shim 插件。这个插件看起来能方便部分场景，但实际上带来的后续问题一堆，主要集中在：
1. 混淆了 CMD 模块和普通文件的区别，有了 shim 插件后，很多人会把 Sea.js 当文件加载器用，但 Sea.js 的核心并不是文件加载器，而是模块加载器。shim 插件一定程度上背离了 Sea.js 作为模块加载器的初衷。
2. 很多人分不清 shim 究竟代表什么含义，更不明白 src 、exports 等配置项的含义。经用存在误用和误理解。
3. shim 插件，导致依赖变复杂。一个模块可能依赖 CMD 模块，也可能依赖普通文件。这会带来认识混乱。
4. 还会导致构建工具的复杂度急增，甚至不可预测。

综合以上各种考虑，从 Sea.js 2.1 起，去除 shim 插件，不再支持。

如果需要继续使用 jquery 插件，建议先封装成 CMD 模块。真的不是太难，而是一劳永逸。

**Comment by vitsippa** [comment]
1. 去除后依赖关系如何实现？比如 jQuery.datepicker依赖jQuery。改用`require.async()`?我不认为这是好办法。
1. 新版添加或者删除某些功能是否偏激。比如说去掉shim插件，是否应该将这个插件标记为已过时，兼容一段时间后再删除。
1. 文档是否应该更系统化一点？？

本打算在项目中使用sea.js，经过这段时间的学习后发现，sea.js更适合用于实验性的项目。(个人观点)

**Comment by Pines-Cheng** [comment]
来回折腾太麻烦了，能不能考虑一下版本兼容性。
