### ISSUE TITLE
grunt工具使用疑惑

### ISSUE THREAD

**Issue by pengfeiWang** [seajs/seajs#763]
构建前

```
define(function ( require, exports, module ){
    var G = require('global');
    var Comments = require('comment');
})
```

构建后

```
define("pro-res/js/init", [ "global", "comment" ], function(require, exports, module) {

});
```

(1) define(), 第一个参数是否要绝对路径, 看起来没有构建前的代码清晰, 而且, require也被缩减了, 不知道是否有影响, 另外sea根据文件自身加载模块, 这样的话是否不需改动就可以加载到模块
(2)  define(), 第一个参数根据什么生成
(3) 构建后的文件下会多个src目录, 在配置中是否可以不生成这个目录,
(4) 有些模块不想合并, 有些要合并, 想请指点下合并策略, 该如何配置
(5) 怎么能不创建 带 -debug的文件呢，貌似这样

```
 options:{  debug: false }
```

经过尝试:

(2) define(), 第一个参数根据options生成, 不知是否正确

```
options : {
    idleading : 'static/project/pro-res/'
}
```

(3) src这个目录不在生成了, 不过还是不知道如何消失的, 不能重现了, 悲剧

刚刚接触seajs, 有一些问题应该是很幼稚, 见笑了

**Comment by dahai300** [comment]
也遇到了同样问题，@pengfeiWang ，你是怎么解决的
