### ISSUE TITLE
不带id的seajs自身script节点的获取可能会出问题

### ISSUE THREAD

**Issue by nuintun** [seajs/seajs#811]
源码中关于`seajs`自身节点的获取：

``` js
// Recommend to add `seajsnode` id for the `sea.js` script element
var loaderScript = doc.getElementById("seajsnode") ||
    scripts[scripts.length - 1]
```

如果是这样引入的：

``` html
<script type="text/javascript" src="/path/2.0.1/sea.js"></script>
<script type="text/javascript">
    seajs.use('/path/app/main');
</script>
```

会导致节点获取异常吧？
按照现在的做法可能照成获取路径有问题，模块加载异常，会把新手搞的一头雾水的（虽说推荐`id`，但很多新手都不会在意这点）！:anguished:

**Comment by vrxubo** [comment]
var d = document.createElement("script"),
d.src ="/path/2.0.1/sea.js";
document.body.appendChild(d);
但是有没有考虑过有人会这么用, 某个360浏览器的插件就是这么引的seajs,  导致页面在装了这个插件的360浏览器里报错
http://plug.xiaoyu.kuaizhe.com/client/js02/xyscore_main.js
