### ISSUE TITLE
seajs 2.1.1中去掉了seajs.modify 后，如何preload CDN 中的jquery ？

### ISSUE THREAD

**Issue by lchuilu** [seajs/seajs#862]
之前1.3.1 的时候 引用 jquery 可以先引用一个原始的没经过 cmd修改的jquery 然后使用

<pre>
 seajs.modify("jquery", function(require, exports) {
   window.jQuery = window.$ = exports
 })
</pre>

将 $ 暴露出来， 但升级2.1.1以后 seajs.modify 已经被去掉了  ，那现在该如何做才能在不修改 jquery的情况下，preload jquery 呢？

**Comment by WhoIsSmile** [comment]
只能该代码吗？我还想用一些网上的cdn 加速呢
