### ISSUE TITLE
社区贡献的优秀文章

### ISSUE THREAD

**Issue by afc163** [seajs/seajs#916]
这里收集社区今年来贡献的一些优秀文档，简单按下面的维度分类，并在文档后面标注文章是基于哪个版本写的。

本文长期维护更新，欢迎大家推荐好的文章，也感谢以下文章作者的出色工作。

---
## 入门
- [HelloSea.js：一本深入浅出地分析 Sea.js 的模块机制，前端模块化的小书。](https://github.com/Bodule/HelloSea.js) `2.1.x`
- [Why SeaJS by Chaos](http://chaoskeh.com/blog/why-seajs.html) `2.1.x`
- [一步步学会使用SeaJS 2.0](http://hi.baidu.com/liuda101/item/54bcf8d0b6a65602d68ed057#713670-tsina-1-87095-128ff9f28d958dae738be418601ffbcd) `2.0.x`
- [seajs实现前端模块化之Hello World](http://q-e-d.github.io/javascript/seajs-hello-world/) `2.0.x`
- [SeaJS 所为何](http://cyj.me/why-seajs/zh/#intro) `1.3.x`
- [seajs 非权威指南](http://madscript.com/javascript/seajs-the-non-definitive-guide/) `1.3.x`
- [使用SeaJS实现模块化JavaScript开发](http://blog.codinglabs.org/articles/modularized-javascript-with-seajs.html) `1.3.x`
- [http://www.diguage.com/archives/82.html](http://www.diguage.com/archives/82.html) `1.3.x`
- [Hello, SeaJS!](http://mrzhang.me/blog/hello-seajs.html) `1.2.x`
- [高富帅seajs使用示例及spm合并压缩工具露脸](http://www.zhangxinxu.com/wordpress/2012/07/seajs-node-nodejs-spm-npm/) `1.2.x`
- [JavaScript模块化开发库之SeaJS](http://www.cnblogs.com/snandy/archive/2012/03/30/2423612.html) `1.1.x`
## 构建
- [spmjs网站收集的社区构建文档](http://docs.spmjs.org/contrib/)
- [为什么 SeaJS 模块的合并这么麻烦 ](http://chaoskeh.com/blog/why-its-hard-to-combo-seajs-modules.html)
- [如何使用 Spm2 压缩合并业务模块](http://chaoskeh.com/blog/how-to-build-seajs-business-module-by-spm2.html)
- [seajs实现前端模块化之Hello World姐妹篇之部署看我的](http://q-e-d.github.io/javascript/seajs-hello-world-deploy/)
## 应用
- [Sea.js 如何与 Rails 结合](http://chaoskeh.com/blog/how-to-integrates-seajs-with-rails.html)
- [seajs+backbone实现单页面应用模块自动加载](http://www.cnblogs.com/mapping/archive/2013/03/03/2941812.html)
- [SeaJS 组件库 by panxuepeng](http://panxuepeng.github.io/seajslib/)
- [sea.js在实际项目中的一些应用思路](http://xbingoz.com/494.html)

**Comment by tianzhen** [comment]
业务看了下3.0的源码，作了些注释，以及对模块源码的解说，大家共同学习。
http://blog.csdn.net/yanyan19880509/article/details/48932851 （seajs3.0模块依赖加载 及 源码注释）

**Comment by wantwantxu** [comment]
与dojo冲突怎么办？
