### ISSUE TITLE
seajs同时存在bootstrap tooltip和jquery ui tooltip冲突

### ISSUE THREAD

**Issue by aa403210842** [seajs/seajs#935]
初次运用seajs 版本2.1.1到项目，不是很懂，下面是我的描述，不知道算不算讲的清楚。
bootstrap和jquery ui都已cmd化了
main.js
define(function(require, exports) {
       var $ = require('jquery');
       require('bootstrap');
           $('[data-toggle="tooltip"]').tooltip();
};
ui.js中我只用sortable
define(function(require, exports) {
    var $ = require('jquery');
    require('js/jquery/jquery-ui/jquery-ui-1.9.2.custom.min.js');
    exports.sortable = function() {
 $(".js-sortable").sortable({
//code
});
}
});
我单单引用main.js时没有报错
seajs.use('main');
而两个一起用的时候，bootstrap.js就报错了
seajs.use('main');
seajs.use('ui',function(ui)(){
ui.sortable();
});
报错：
TypeError: i.show is not a function

...t:function(){return this.getTitle()},getPosition:function(){var t=this.$element[...

bootstrap.min.js (第 8 行)
TypeError: n.hide is not a function

...t:function(){return this.getTitle()},getPosition:function(){var t=this.$element[...

**Comment by zhua2014** [comment]
就是seajs造成的，作者别装B。seajs同步都没做好，use的时候，相互覆盖了

**Comment by afc163** [comment]
什么时候了还用 seajs

**Comment by lizzie** [comment]
我觉得可以关闭 issue 功能了

**Comment by 644792799** [comment]
@afc163 什么意思，还能愉快的入坑不，求指路

**Comment by afc163** [comment]
https://github.com/seajs/seajs/issues/1605
