### ISSUE TITLE
我改变了jquery.js存放的目录后，就引用不到了。

### ISSUE THREAD

**Issue by xiang-fish** [seajs/seajs#954]
我改变了jquery.js存放的目录后，var $ = require('jquery');就引用不到了。
![png](https://f.cloud.github.com/assets/5515408/1188888/557617c6-23f3-11e3-9dea-f7a8aff2c956.PNG)
改变后，上图执行exec()结果为null...

**Comment by a-lian123** [comment]
为什么开始的query并没有define，放在jquery/jquery/路径下就可以能？这样的匹配原则是怎样匹配的？
