### ISSUE TITLE
如何改造现有文件为 CMD 模块

### ISSUE THREAD

**Issue by afc163** [seajs/seajs#971]
# 如何改造现有文件为 CMD 模块

经过一段考察，我们终于要在项目中引入模块机制和 Sea.js 了，那么如何将现有的文件改造成 CMD 模块就成了重要的问题。下面针对一些典型场景来说明包装的方式。

首先还是请大家详细了解下 [CMD 模块定义规范](https://github.com/seajs/seajs/issues/242)，只要洞悉事物的定义和本质，一切问题可迎刃而解。
## 改造主流模块

这里指的是 jQuery、Moment、Backbone、underscore 等业界主流模块，这些模块一般都有对 AMD 和 CommonJS 的支持代码，例如 jQuery 源文件的最后几行：

``` js
if ( typeof module === "object" && module && typeof module.exports === "object" ) {
    module.exports = jQuery;
} else {
    window.jQuery = window.$ = jQuery;

    if ( typeof define === "function" && define.amd ) {
        define( "jquery", [], function () { return jQuery; } );
    }
}
```

还有 Backbone 里：

``` js
var Backbone;
if (typeof exports !== 'undefined') {
  Backbone = exports;
} else {
  Backbone = root.Backbone = {};
}
```

对于有这些兼容代码的，只需要去掉 define.amd 的支持，或是直接包装上 `define` 就可以了。

``` js
define(function(require, exports, module) {
  // code here ...
});
```

如果没有模块化的兼容代码，有时候需要手动引入依赖，以及暴露对应的接口。

``` js
define(function(require, exports, module) {
  var $ = require('$');
  // code here ...
  module.exports = Placeholders;
});
```

可以参考 [cmdjs/gallery](https://github.com/cmdjs/gallery) 里的 [Gruntfile](https://github.com/cmdjs/gallery/blob/master/moment/Gruntfile.js) 对这些主流模块的代码替换方式。
## 现有的 JS 文件

对于一些现有的普通 JS 文件，相对简单的多，参考 CMD 的[书写规范](https://github.com/seajs/seajs/issues/242)，把那些暴露到全局命名空间的接口用 CMD 的方式进行改造就可以了。

比如现有文件 `util.js` 。

``` js
window.util = window.util || {};
util.addClass = function() {
  window.css();
};
util.queryString = function() {};
```

改为：

``` js
define(function(require, exports, module) {
  // 引入依赖
  var css = require('css');

  util.addClass = function() {
    css();
  };
  util.queryString = function() {};

  // 暴露对应接口
  module.exports = util;
});
```

这里不啰嗦，就是基本的 CMD 书写规范。实际的改造过程中，情况可以比上面的例子要复杂一些，具体情况具体解决就行。
## 改造 jQuery 插件

这也是一个经常遇到的问题，我们推荐以下的包装方式：

``` js
// jquery-plugin-abc
define(function(require, exports, module) {
  var $ = require('$');
  // 插件的代码
  $.fn.abc = function() {};
});
```

这样的改造方式实际上是强化了原有的 $ 对象（而不是重新包装出一个新的 $），在实际调用时，可以用下面的方式：

``` js
seajs.use(['$', 'jquery-plugin-abc'], function($) {
  // $ 有了 jquery-plugin-abc 所提供的插件功能
  $.abc();
});
```

更多 jQuery 插件的包装，可以参考 [cmdjs/jquery](https://github.com/cmdjs/jquery) 里的做法。
## 工具

除了手动的方式修改代码外，我们推荐使用 [Grunt](http://gruntjs.com) 来进行统一的改造，官方也通过 Grunt 改造了很多主流模块和 jQuery 插件，具体的操作手册见 [引入 CMD 模块指南](https://github.com/cmdjs/gallery/blob/master/README.md) 。你可以在 [cmdjs/gallery](https://github.com/cmdjs/gallery) 和 [cmdjs/jquery](https://github.com/cmdjs/jquery) 中找到具体的 Gruntfile ，从而借鉴到您的项目中去。所有打包好的模块可以在 [spmjs.org](https://spmjs.org/) 中找到。
## 小结

上面提供的是原有代码包装为 `CMD 书写规范` 的方法，在具体上线前，可能还需要打包为具名模块（包含 ID 的模块）。关于构建方面的进一步知识可以参考 [构建工具](https://github.com/seajs/seajs/issues/538) 。

这里提到的包装方式都比较典型和简单，具体的实践可能千差万别。您在项目中有什么探索、实践和问题，欢迎来这里分享和提问。

**Comment by jieyou** [comment]
截止到目前，jQuery依然没有自己实现对CMD的兼容吗？  目前还是需要手动改造？

**Comment by hhsh** [comment]
有个错误指出一下：
 .abc();是实例方法，不是类方法，所以不能如此调用： $.abc();

**Comment by Suzixuan** [comment]
关于组件依赖于jQuery的问题：
![qq 20150227181046](https://cloud.githubusercontent.com/assets/10936781/6410654/f90d34d8-beab-11e4-8dd4-fb8ed2af4a2f.png)

调用：
![qq 20150227181135](https://cloud.githubusercontent.com/assets/10936781/6410670/184255f4-beac-11e4-81c2-e69f485a5d3f.png)

在新版浏览器上（火狐）正常，但在IE8下就报错。于是我就试着再封装jQuery和插件，结果是IE8没报错，但是插件也没有正常运作。

**Comment by jack-Lo** [comment]
请问如何改造那种链入的资源，像百度地图这样<script src="http://api.map.baidu.com/api?v=2.0&ak=123456"></script>的？

**Comment by kmvan** [comment]
没法


 

-------- Original Message --------
From：jack <notifications@github.com>
Time：Wed 3/4 PM 08:37
To：seajs/seajs <seajs@noreply.github.com>
Cc："Km.Van" <kmvan.com@gmail.com>
Subject：Re: [seajs] 如何改造现有文件为 CMD 模块 (#971)

**Comment by nickeljew** [comment]
为什么我去掉 jQuery 中的 define.amd后，var $ = require("jquery");  $是undefined?
 但是不赋值给$就可以正常使用。

**Comment by mozackye** [comment]
cmdjs/gallery 里没有的js怎么改造啊  gmu怎么改造啊   在外面套个define好像不行啊   都要自己改造太麻烦了啊

**Comment by mozackye** [comment]
都要去看懂js插件的源码吗  搞笑

**Comment by mozackye** [comment]
define(function(require, exports, module) {
  var $ = require('$');
  // code here ...
  module.exports = Placeholders;
});    这个Placeholders是什么东东  能举个例子吗

**Comment by suibobuzhuliu** [comment]
define(function(require, exports, module) {
    // jquery源码
    return window.$;
});

**Comment by jack-Lo** [comment]
seajs模块有shim的实现吗？

**Comment by lilugirl** [comment]
seajs如何包裹bootstrap.js

**Comment by sunstarvip** [comment]
请问下按照文档介绍的方法封装了uploadify插件后，能够正常调用但是功能无法使用，而且初始化过程中还提示了看不明白的错误。有没有哪位大神封装过uploadify插件，应该如何封装和调用呢？

**Comment by sunstarvip** [comment]
在sea剔除了shim插件的3.0版本里面每一个非CMD的插件都需要我手动去重新模块化，并且还不一定能成功，更痛苦的是基本上除了自己写的JS所有第三方文件基本都是非CMD的，如此痛苦的开发经历我感觉远远偏离了我最初准备使用sea的初衷，不仅没有提升效率反而被各种模块化的问题困扰。虽然感觉作者剔除shim插件的初衷是好的，但是感觉实际结果只能是我转投了requirejs。
