### ISSUE TITLE
循环引用，不提示错误，也不运行：

### ISSUE THREAD

**Issue by LongEth** [seajs/seajs#991]
循环引用，不提示错误，也不运行：

a.js

define('a',function(require,exports,module){
    var b = require('./b');
    b.say()
    exports.say = function(){
        alert('hello a')
    }
});

b.js

define('b', function(require, exports, module) {
    var a = require('./a');
    a.say('a')
    exports.say = function(){
        alert('hello b')
    }
});

sea.html

<script>
  seajs.use('b')
</script>

**Comment by zdjray** [comment]
确实比较坑,当没有发现是循环引用的问题时,没有任何提示.找了很久也不知道原因所在.支持重构解决循环依赖的问题,不过要是有插件能发现就不会掉进去出不来了.

**Comment by zdjray** [comment]
建议假如有循环依赖还是可以执行,执行到循环依赖处再停止会比较好

**Comment by zdjray** [comment]
建议假如有循环依赖还是可以执行,执行到循环依赖处再停止会比较好
